// Boilerplate filter: identifies and removes low-value content before training.
// Strips frontmatter, license blocks, auto-generated markers, TOC, and
// excessive whitespace to produce clean training-ready text.

use regex::Regex;

/// Result of filtering a document.
#[derive(Debug, Clone)]
pub struct FilterResult {
    pub cleaned: String,
    pub removed_bytes: usize,
    pub original_bytes: usize,
    pub sections_removed: Vec<String>,
}

/// Filter boilerplate from a document, returning cleaned text suitable for training.
pub fn filter_boilerplate(content: &str) -> FilterResult {
    let original_bytes = content.len();
    let mut cleaned = content.to_string();
    let mut sections_removed: Vec<String> = Vec::new();

    // 1. Strip YAML frontmatter
    if let Some(stripped) = strip_frontmatter(&cleaned) {
        if stripped.len() < cleaned.len() {
            sections_removed.push("frontmatter".to_string());
            cleaned = stripped;
        }
    }

    // 2. Strip license/copyright blocks
    let before = cleaned.len();
    cleaned = strip_license_blocks(&cleaned);
    if cleaned.len() < before {
        sections_removed.push("license_block".to_string());
    }

    // 3. Strip auto-generated markers and their content
    let before = cleaned.len();
    cleaned = strip_autogenerated(&cleaned);
    if cleaned.len() < before {
        sections_removed.push("autogenerated".to_string());
    }

    // 4. Strip table of contents
    let before = cleaned.len();
    cleaned = strip_toc(&cleaned);
    if cleaned.len() < before {
        sections_removed.push("toc".to_string());
    }

    // 5. Strip HTML comments
    let before = cleaned.len();
    cleaned = strip_html_comments(&cleaned);
    if cleaned.len() < before {
        sections_removed.push("html_comments".to_string());
    }

    // 6. Collapse excessive blank lines (3+ → 2)
    cleaned = collapse_blank_lines(&cleaned);

    // 7. Trim leading/trailing whitespace
    cleaned = cleaned.trim().to_string();

    let removed_bytes = original_bytes.saturating_sub(cleaned.len());

    FilterResult {
        cleaned,
        removed_bytes,
        original_bytes,
        sections_removed,
    }
}

/// Strip YAML frontmatter (--- ... ---) from the start of content.
fn strip_frontmatter(content: &str) -> Option<String> {
    let trimmed = content.trim_start();
    if !trimmed.starts_with("---") {
        return Some(content.to_string());
    }

    let after_open = &trimmed[3..];
    if let Some(close_pos) = after_open.find("\n---") {
        let after_close = &after_open[close_pos + 4..];
        // Skip any trailing newline after closing ---
        let result = after_close.strip_prefix('\n').unwrap_or(after_close);
        Some(result.to_string())
    } else {
        Some(content.to_string())
    }
}

/// Strip license/copyright header blocks (common in source files and docs).
fn strip_license_blocks(content: &str) -> String {
    let lines: Vec<&str> = content.lines().collect();
    let mut result_lines: Vec<&str> = Vec::with_capacity(lines.len());
    let mut i = 0;
    let mut in_license = false;

    while i < lines.len() {
        let trimmed = lines[i].trim().to_lowercase();

        // Detect start of license block
        if !in_license
            && (trimmed.contains("copyright")
                || trimmed.contains("licensed under")
                || trimmed.contains("license:")
                || trimmed.starts_with("// spdx-license")
                || trimmed.starts_with("# spdx-license")
                || trimmed.starts_with("/* copyright")
                || trimmed.starts_with("// copyright"))
        {
            // Check if it's a comment block — consume until block ends
            if is_comment_line(lines[i]) {
                in_license = true;
                i += 1;
                continue;
            }
        }

        if in_license {
            if is_comment_line(lines[i]) {
                i += 1;
                continue;
            } else {
                in_license = false;
            }
        }

        result_lines.push(lines[i]);
        i += 1;
    }

    result_lines.join("\n")
}

fn is_comment_line(line: &str) -> bool {
    let trimmed = line.trim();
    trimmed.starts_with("//")
        || trimmed.starts_with('#')
        || trimmed.starts_with('*')
        || trimmed.starts_with("/*")
        || trimmed.starts_with("*/")
        || trimmed.starts_with("<!--")
        || trimmed.starts_with("-->")
}

/// Strip auto-generated content markers and the lines between them.
fn strip_autogenerated(content: &str) -> String {
    let lines: Vec<&str> = content.lines().collect();
    let mut result_lines: Vec<&str> = Vec::with_capacity(lines.len());
    let mut skip = false;

    for line in &lines {
        let lower = line.trim().to_lowercase();

        if lower.contains("auto-generated") || lower.contains("autogenerated")
            || lower.contains("do not edit") || lower.contains("generated by")
            || lower.contains("this file is generated")
        {
            skip = true;
            continue;
        }

        // End skip on blank line or heading
        if skip && (line.trim().is_empty() || line.trim().starts_with('#')) {
            skip = false;
        }

        if !skip {
            result_lines.push(line);
        }
    }

    result_lines.join("\n")
}

/// Strip markdown table of contents sections.
fn strip_toc(content: &str) -> String {
    let lines: Vec<&str> = content.lines().collect();
    let mut result_lines: Vec<&str> = Vec::with_capacity(lines.len());
    let mut in_toc = false;

    for line in &lines {
        let trimmed = line.trim().to_lowercase();

        // Detect TOC heading
        if trimmed == "## table of contents"
            || trimmed == "## contents"
            || trimmed == "## toc"
            || trimmed == "# table of contents"
        {
            in_toc = true;
            continue;
        }

        // End TOC at next non-TOC heading or substantial content
        if in_toc {
            if line.trim().starts_with("## ") || line.trim().starts_with("# ") {
                // Check it's not a TOC heading itself
                if !trimmed.contains("contents") && !trimmed.contains("toc") {
                    in_toc = false;
                    result_lines.push(line);
                }
            } else if !line.trim().is_empty()
                && !line.trim().starts_with('-')
                && !line.trim().starts_with('*')
                && !line.trim().starts_with('[')
                && !is_toc_entry(line)
            {
                // Non-list, non-link line → end of TOC
                in_toc = false;
                result_lines.push(line);
            }
            continue;
        }

        result_lines.push(line);
    }

    result_lines.join("\n")
}

fn is_toc_entry(line: &str) -> bool {
    let trimmed = line.trim();
    // Common TOC patterns: "- [Section](#section)" or "1. [Section](#section)"
    (trimmed.starts_with("- [") || trimmed.starts_with("* ["))
        && trimmed.contains("](#")
}

/// Strip HTML comments <!-- ... -->.
fn strip_html_comments(content: &str) -> String {
    let re = Regex::new(r"<!--[\s\S]*?-->").expect("valid regex");
    re.replace_all(content, "").to_string()
}

/// Collapse runs of 3+ blank lines down to 2.
fn collapse_blank_lines(content: &str) -> String {
    let re = Regex::new(r"\n{4,}").expect("valid regex");
    re.replace_all(content, "\n\n\n").to_string()
}

/// UniFFI-exported struct matching the UDL `BoilerplateResult` dictionary.
#[derive(Debug, Clone)]
pub struct BoilerplateResult {
    pub cleaned: String,
    pub removed_bytes: u64,
    pub sections_removed_json: String,
}

impl From<FilterResult> for BoilerplateResult {
    fn from(r: FilterResult) -> Self {
        BoilerplateResult {
            cleaned: r.cleaned,
            removed_bytes: r.removed_bytes as u64,
            sections_removed_json: serde_json::to_string(&r.sections_removed).unwrap_or_default(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_empty() {
        let result = filter_boilerplate("");
        assert_eq!(result.cleaned, "");
        assert_eq!(result.removed_bytes, 0);
    }

    #[test]
    fn test_strip_frontmatter() {
        let doc = "---\ntitle: Test\ndate: 2026-01-01\n---\n\nHello world.";
        let result = filter_boilerplate(doc);
        assert_eq!(result.cleaned, "Hello world.");
        assert!(result.sections_removed.contains(&"frontmatter".to_string()));
    }

    #[test]
    fn test_no_frontmatter_unchanged() {
        let doc = "Hello world.\nThis is a test.";
        let result = filter_boilerplate(doc);
        assert_eq!(result.cleaned, doc);
    }

    #[test]
    fn test_strip_license_comment() {
        let doc = "// Copyright 2026 Acme Corp.\n// Licensed under MIT.\n// All rights reserved.\n\nfn main() {}";
        let result = filter_boilerplate(doc);
        assert_eq!(result.cleaned, "fn main() {}");
        assert!(result.sections_removed.contains(&"license_block".to_string()));
    }

    #[test]
    fn test_strip_autogenerated() {
        let doc = "# API\n\n// This file is generated by codegen. Do not edit.\nconst X = 1;\n\n# Real Content\n\nParagraph here.";
        let result = filter_boilerplate(doc);
        assert!(result.cleaned.contains("Real Content"));
        assert!(result.cleaned.contains("Paragraph here"));
    }

    #[test]
    fn test_strip_toc() {
        let doc = "# My Doc\n\n## Table of Contents\n\n- [Intro](#intro)\n- [Details](#details)\n\n## Intro\n\nHello.";
        let result = filter_boilerplate(doc);
        assert!(result.cleaned.contains("## Intro"));
        assert!(result.cleaned.contains("Hello."));
        assert!(!result.cleaned.contains("Table of Contents"));
    }

    #[test]
    fn test_strip_html_comments() {
        let doc = "Hello <!-- hidden comment --> world.";
        let result = filter_boilerplate(doc);
        assert_eq!(result.cleaned, "Hello  world.");
    }

    #[test]
    fn test_collapse_blank_lines() {
        let doc = "Line 1\n\n\n\n\n\nLine 2";
        let result = filter_boilerplate(doc);
        assert_eq!(result.cleaned, "Line 1\n\n\nLine 2");
    }

    #[test]
    fn test_multiple_filters_combined() {
        let doc = "---\ntitle: Doc\n---\n\n// Copyright 2026 Foo\n// Licensed under MIT\n\n## Table of Contents\n\n- [A](#a)\n\n## A\n\nReal content here.";
        let result = filter_boilerplate(doc);
        assert!(result.cleaned.contains("Real content here."));
        assert!(!result.cleaned.contains("Copyright"));
        assert!(!result.cleaned.contains("title: Doc"));
        assert!(result.sections_removed.len() >= 2);
    }

    #[test]
    fn test_ffi_wrapper() {
        let doc = "---\nk: v\n---\n\nText.";
        let result: BoilerplateResult = filter_boilerplate(doc).into();
        assert_eq!(result.cleaned, "Text.");
        assert!(result.removed_bytes > 0);
        assert!(result.sections_removed_json.contains("frontmatter"));
    }

    #[test]
    fn test_preserves_code_content() {
        let doc = "fn compute(x: i32) -> i32 {\n    x * 2\n}\n\nfn main() {\n    let val = compute(21);\n    println!(\"{}\", val);\n}";
        let result = filter_boilerplate(doc);
        // No boilerplate to strip — content should be preserved
        assert_eq!(result.cleaned, doc);
        assert!(result.sections_removed.is_empty());
    }
}
