//! Atomic creation transaction (S1; DOCTRINE §6.3 step ordering with
//! rollback).
//!
//! Per DOCTRINE §6.3 the seven steps are:
//!
//!   1. Allocate `CompanionId` (in-memory, monotonic ULID).
//!   2. Create vault folder + `companion.toml` (filesystem; fsync).
//!   3. Insert registry record (SQLite transaction).
//!   4. Materialize `ModelProfile` (same SQLite transaction; in our
//!      schema this is denormalised into the `companions` row's
//!      `base_model`, `system_prompt_preset`, `tool_affinities`
//!      columns — no separate `model_profiles` table is required).
//!   5. Allocate graph slice (recorded as a unique `graph_slice`
//!      slug on the row; real subgraph allocation is wired when the
//!      graph engine integrates in a later slice).
//!   6. Write audit-log entry (same SQLite transaction; CRITICAL —
//!      fsync required, and the transaction commit IS the fsync).
//!   7. Emit `CompanionRegistered` to observers (S5/S6/S7 wire
//!      this; S1 returns the populated record so the immediate
//!      caller can fan out itself).
//!
//! If any step fails, the entire transaction rolls back: vault
//! folder deleted, SQLite rows automatically rolled back via the
//! transaction's Drop. The user sees a typed `CreationError` keyed
//! to the failing step.
//!
//! Test injection: `FailureInjection` lets the unit tests force a
//! failure at any step and assert the rollback restored the prior
//! state exactly.

use std::path::{Path, PathBuf};

use rusqlite::params;

use super::audit::{AuditEventKind, CompanionRegisteredPayload};
use super::registry::{CompanionRegistry, RegistryError};
use super::{Companion, CompanionId, CompanionSpec, ToolKind};

const VAULT_TOML_TEMPLATE: &str =
    "# companion.toml — auto-generated by agent_core companion registry.\n\
     # See DOCTRINE.md §6.3 for the canonical creation transaction.\n";

/// Errors emitted by the §6.3 creation flow. Each variant maps to
/// the step that failed so callers can present a useful message
/// and so tests can assert which step rolled back.
#[derive(Debug, thiserror::Error)]
pub enum CreationError {
    #[error("validation: {0}")]
    Validation(String),
    #[error("step 2 vault folder: {0}")]
    Step2Vault(#[source] std::io::Error),
    #[error("step 3 registry insert: {0}")]
    Step3Registry(#[source] rusqlite::Error),
    #[error("step 4 model profile: {0}")]
    Step4ModelProfile(String),
    #[error("step 5 graph slice: {0}")]
    Step5GraphSlice(#[source] rusqlite::Error),
    #[error("step 6 audit log: {0}")]
    Step6Audit(#[source] rusqlite::Error),
    #[error("commit: {0}")]
    Commit(#[source] rusqlite::Error),
    #[error("registry: {0}")]
    Registry(#[from] RegistryError),
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
}

/// Test-only failure injection. Specifies which step the
/// transaction should fail on synthetically so the test can assert
/// rollback behaviour. None of these variants exist in production
/// code paths; they're only consulted when `Some(...)` is passed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FailureInjection {
    Step2VaultFolder,
    Step3RegistryInsert,
    Step4ModelProfile,
    Step5GraphSlice,
    Step6AuditLog,
}

/// Run the §6.3 atomic creation transaction. Returns the populated
/// `Companion` record on success, or a typed `CreationError` keyed
/// to the failing step on failure. On failure the persistent state
/// (vault folder, SQLite rows) is restored exactly to its
/// pre-transaction shape.
///
/// `vault_root` is the user's `EpistemosVault/` parent. The spec's
/// `vault_path` must be inside it (validated in §6.2).
pub fn create_companion(
    registry: &mut CompanionRegistry,
    spec: CompanionSpec,
    vault_root: &Path,
) -> Result<Companion, CreationError> {
    create_companion_with_failure(registry, spec, vault_root, None)
}

/// Test-only variant of `create_companion` that synthetically fails
/// at the given step. Defined under `#[cfg(any(test, feature = ...))]`
/// would be cleaner, but we keep it `pub` (no cfg) so integration
/// tests in sibling crates can drive the same flow once the FFI
/// surface lands. The `failure` parameter is unused in production
/// callers (always `None`).
pub fn create_companion_with_failure(
    registry: &mut CompanionRegistry,
    spec: CompanionSpec,
    vault_root: &Path,
    failure: Option<FailureInjection>,
) -> Result<Companion, CreationError> {
    let started = std::time::Instant::now();

    // §6.2 input validation — fail fast before touching state.
    validate_spec(&spec, vault_root)?;

    // Step 1: allocate id.
    let id = CompanionId::new_ulid();

    // Step 2: vault folder + companion.toml. Synthetic failure
    // either before or after the on-disk creation. After-failure is
    // closer to a real disk-full mid-write, so we fail there.
    if failure == Some(FailureInjection::Step2VaultFolder) {
        return Err(CreationError::Step2Vault(std::io::Error::other(
            "synthetic step-2 failure",
        )));
    }
    let vault_path = ensure_vault_folder(&spec.vault_path)?;
    let mut folder_guard = VaultFolderGuard::new(&vault_path);

    // Step 3 onwards live in a SQLite transaction so any failure
    // automatically rolls back via Drop on `txn`.
    let conn = registry.connection_mut();
    let txn = conn
        .transaction()
        .map_err(CreationError::Step3Registry)?;

    let now = txn
        .query_row("SELECT datetime('now')", [], |row| row.get::<_, String>(0))
        .map_err(CreationError::Step3Registry)?;

    let graph_slice = format!("slice_{}", id);

    // Step 3: registry insert.
    if failure == Some(FailureInjection::Step3RegistryInsert) {
        return Err(CreationError::Step3Registry(
            rusqlite::Error::ExecuteReturnedResults,
        ));
    }
    txn.execute(
        "INSERT INTO companions
            (id, name, head_shape, palette_ref, eyes, arms, prop_ref, accessory_ref,
             role, base_model, system_prompt_preset, tool_affinities,
             vault_path, graph_slice, created_at, updated_at, archived_at,
             farm_position_x, farm_position_y, config_version)
         VALUES
            (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?15, NULL,
             ?16, ?17, 1)",
        params![
            id.to_string(),
            &spec.name,
            spec.head_shape.as_str(),
            &spec.palette_ref,
            spec.eyes.as_str(),
            spec.arms.as_str(),
            spec.prop.map(|p| p.as_str()),
            spec.accessory_ref.as_deref(),
            spec.role.as_str(),
            &spec.base_model,
            &spec.system_prompt_preset,
            spec.tool_affinities.to_le_bytes().to_vec(),
            spec.vault_path.to_string_lossy().to_string(),
            &graph_slice,
            &now,
            spec.farm_position.0 as f64,
            spec.farm_position.1 as f64,
        ],
    )
    .map_err(CreationError::Step3Registry)?;

    // Step 4: model profile materialisation. In our schema this is
    // the denormalised columns above; we re-validate and emit a
    // synthetic failure if requested. Real validation: base_model
    // is non-empty and tool affinities are non-zero.
    if failure == Some(FailureInjection::Step4ModelProfile) {
        return Err(CreationError::Step4ModelProfile(
            "synthetic step-4 failure".to_string(),
        ));
    }
    if spec.base_model.is_empty() {
        return Err(CreationError::Step4ModelProfile(
            "base_model must be non-empty".to_string(),
        ));
    }

    // Step 5: graph slice allocation. At S1 we record a unique slug
    // (`slice_<id>`) on the row above. The dedicated slug column is
    // declared UNIQUE so a colliding slug would fail at insert. The
    // failure injection emulates a graph-engine refusal.
    if failure == Some(FailureInjection::Step5GraphSlice) {
        return Err(CreationError::Step5GraphSlice(
            rusqlite::Error::ExecuteReturnedResults,
        ));
    }
    // Real allocation work lives in a future slice; for S1 the
    // unique-slug invariant is the entire effect of step 5.

    // Step 6: audit log. CRITICAL per §6.5 — without an audit
    // entry the registry insert is rolled back.
    if failure == Some(FailureInjection::Step6AuditLog) {
        return Err(CreationError::Step6Audit(
            rusqlite::Error::ExecuteReturnedResults,
        ));
    }
    let payload = CompanionRegisteredPayload {
        name: spec.name.clone(),
        head_shape: spec.head_shape.as_str().to_string(),
        palette: spec.palette_ref.clone(),
        eyes: spec.eyes.as_str().to_string(),
        arms: spec.arms.as_str().to_string(),
        prop: spec.prop.map(|p| p.as_str().to_string()),
        role: spec.role.as_str().to_string(),
        base_model: spec.base_model.clone(),
        system_prompt_preset: spec.system_prompt_preset.clone(),
        tool_affinities: tool_affinities_to_strings(&spec),
        vault_path: spec.vault_path.to_string_lossy().to_string(),
        graph_slice: graph_slice.clone(),
        preset: None,
        registration_duration_ms: started.elapsed().as_millis() as u64,
        created_by: "user".to_string(),
    };
    let payload_json =
        serde_json::to_string(&payload).map_err(|e| {
            CreationError::Step6Audit(rusqlite::Error::FromSqlConversionFailure(
                0,
                rusqlite::types::Type::Text,
                Box::new(e),
            ))
        })?;
    txn.execute(
        "INSERT INTO companion_audit_log
            (companion_id, event_type, payload, created_at)
         VALUES (?1, ?2, ?3, ?4)",
        params![
            id.to_string(),
            AuditEventKind::CompanionRegistered.as_str(),
            payload_json,
            &now,
        ],
    )
    .map_err(CreationError::Step6Audit)?;

    // Commit — fsync of every change above lands here. After this
    // point the row is durable and the folder guard must disarm.
    txn.commit().map_err(CreationError::Commit)?;
    folder_guard.disarm();

    // Step 7: caller-side observer fanout. S1 surfaces the
    // populated record; S5/S6/S7 layer their observers on top.
    let companion = registry
        .get(id)?
        .expect("freshly committed companion missing from registry");
    registry.activity_mut().register(id);
    Ok(companion)
}

fn validate_spec(spec: &CompanionSpec, vault_root: &Path) -> Result<(), CreationError> {
    // §6.2 — name: non-empty, ≤ 64 chars, filesystem-safe.
    if spec.name.trim().is_empty() {
        return Err(CreationError::Validation("name is empty".to_string()));
    }
    if spec.name.len() > 64 {
        return Err(CreationError::Validation(format!(
            "name length {} exceeds 64",
            spec.name.len()
        )));
    }
    if spec.name.contains('/') || spec.name.contains('\\') || spec.name.contains('\0') {
        return Err(CreationError::Validation(format!(
            "name '{}' contains forbidden filesystem characters",
            spec.name
        )));
    }

    // §6.2 — workspace: under vault root, normalised path component
    // doesn't escape via "..", parent (if existing) is writable.
    if !spec.vault_path.starts_with(vault_root) {
        return Err(CreationError::Validation(format!(
            "vault_path {:?} not under vault_root {:?}",
            spec.vault_path, vault_root
        )));
    }
    if spec
        .vault_path
        .components()
        .any(|c| matches!(c, std::path::Component::ParentDir))
    {
        return Err(CreationError::Validation(format!(
            "vault_path {:?} contains '..' — escaping the vault root is forbidden",
            spec.vault_path
        )));
    }

    // §6.2 — palette: when the user picked a Custom palette
    // (everything not in the curated provider catalog), the value
    // is treated as a sRGB hex literal `#RRGGBB` and must parse
    // and pass the WCAG AA contrast threshold against both light
    // and dark macOS sidebar backgrounds.
    if is_custom_palette(&spec.palette_ref) {
        validate_custom_palette_hex(&spec.palette_ref)?;
    }

    Ok(())
}

/// A palette reference is "Custom" if it doesn't match a curated
/// provider preset slug (`*_v1`, `*_v2`, …) — i.e. the user is
/// supplying a raw hex literal directly.
fn is_custom_palette(palette_ref: &str) -> bool {
    !palette_ref.ends_with("_v1")
        && !palette_ref.ends_with("_v2")
        && !palette_ref.ends_with("_v3")
}

/// `#RRGGBB` parser + WCAG AA (≥ 4.5:1) contrast check against
/// both the macOS dark-sidebar baseline (#1E1E1E) and light-sidebar
/// baseline (#F5F5F5). The ratio is computed from relative
/// luminance per WCAG 2.1.
fn validate_custom_palette_hex(palette_ref: &str) -> Result<(), CreationError> {
    let bytes = palette_ref.as_bytes();
    if bytes.len() != 7 || bytes[0] != b'#' {
        return Err(CreationError::Validation(format!(
            "custom palette '{}' must be sRGB hex literal `#RRGGBB`",
            palette_ref
        )));
    }
    let parse_hex = |slice: &[u8]| -> Option<u8> {
        let s = std::str::from_utf8(slice).ok()?;
        u8::from_str_radix(s, 16).ok()
    };
    let r = parse_hex(&bytes[1..3]).ok_or_else(|| {
        CreationError::Validation(format!("palette '{}' has non-hex characters", palette_ref))
    })?;
    let g = parse_hex(&bytes[3..5]).ok_or_else(|| {
        CreationError::Validation(format!("palette '{}' has non-hex characters", palette_ref))
    })?;
    let b = parse_hex(&bytes[5..7]).ok_or_else(|| {
        CreationError::Validation(format!("palette '{}' has non-hex characters", palette_ref))
    })?;
    let dark = relative_luminance(0x1E, 0x1E, 0x1E);
    let light = relative_luminance(0xF5, 0xF5, 0xF5);
    let chosen = relative_luminance(r, g, b);
    let cr_dark = contrast_ratio(chosen, dark);
    let cr_light = contrast_ratio(chosen, light);
    // The palette must remain legible on whichever sidebar the
    // user is using — both directions matter. WCAG AA threshold
    // is 4.5:1 for body text; we use it as a coarse "this colour
    // won't disappear" gate.
    if cr_dark < 4.5 && cr_light < 4.5 {
        return Err(CreationError::Validation(format!(
            "palette '{}' contrast {:.2}:1 (dark) / {:.2}:1 (light) below WCAG AA 4.5:1 threshold",
            palette_ref, cr_dark, cr_light
        )));
    }
    Ok(())
}

fn relative_luminance(r: u8, g: u8, b: u8) -> f64 {
    let lin = |c: u8| -> f64 {
        let c = (c as f64) / 255.0;
        if c <= 0.03928 {
            c / 12.92
        } else {
            ((c + 0.055) / 1.055).powf(2.4)
        }
    };
    0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b)
}

fn contrast_ratio(l1: f64, l2: f64) -> f64 {
    let (lighter, darker) = if l1 > l2 { (l1, l2) } else { (l2, l1) };
    (lighter + 0.05) / (darker + 0.05)
}

fn ensure_vault_folder(path: &Path) -> Result<PathBuf, CreationError> {
    std::fs::create_dir_all(path).map_err(CreationError::Step2Vault)?;
    let toml = path.join("companion.toml");
    std::fs::write(&toml, VAULT_TOML_TEMPLATE).map_err(CreationError::Step2Vault)?;
    Ok(path.to_owned())
}

/// RAII guard for the vault folder. If the transaction fails after
/// the folder is created, Drop deletes it. Disarming via `disarm()`
/// signals success — the folder stays put.
struct VaultFolderGuard {
    path: PathBuf,
    armed: bool,
}

impl VaultFolderGuard {
    fn new(path: &Path) -> Self {
        Self {
            path: path.to_owned(),
            armed: true,
        }
    }
    fn disarm(&mut self) {
        self.armed = false;
    }
}

impl Drop for VaultFolderGuard {
    fn drop(&mut self) {
        if self.armed {
            // Best-effort cleanup — failure here only logs a warning;
            // worst case the user sees an orphan folder which the
            // crash-recovery reconciliation pass (DOCTRINE §6.5)
            // would surface on next launch.
            let _ = std::fs::remove_dir_all(&self.path);
        }
    }
}

fn tool_affinities_to_strings(spec: &CompanionSpec) -> Vec<String> {
    use ToolKind::*;
    [
        (CodeEdit, "code_edit"),
        (CodeRead, "code_read"),
        (TestRun, "test_run"),
        (Git, "git"),
        (NoteCreate, "note_create"),
        (NoteRead, "note_read"),
        (NoteUpdate, "note_update"),
        (WebSearch, "web_search"),
        (GraphSearch, "graph_search"),
        (VaultRead, "vault_read"),
        (VaultWrite, "vault_write"),
        (Routing, "routing"),
        (Delegate, "delegate"),
        (DeepThink, "deep_think"),
        (Plan, "plan"),
    ]
    .into_iter()
    .filter(|(k, _)| spec.tool_affinities.has(*k))
    .map(|(_, s)| s.to_string())
    .collect()
}

#[cfg(test)]
#[allow(unused_imports)]
mod tests {
    use super::*;
    use crate::companions::audit::CompanionRegisteredPayload;
    use crate::companions::{
        ArmStyle, CompanionRegistry, CompanionSpec, EyeStyle, HeadShape, PropKind,
        ProviderRole, ToolAffinities,
    };

    fn fixture_spec(vault_root: &Path, name: &str) -> CompanionSpec {
        CompanionSpec {
            name: name.to_string(),
            head_shape: HeadShape::Block,
            palette_ref: "claude_warm_v1".to_string(),
            eyes: EyeStyle::NegativeSpace,
            arms: ArmStyle::None,
            prop: Some(PropKind::Wrench),
            accessory_ref: None,
            role: ProviderRole::CodeWorker,
            base_model: "claude-sonnet-4-6".to_string(),
            system_prompt_preset: "careful_reviewer_v1".to_string(),
            tool_affinities: ToolAffinities::from_prop(PropKind::Wrench),
            vault_path: vault_root.join("Companions").join(name),
            farm_position: (10.0, 5.0),
        }
    }

    #[test]
    fn happy_path_creates_companion_and_audit_entry() {
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();

        let spec = fixture_spec(vault_root, "Sage Reviewer");
        let companion =
            create_companion(&mut registry, spec.clone(), vault_root).expect("happy path");

        // Persisted in registry.
        let fetched = registry.get(companion.id).unwrap().unwrap();
        assert_eq!(fetched.name, "Sage Reviewer");
        assert_eq!(fetched.head_shape, HeadShape::Block);
        assert_eq!(fetched.role, ProviderRole::CodeWorker);
        assert!(fetched.archived_at.is_none());
        assert!(fetched.graph_slice.starts_with("slice_"));

        // Vault folder + companion.toml created.
        let toml = spec.vault_path.join("companion.toml");
        assert!(toml.exists(), "vault toml created");

        // Audit log has one CompanionRegistered entry.
        let log = registry.audit_log(companion.id).unwrap();
        assert_eq!(log.len(), 1);
        assert_eq!(log[0].event_kind, AuditEventKind::CompanionRegistered);
        let payload: CompanionRegisteredPayload = log[0].payload_as().unwrap();
        assert_eq!(payload.name, "Sage Reviewer");
        assert_eq!(payload.role, "CodeWorker");
        assert!(payload.tool_affinities.iter().any(|s| s == "code_edit"));

        // Activity tracker has the companion at JustAcquired.
        assert_eq!(
            registry.activity().state(companion.id),
            Some(crate::companions::ActivityState::JustAcquired)
        );
    }

    #[test]
    fn rollback_when_step_3_registry_fails() {
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();
        let spec = fixture_spec(vault_root, "Step3Fail");

        let err = create_companion_with_failure(
            &mut registry,
            spec.clone(),
            vault_root,
            Some(FailureInjection::Step3RegistryInsert),
        )
        .unwrap_err();
        assert!(matches!(err, CreationError::Step3Registry(_)), "{err:?}");

        // No companions in the registry.
        assert!(registry.list_all().unwrap().is_empty());
        // Vault folder cleaned up by VaultFolderGuard.
        assert!(!spec.vault_path.exists(), "vault folder rolled back");
    }

    #[test]
    fn rollback_when_step_4_model_profile_fails() {
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();
        let spec = fixture_spec(vault_root, "Step4Fail");

        let err = create_companion_with_failure(
            &mut registry,
            spec.clone(),
            vault_root,
            Some(FailureInjection::Step4ModelProfile),
        )
        .unwrap_err();
        assert!(matches!(err, CreationError::Step4ModelProfile(_)), "{err:?}");
        assert!(registry.list_all().unwrap().is_empty());
        assert!(!spec.vault_path.exists());
    }

    #[test]
    fn rollback_when_step_5_graph_slice_fails() {
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();
        let spec = fixture_spec(vault_root, "Step5Fail");

        let err = create_companion_with_failure(
            &mut registry,
            spec.clone(),
            vault_root,
            Some(FailureInjection::Step5GraphSlice),
        )
        .unwrap_err();
        assert!(matches!(err, CreationError::Step5GraphSlice(_)), "{err:?}");
        assert!(registry.list_all().unwrap().is_empty());
        assert!(!spec.vault_path.exists());
    }

    #[test]
    fn rollback_when_step_6_audit_fails() {
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();
        let spec = fixture_spec(vault_root, "Step6Fail");

        let err = create_companion_with_failure(
            &mut registry,
            spec.clone(),
            vault_root,
            Some(FailureInjection::Step6AuditLog),
        )
        .unwrap_err();
        assert!(matches!(err, CreationError::Step6Audit(_)), "{err:?}");
        // The §6.3 doctrine specifies audit-log failure must roll
        // back the registry — verify no companion row leaked.
        assert!(registry.list_all().unwrap().is_empty());
        // Vault folder also rolled back.
        assert!(!spec.vault_path.exists());
    }

    #[test]
    fn step_2_failure_does_not_touch_db() {
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();
        let spec = fixture_spec(vault_root, "Step2Fail");

        let err = create_companion_with_failure(
            &mut registry,
            spec.clone(),
            vault_root,
            Some(FailureInjection::Step2VaultFolder),
        )
        .unwrap_err();
        assert!(matches!(err, CreationError::Step2Vault(_)), "{err:?}");
        // SQLite never touched, vault never created.
        assert!(registry.list_all().unwrap().is_empty());
        assert!(!spec.vault_path.exists());
    }

    #[test]
    fn validation_rejects_empty_name() {
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();
        let mut spec = fixture_spec(vault_root, "OK");
        spec.name = "".to_string();

        let err = create_companion(&mut registry, spec, vault_root).unwrap_err();
        assert!(matches!(err, CreationError::Validation(_)), "{err:?}");
    }

    #[test]
    fn validation_rejects_path_outside_vault_root() {
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();
        let mut spec = fixture_spec(vault_root, "OK");
        spec.vault_path = PathBuf::from("/tmp/other-vault/Companions/Imposter");

        let err = create_companion(&mut registry, spec, vault_root).unwrap_err();
        assert!(matches!(err, CreationError::Validation(_)), "{err:?}");
    }

    #[test]
    fn duplicate_name_is_rejected_by_unique_constraint() {
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();

        let spec_a = fixture_spec(vault_root, "Twin");
        let _ = create_companion(&mut registry, spec_a, vault_root).unwrap();

        let spec_b = CompanionSpec {
            name: "Twin".to_string(),
            vault_path: vault_root.join("Companions").join("Twin-other"),
            ..fixture_spec(vault_root, "Twin-other")
        };
        let err = create_companion(&mut registry, spec_b, vault_root).unwrap_err();
        // Step 3 fires the SQLite UNIQUE constraint violation.
        assert!(matches!(err, CreationError::Step3Registry(_)), "{err:?}");
        // The duplicate's vault folder must NOT exist (rolled back).
        assert!(!vault_root
            .join("Companions")
            .join("Twin-other")
            .exists());
        // Original companion still present.
        let all = registry.list_active().unwrap();
        assert_eq!(all.len(), 1);
        assert_eq!(all[0].name, "Twin");
    }

    #[test]
    fn validation_rejects_name_with_forbidden_filesystem_chars() {
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();
        for bad in ["a/b", "back\\slash", "null\0byte"] {
            let mut spec = fixture_spec(vault_root, "OK");
            spec.name = bad.to_string();
            let err = create_companion(&mut registry, spec, vault_root).unwrap_err();
            assert!(matches!(err, CreationError::Validation(_)), "{bad}: {err:?}");
        }
    }

    #[test]
    fn validation_rejects_vault_path_with_parent_dir_escape() {
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();
        let mut spec = fixture_spec(vault_root, "Escapist");
        // "../" escape attempt that nominally starts under
        // vault_root via prefix but contains a parent-dir
        // component — should be rejected per §6.2.
        spec.vault_path = vault_root.join("Companions").join("..").join("Sneaky");
        let err = create_companion(&mut registry, spec, vault_root).unwrap_err();
        assert!(matches!(err, CreationError::Validation(_)), "{err:?}");
    }

    #[test]
    fn validation_accepts_curated_palette_refs_unchecked() {
        // Curated provider presets (`*_v1`) are NOT subject to
        // the hex/contrast gate — the catalog vouches for them.
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();
        for curated in ["claude_warm_v1", "kimi_indigo_v1", "local_teal_v1"] {
            let mut spec = fixture_spec(vault_root, &format!("CuratedFor_{curated}"));
            spec.palette_ref = curated.to_string();
            let _ = create_companion(&mut registry, spec, vault_root)
                .unwrap_or_else(|e| panic!("curated palette {curated} should validate: {e:?}"));
        }
    }

    #[test]
    fn validation_rejects_custom_palette_with_bad_hex() {
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();
        for bad in ["#XYZXYZ", "not-a-hex", "#FFF", "FFFFFF", "#GGGGGG"] {
            let mut spec = fixture_spec(vault_root, "BadPalette");
            spec.palette_ref = bad.to_string();
            let err = create_companion(&mut registry, spec, vault_root).unwrap_err();
            assert!(matches!(err, CreationError::Validation(_)), "{bad}: {err:?}");
        }
    }

    #[test]
    fn validation_rejects_custom_palette_below_contrast_threshold() {
        // Mid-grey (#808080) sits at ~3.95:1 vs both #1E1E1E and
        // #F5F5F5 — below the WCAG AA 4.5:1 threshold. Should
        // reject as a Custom palette.
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();
        let mut spec = fixture_spec(vault_root, "MidGrey");
        spec.palette_ref = "#808080".to_string();
        let err = create_companion(&mut registry, spec, vault_root).unwrap_err();
        assert!(matches!(err, CreationError::Validation(_)), "{err:?}");
        // And the offending hex should appear in the message so
        // the wizard can surface it.
        let msg = format!("{err:?}");
        assert!(msg.contains("#808080"), "{msg}");
    }

    #[test]
    fn validation_accepts_high_contrast_custom_palette() {
        // Pure white passes against the dark sidebar; pure black
        // passes against the light sidebar. Either side is enough.
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();
        for ok in ["#FFFFFF", "#000000", "#D97757"] {
            let mut spec = fixture_spec(vault_root, &format!("HighContrast_{}", &ok[1..]));
            spec.palette_ref = ok.to_string();
            let _ = create_companion(&mut registry, spec, vault_root).unwrap_or_else(|e| {
                panic!("high-contrast palette {ok} should validate: {e:?}")
            });
        }
    }

    #[test]
    fn archive_marks_row_and_logs_audit_entry() {
        let tmp = tempfile::tempdir().unwrap();
        let vault_root = tmp.path();
        let mut registry = CompanionRegistry::open_in_memory().unwrap();

        let spec = fixture_spec(vault_root, "ToArchive");
        let companion = create_companion(&mut registry, spec, vault_root).unwrap();
        assert_eq!(registry.list_active().unwrap().len(), 1);

        registry.archive(companion.id, Some("test")).unwrap();
        // No longer in active list, still in all list.
        assert!(registry.list_active().unwrap().is_empty());
        assert_eq!(registry.list_all().unwrap().len(), 1);
        // Activity tracker dropped the entry.
        assert_eq!(registry.activity().state(companion.id), None);
        // Audit log gained a CompanionArchived row.
        let log = registry.audit_log(companion.id).unwrap();
        assert_eq!(log.len(), 2);
        assert_eq!(log[0].event_kind, AuditEventKind::CompanionRegistered);
        assert_eq!(log[1].event_kind, AuditEventKind::CompanionArchived);
    }
}
