//! Resonance Gate — epistemic gating via 8-field signature.
//!
//! The Resonance Gate is the philosophical core of the Epistenos runtime.
//! Every claim that enters the system is evaluated against an 8-field
//! signature that determines whether the claim is **Promoted** (accepted
//! into higher residency), **Held** (kept at current level), or **Rejected**
//! (demoted or dropped).
//!
//! The eight fields encode:
//! 1. **Ternary claim state** — does the claim fit, wait, or fall?
//! 2. **Direction** — should we promote, demote, or hold?
//! 3. **Primality** — is this a fundamental or derived claim?
//! 4. **Resonance strength** — how much does it cohere with existing state?
//! 5. **KAM stability** — Kolmogorov-Arnold-Moser invariant measure
//! 6. **Evidence mass** — how much observational support exists?
//! 7. **Residency level** — L0 (sensory) → L_SE (self-evolving)
//! 8. **Learning mode** — which plasticity rule should govern adaptation?

use serde::{Deserialize, Serialize};
use std::collections::VecDeque;
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};
use thiserror::Error;
use tracing::{debug, info, instrument, warn};
use helios_core::TernaryState;
use hex;

// ---------------------------------------------------------------------------
// Core enums
// ---------------------------------------------------------------------------

/// Direction of change for a claim's residency.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Direction {
    /// Move the claim to a higher residency level.
    Promote,
    /// Move the claim to a lower residency level.
    Demote,
    /// Keep the claim at its current residency level.
    Hold,
}

/// Primality — distinguishes fundamental (prime) claims from derived
/// (composite) claims.
///
/// Prime claims are axiomatic or directly observed. Composite claims
/// are inferred, deduced, or generated by the model.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Primality {
    /// A fundamental claim — directly observed or axiomatic.
    Prime,
    /// A derived claim — inferred, composed, or model-generated.
    Composite,
}

/// Residency level — the hierarchical tier at which a claim is held.
///
/// The levels form a cognitive stack from raw sensory input (L0) up
/// to the self-evolving meta-layer (L_SE) where the model modifies
/// its own learning rules.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Residency {
    /// L0 — raw sensory / token-level input.
    L0,
    /// L1 — local feature / embedding level.
    L1,
    /// L2 — contextual / attention-level representations.
    L2,
    /// L3 — episodic / working-memory level.
    L3,
    /// L4 — long-term / consolidated knowledge.
    L4,
    /// L_SE — self-evolving meta-layer (titans, fast weights, DoRA).
    LSe,
}

impl Residency {
    /// Numeric level for comparison.
    pub fn level(self) -> u8 {
        match self {
            Residency::L0 => 0,
            Residency::L1 => 1,
            Residency::L2 => 2,
            Residency::L3 => 3,
            Residency::L4 => 4,
            Residency::LSe => 5,
        }
    }
}

/// Learning mode — which plasticity rule governs weight adaptation for
/// this claim or agent.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LearningMode {
    /// Stochastic Gradient Descent — standard backprop-based update.
    Sgd,
    /// Hebbian learning — "fire together, wire together".
    Hebbian,
    /// Elastic Weight Consolidation — protect important weights.
    Ewc,
    /// Fast weights — online adaptation with separate fast parameters.
    FastWeights,
    /// Meta-learning — learn how to learn (higher-order gradients).
    Meta,
}

/// The action the gate should take after evaluating a signature.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum GateAction {
    /// Accept the claim into the target residency.
    Promote,
    /// Keep the claim at its current residency.
    Hold,
    /// Reject the claim (demote or drop).
    Reject,
}

// ---------------------------------------------------------------------------
// ResonanceSignature — the 8-field vector
// ---------------------------------------------------------------------------

/// The full 8-field Resonance Signature that characterises a claim's
/// relationship to the cognitive state.
///
/// Each field is computed by [`compute_resonance`] and consumed by
/// [`gate_action`] to produce a [`GateAction`].
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResonanceSignature {
    /// `tau` — ternary claim state: {-1, 0, +1}.
    pub tau: TernaryState,
    /// `delta` — direction: Promote, Demote, Hold.
    pub delta: Direction,
    /// `pi` — primality: Prime (fundamental) vs Composite (derived).
    pub pi: Primality,
    /// `rho` — resonance strength ∈ [0.0, 1.0].
    /// Measures coherence with existing claims.
    pub rho: f32,
    /// `kappa` — KAM (Kolmogorov-Arnold-Moser) stability ∈ [0.0, 1.0].
    /// Measures whether the claim's addition preserves quasi-periodic
    /// orbits in the epistemic phase space (i.e. does not destabilise
    /// the knowledge manifold).
    pub kappa: f32,
    /// `eta` — evidence mass ∈ [0.0, 1.0].
    /// Fraction of available evidence slots that support this claim.
    pub eta: f32,
    /// `lambda` — residency level (L0 → L_SE).
    pub lambda: Residency,
    /// `learning_mode` — which plasticity rule to apply.
    pub learning_mode: LearningMode,
}

impl ResonanceSignature {
    /// Composite scalar — a single number summarising the signature.
    ///
    /// Weighted: 0.3·rho + 0.3·kappa + 0.2·eta + 0.2·tau_norm,
    /// where `tau_norm` maps {-1,0,+1} → {0.0,0.5,1.0}.
    pub fn composite_scalar(&self) -> f32 {
        let tau_norm = (self.tau.as_i8() as f32 + 1.0) / 2.0;
        0.3 * self.rho + 0.3 * self.kappa + 0.2 * self.eta + 0.2 * tau_norm
    }
}

// ---------------------------------------------------------------------------
// Claim / Context (re-exports from helios_core types with local wrappers)
// ---------------------------------------------------------------------------

/// A claim entering the Resonance Gate for evaluation.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Claim {
    pub id: [u8; 32],
    pub proposition: String,
    pub confidence: f32,
    pub evidence_count: usize,
    pub is_observed: bool,
    pub source_residency: Residency,
}

/// The cognitive context against which a claim is evaluated.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Context {
    pub active_claims: Vec<[u8; 32]>,
    pub feature_vector: Vec<f32>,
    pub current_residency: Residency,
    pub learning_mode: LearningMode,
}

// ---------------------------------------------------------------------------
// compute_resonance — full 8-field signature computation
// ---------------------------------------------------------------------------

/// Compute the complete 8-field Resonance Signature for a claim.
///
/// This is a **deterministic, pure function** — the same `(claim, context)`
/// pair always produces the same signature.
#[instrument(skip(claim, context), fields(claim_id = hex::encode(&claim.id)))]
pub fn compute_resonance(claim: &Claim, context: &Context) -> ResonanceSignature {
    // 1. tau — ternary state: does the claim fit the context?
    let tau = compute_tau(claim, context);

    // 2. rho — resonance strength: cosine similarity with context features
    let rho = compute_rho(claim, context);

    // 3. eta — evidence mass: fraction of evidence capacity used
    let eta = compute_eta(claim, context);

    // 4. kappa — KAM stability: does adding this claim preserve manifold structure?
    let kappa = compute_kappa(claim, context, rho, eta);

    // 5. delta — direction based on tau + rho + kappa
    let delta = compute_delta(tau, rho, kappa, eta);

    // 6. pi — primality: observed = Prime, inferred = Composite
    let pi = if claim.is_observed {
        Primality::Prime
    } else {
        Primality::Composite
    };

    // 7. lambda — target residency (may differ from source)
    let lambda = compute_lambda(claim.source_residency, delta, kappa);

    // 8. learning_mode — from context
    let learning_mode = context.learning_mode;

    let sig = ResonanceSignature {
        tau,
        delta,
        pi,
        rho: rho.clamp(0.0, 1.0),
        kappa: kappa.clamp(0.0, 1.0),
        eta: eta.clamp(0.0, 1.0),
        lambda,
        learning_mode,
    };

    info!(
        composite = sig.composite_scalar(),
        ?tau,
        ?delta,
        ?pi,
        rho,
        kappa,
        eta,
        ?lambda,
        ?learning_mode,
        "computed resonance signature"
    );

    sig
}

fn compute_tau(claim: &Claim, context: &Context) -> TernaryState {
    let overlap = context
        .active_claims
        .iter()
        .filter(|&c| *c == claim.id)
        .count();
    if overlap > 0 && claim.confidence > 0.7 {
        TernaryState::Pos
    } else if claim.confidence > 0.3 {
        TernaryState::Zero
    } else {
        TernaryState::Neg
    }
}

fn compute_rho(claim: &Claim, context: &Context) -> f32 {
    if context.feature_vector.is_empty() {
        return 0.5;
    }
    // Cosine similarity between claim confidence (as a scalar feature)
    // and the mean of the context feature vector.
    let mean_feature: f32 = context.feature_vector.iter().sum::<f32>() / context.feature_vector.len() as f32;
    let a = claim.confidence;
    let b = mean_feature;
    let dot = a * b;
    let norm_a = a.abs();
    let norm_b = b.abs();
    if norm_a == 0.0 || norm_b == 0.0 {
        0.0
    } else {
        let sim = dot / (norm_a * norm_b);
        (sim + 1.0) / 2.0 // map [-1,1] → [0,1]
    }
}

fn compute_eta(claim: &Claim, _context: &Context) -> f32 {
    // Evidence mass = evidence_count / (evidence_count + 10) with a soft ceiling.
    let count = claim.evidence_count as f32;
    count / (count + 10.0)
}

fn compute_kappa(_claim: &Claim, _context: &Context, rho: f32, eta: f32) -> f32 {
    // KAM stability heuristic: high coherence + sufficient evidence → stable manifold.
    // We model this as a soft-min of rho and eta, boosted when both are high.
    let base = rho.min(eta);
    let boost = (rho * eta).sqrt();
    (base + boost) / 2.0
}

fn compute_delta(tau: TernaryState, rho: f32, kappa: f32, eta: f32) -> Direction {
    match tau {
        TernaryState::Pos => {
            if rho > 0.75 && kappa > 0.6 && eta > 0.3 {
                Direction::Promote
            } else {
                Direction::Hold
            }
        }
        TernaryState::Zero => {
            if rho > 0.85 && kappa > 0.8 {
                Direction::Promote
            } else {
                Direction::Hold
            }
        }
        TernaryState::Neg => {
            if rho < 0.2 && kappa < 0.3 {
                Direction::Demote
            } else {
                Direction::Hold
            }
        }
    }
}

fn compute_lambda(current: Residency, delta: Direction, kappa: f32) -> Residency {
    let level = current.level();
    let new_level = match delta {
        Direction::Promote => (level + 1).min(5),
        Direction::Demote => level.saturating_sub(1),
        Direction::Hold => level,
    };
    // KAM stability bonus: if kappa > 0.9, allow an extra promotion step
    let bonus = if kappa > 0.9 && delta == Direction::Promote { 1 } else { 0 };
    let final_level = (new_level + bonus).min(5);
    match final_level {
        0 => Residency::L0,
        1 => Residency::L1,
        2 => Residency::L2,
        3 => Residency::L3,
        4 => Residency::L4,
        5 => Residency::LSe,
        _ => Residency::L0,
    }
}

// ---------------------------------------------------------------------------
// gate_action — threshold-based gate decision
// ---------------------------------------------------------------------------

/// Threshold configuration for the Resonance Gate.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct GateThresholds {
    /// Minimum composite scalar to Promote (default 0.65).
    pub promote_min: f32,
    /// Minimum composite scalar to Hold (default 0.35).
    pub hold_min: f32,
    /// Minimum KAM stability for promotion (default 0.5).
    pub kappa_min: f32,
    /// Minimum evidence mass for promotion (default 0.2).
    pub eta_min: f32,
}

impl Default for GateThresholds {
    fn default() -> Self {
        Self {
            promote_min: 0.65,
            hold_min: 0.35,
            kappa_min: 0.5,
            eta_min: 0.2,
        }
    }
}

/// Given a signature and optional thresholds, decide the gate action.
///
/// The default logic:
/// - **Promote** if composite ≥ promote_min AND kappa ≥ kappa_min AND eta ≥ eta_min
/// - **Hold** if composite ≥ hold_min
/// - **Reject** otherwise
#[instrument(skip(sig, thresholds))]
pub fn gate_action(sig: &ResonanceSignature, thresholds: Option<&GateThresholds>) -> GateAction {
    let t = thresholds.unwrap_or(&GateThresholds::default());
    let composite = sig.composite_scalar();

    if composite >= t.promote_min && sig.kappa >= t.kappa_min && sig.eta >= t.eta_min {
        info!(composite, "gate action: Promote");
        GateAction::Promote
    } else if composite >= t.hold_min {
        debug!(composite, "gate action: Hold");
        GateAction::Hold
    } else {
        warn!(composite, "gate action: Reject");
        GateAction::Reject
    }
}

// ---------------------------------------------------------------------------
// ResonanceGate — stateful gate with running statistics
// ---------------------------------------------------------------------------

/// Stateful Resonance Gate that maintains running statistics over all
/// evaluated claims.
///
/// This is the production entry-point: agents call `evaluate(claim, context)`
/// and receive a `(GateAction, ResonanceSignature)` pair.
#[derive(Clone, Debug)]
pub struct ResonanceGate {
    thresholds: GateThresholds,
    /// Running mean of composite scores.
    mean_composite: f32,
    /// Running count of evaluations.
    count: u64,
    /// Histogram of actions.
    promotions: u64,
    holds: u64,
    rejections: u64,
}

impl Default for ResonanceGate {
    fn default() -> Self {
        Self {
            thresholds: GateThresholds::default(),
            mean_composite: 0.0,
            count: 0,
            promotions: 0,
            holds: 0,
            rejections: 0,
        }
    }
}

impl ResonanceGate {
    /// Create a new gate with custom thresholds.
    pub fn new(thresholds: GateThresholds) -> Self {
        Self {
            thresholds,
            ..Default::default()
        }
    }

    /// Evaluate a claim against the current context.
    ///
    /// Returns the signature and the resulting gate action, updating
    /// internal running statistics.
    pub fn evaluate(&mut self, claim: &Claim, context: &Context) -> (ResonanceSignature, GateAction) {
        let sig = compute_resonance(claim, context);
        let action = gate_action(&sig, Some(&self.thresholds));

        // Update running statistics (Welford's online algorithm)
        self.count += 1;
        let delta = sig.composite_scalar() - self.mean_composite;
        self.mean_composite += delta / self.count as f32;

        match action {
            GateAction::Promote => self.promotions += 1,
            GateAction::Hold => self.holds += 1,
            GateAction::Reject => self.rejections += 1,
        }

        (sig, action)
    }

    /// Current running mean of all composite scores.
    pub fn mean_composite(&self) -> f32 {
        self.mean_composite
    }

    /// Total number of evaluations.
    pub fn total_evaluations(&self) -> u64 {
        self.count
    }

    /// Histogram of gate actions.
    pub fn action_histogram(&self) -> (u64, u64, u64) {
        (self.promotions, self.holds, self.rejections)
    }

    /// Adjust thresholds based on recent statistics (self-tuning gating).
    ///
    /// If rejection rate is too high, we lower `promote_min` slightly;
    /// if promotion rate is too high, we raise it.
    pub fn auto_tune(&mut self) {
        if self.count == 0 {
            return;
        }
        let rej_rate = self.rejections as f32 / self.count as f32;
        let prom_rate = self.promotions as f32 / self.count as f32;

        if rej_rate > 0.5 {
            self.thresholds.promote_min = (self.thresholds.promote_min * 0.95).max(0.4);
            debug!("auto-tune: lowering promote_min due to high rejection rate");
        } else if prom_rate > 0.7 {
            self.thresholds.promote_min = (self.thresholds.promote_min * 1.05).min(0.9);
            debug!("auto-tune: raising promote_min due to high promotion rate");
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn test_claim(confidence: f32, evidence: usize, observed: bool) -> Claim {
        Claim {
            id: [0u8; 32],
            proposition: "test".into(),
            confidence,
            evidence_count: evidence,
            is_observed: observed,
            source_residency: Residency::L1,
        }
    }

    fn test_context(features: Vec<f32>) -> Context {
        Context {
            active_claims: vec![[0u8; 32]],
            feature_vector: features,
            current_residency: Residency::L1,
            learning_mode: LearningMode::Sgd,
        }
    }

    #[test]
    fn ternary_state_encoding() {
        assert_eq!(TernaryState::Pos.as_i8(), 1);
        assert_eq!(TernaryState::Zero.as_i8(), 0);
        assert_eq!(TernaryState::Neg.as_i8(), -1);
    }

    #[test]
    fn compute_resonance_high_confidence() {
        let claim = test_claim(0.9, 20, true);
        let context = test_context(vec![0.8; 128]);
        let sig = compute_resonance(&claim, &context);

        assert_eq!(sig.tau, TernaryState::Pos);
        assert_eq!(sig.pi, Primality::Prime);
        assert!(sig.rho > 0.5);
        assert!(sig.eta > 0.5);
        assert!(sig.kappa > 0.0);
    }

    #[test]
    fn compute_resonance_low_confidence() {
        let claim = test_claim(0.1, 0, false);
        let context = test_context(vec![0.1; 128]);
        let sig = compute_resonance(&claim, &context);

        assert_eq!(sig.tau, TernaryState::Neg);
        assert_eq!(sig.pi, Primality::Composite);
        assert!(sig.rho < 0.6);
    }

    #[test]
    fn gate_action_thresholds() {
        let sig = ResonanceSignature {
            tau: TernaryState::Pos,
            delta: Direction::Promote,
            pi: Primality::Prime,
            rho: 0.9,
            kappa: 0.9,
            eta: 0.9,
            lambda: Residency::L3,
            learning_mode: LearningMode::Sgd,
        };
        assert_eq!(gate_action(&sig, None), GateAction::Promote);

        let sig_low = ResonanceSignature {
            tau: TernaryState::Neg,
            delta: Direction::Demote,
            pi: Primality::Composite,
            rho: 0.1,
            kappa: 0.1,
            eta: 0.0,
            lambda: Residency::L0,
            learning_mode: LearningMode::Sgd,
        };
        assert_eq!(gate_action(&sig_low, None), GateAction::Reject);
    }

    #[test]
    fn gate_action_hold() {
        let sig = ResonanceSignature {
            tau: TernaryState::Zero,
            delta: Direction::Hold,
            pi: Primality::Composite,
            rho: 0.5,
            kappa: 0.4,
            eta: 0.3,
            lambda: Residency::L1,
            learning_mode: LearningMode::Hebbian,
        };
        let t = GateThresholds {
            promote_min: 0.7,
            hold_min: 0.35,
            kappa_min: 0.6,
            eta_min: 0.3,
        };
        assert_eq!(gate_action(&sig, Some(&t)), GateAction::Hold);
    }

    #[test]
    fn composite_scalar_range() {
        let sig = ResonanceSignature {
            tau: TernaryState::Pos,
            delta: Direction::Promote,
            pi: Primality::Prime,
            rho: 1.0,
            kappa: 1.0,
            eta: 1.0,
            lambda: Residency::LSe,
            learning_mode: LearningMode::Meta,
        };
        assert!((sig.composite_scalar() - 1.0).abs() < 0.01);

        let sig_min = ResonanceSignature {
            tau: TernaryState::Neg,
            delta: Direction::Demote,
            pi: Primality::Composite,
            rho: 0.0,
            kappa: 0.0,
            eta: 0.0,
            lambda: Residency::L0,
            learning_mode: LearningMode::Sgd,
        };
        assert!(sig_min.composite_scalar() < 0.15); // 0.2 * 0.5 = 0.1 from tau_norm
    }

    #[test]
    fn resonance_gate_evaluate() {
        let mut gate = ResonanceGate::default();
        let claim = test_claim(0.9, 20, true);
        let context = test_context(vec![0.8; 128]);

        let (sig, action) = gate.evaluate(&claim, &context);
        assert_eq!(action, GateAction::Promote);
        assert!(sig.rho > 0.0);
        assert_eq!(gate.total_evaluations(), 1);
    }

    #[test]
    fn resonance_gate_histogram() {
        let mut gate = ResonanceGate::default();
        let context = test_context(vec![0.8; 128]);

        // High confidence → Promote
        gate.evaluate(&test_claim(0.9, 20, true), &context);
        // Medium confidence → Hold
        gate.evaluate(&test_claim(0.5, 5, false), &context);
        // Low confidence → Reject
        gate.evaluate(&test_claim(0.1, 0, false), &context);

        let (p, h, r) = gate.action_histogram();
        assert_eq!(p, 1);
        assert_eq!(h, 1);
        assert_eq!(r, 1);
    }

    #[test]
    fn resonance_gate_auto_tune() {
        let mut gate = ResonanceGate::default();
        let context = test_context(vec![0.1; 128]);

        // Feed many low-confidence claims to drive rejection rate up
        for _ in 0..10 {
            gate.evaluate(&test_claim(0.1, 0, false), &context);
        }
        let before = gate.thresholds.promote_min;
        gate.auto_tune();
        let after = gate.thresholds.promote_min;
        assert!(after < before);
    }

    #[test]
    fn residency_level_ordering() {
        assert!(Residency::L0.level() < Residency::L1.level());
        assert!(Residency::L1.level() < Residency::L2.level());
        assert!(Residency::L4.level() < Residency::LSe.level());
    }

    #[test]
    fn kam_stability_bonus_promotion() {
        let claim = Claim {
            id: [1u8; 32],
            proposition: "bonus".into(),
            confidence: 0.95,
            evidence_count: 50,
            is_observed: true,
            source_residency: Residency::L3,
        };
        let context = Context {
            active_claims: vec![],
            feature_vector: vec![0.95; 64],
            current_residency: Residency::L3,
            learning_mode: LearningMode::Sgd,
        };
        let sig = compute_resonance(&claim, &context);
        // High confidence + high features should yield kappa > 0.9
        assert!(sig.kappa > 0.9, "kappa = {}", sig.kappa);
        // With kappa > 0.9 and delta = Promote, we should get L_SE (level 5)
        assert_eq!(sig.lambda, Residency::LSe);
    }
}
  }
}
