import os
import itertools

def generate_swift_concurrency_and_ast_tests():
    with open("EpistemosTests/HardenedConcurrencyTests.swift", "w") as f:
        f.write("import XCTest\n")
        f.write("@testable import Epistemos\n\n")
        f.write("final class HardenedConcurrencyTests: XCTestCase {\n")
        f.write("    // Paper Translation: Race Condition & Stress Tests\n")
        f.write("    // Spawning hundreds of simultaneous Tasks to mutate the same GraphStore to ensure SwiftData/MainActor thread safety.\n")
        
        for scale in [10, 100, 1000]:
            f.write(f"    func test_Concurrent_Graph_Mutations_Scale_{scale}() async throws {{\n")
            f.write(f"        let store = GraphStore()\n")
            f.write(f"        await withTaskGroup(of: Void.self) {{ group in\n")
            f.write(f"            for i in 0..<{scale} {{\n")
            f.write(f"                group.addTask {{\n")
            f.write(f"                    await store.applyDelta(nodes: GraphFuzz.randomGraph(nodeCount: 5).0, edges: [], clearFirst: i % 10 == 0)\n")
            f.write(f"                }}\n")
            f.write(f"            }}\n")
            f.write(f"        }}\n")
            f.write(f"        // If we reach here without a data race crash, Swift concurrency barriers are intact.\n")
            f.write(f"        XCTAssertTrue(true)\n")
            f.write(f"    }}\n\n")
            
        f.write("}\n")
        
    with open("EpistemosTests/HardenedASTFuzzTests.swift", "w") as f:
        f.write("import XCTest\n")
        f.write("@testable import Epistemos\n\n")
        f.write("final class HardenedASTFuzzTests: XCTestCase {\n")
        f.write("    // Paper Translation: XSS, Markdown Parser Injection, and Fuzzing\n")
        f.write("    // Validating that the Native SwiftUI/SwiftData Markdown representations do not crash or execute code under extreme AST stress.\n")
        f.write("    let payloads = StringFuzz.sqlInjectionPatterns() + StringFuzz.controlChars() + [\n")
        f.write("        \"<script>alert(1)</script>\",\n")
        f.write("        \"[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]\",\n")
        f.write("        String(repeating: \"#\", count: 10000) + \" Header\",\n")
        f.write("        \"![exploit](javascript:alert(1))\"\n")
        f.write("    ]\n\n")
        
        f.write("    func test_Markdown_AST_Sanitization() {\n")
        f.write("        for (idx, payload) in payloads.enumerated() {\n")
        f.write("            let page = SDPage(title: payload, isJournal: false)\n")
        f.write("            // Simulate Text(page.title) AST rendering crash test\n")
        f.write("            var attemptStr: String?\n")
        f.write("            do {\n")
        f.write("                let attr = try AttributedString(markdown: page.title)\n")
        f.write("                attemptStr = String(attr.characters)\n")
        f.write("            } catch {\n")
        f.write("                // Expected to fail on garbage, but must NEVER hard crash the app\n")
        f.write("                attemptStr = \"failed cleanly\"\n")
        f.write("            }\n")
        f.write("            XCTAssertNotNil(page)\n")
        f.write("            XCTAssertNotNil(attemptStr)\n")
        f.write("        }\n")
        f.write("    }\n")
        f.write("}\n")
        
def generate_rust_ffi_deadlock_tests():
    with open("graph-engine/src/hardened_race_tests.rs", "w") as f:
        f.write("//! Paper Translation: IPC Bridge Latency and Multithreaded Race Conditions\n")
        f.write("//! Tests the Engine's Arc<Mutex> boundaries by hammering tick() and write() concurrently.\n")
        f.write("#[cfg(test)]\n")
        f.write("mod tests {\n")
        f.write("    use crate::engine::GraphEngine;\n")
        f.write("    use crate::types::Graph;\n")
        f.write("    use std::sync::{Arc, Mutex};\n")
        f.write("    use std::thread;\n\n")
        
        f.write("    #[test]\n")
        f.write("    fn test_ffi_multithread_deadlock_stress() {\n")
        f.write("        // The FFI wrapper is single-threaded from Swift Main Actor typically, but background tasks may request data.\n")
        f.write("        // We simulate highly contentious reads/writes to the Engine to ensure no Mutex deadlocks.\n")
        f.write("        let engine = Arc::new(Mutex::new(GraphEngine::new()));\n")
        f.write("        let mut handles = vec![];\n\n")
        
        f.write("        // 10 Writer threads hammering `applyDelta`\n")
        f.write("        for i in 0..10 {\n")
        f.write("            let eng = Arc::clone(&engine);\n")
        f.write("            handles.push(thread::spawn(move || {\n")
        f.write("                for j in 0..100 {\n")
        f.write("                    let mut g = Graph::new();\n")
        f.write("                    g.add_node(format!(\"n-{}-{}\", i, j), 0.0, 0.0, 0, 1, format!(\"L\"));\n")
        f.write("                    let mut lock = eng.lock().unwrap();\n")
        f.write("                    lock.engine_apply_data(&g.nodes, &g.edges, false);\n")
        f.write("                }\n")
        f.write("            }));\n")
        f.write("        }\n\n")
        
        f.write("        // 10 Reader threads hammering `tick` and `get_render_data`\n")
        f.write("        for _ in 0..10 {\n")
        f.write("            let eng = Arc::clone(&engine);\n")
        f.write("            handles.push(thread::spawn(move || {\n")
        f.write("                for _ in 0..200 {\n")
        f.write("                    let mut lock = eng.lock().unwrap();\n")
        f.write("                    lock.tick(0.016);\n")
        f.write("                }\n")
        f.write("            }));\n")
        f.write("        }\n\n")
        
        f.write("        for h in handles {\n")
        f.write("            h.join().unwrap();\n")
        f.write("        }\n")
        f.write("        \n")
        f.write("        let lock = engine.lock().unwrap();\n")
        f.write("        assert!(lock.nodes.len() > 0);\n")
        f.write("    }\n")
        f.write("}\n")

if __name__ == "__main__":
    generate_swift_concurrency_and_ast_tests()
    generate_rust_ffi_deadlock_tests()
    print("Generated Native Hardening Suites")
