// MeaningAnchorService.swift
//
// Generates and manages "meaning anchors" — structured snapshots of chat
// conversations that capture WHY a chat matters, not just WHAT was discussed.
//
// Anchors become graph nodes (.idea type with originChatId metadata),
// enabling the knowledge graph to incorporate conversational intelligence.
// Generated by local Qwen model on chat exit (meaningful threshold: 3+ exchanges).
//
// Architecture:
// - SDChat exit → MeaningAnchorService.generateAnchor()
// - Local Qwen generates structured JSON: topic, insights, connections, summary
// - Anchor persisted as GraphNodeRecord with edges to related notes
// - Embedding computed for semantic search integration

import Foundation
import SwiftData
import os.log

// MARK: - Meaning Anchor Model

struct MeaningAnchor: Codable, Sendable {
    let chatId: String
    let chatType: String
    let topic: String
    let summary: String
    let keyInsights: [String]
    let relatedNoteIds: [String]
    let broaderTheme: String
    let confidence: Double
    let generatedAt: Date

    /// Formats the anchor as context for AI prompt injection.
    func formatForPrompt() -> String {
        var parts = ["[\(topic)] \(summary)"]
        if !keyInsights.isEmpty {
            parts.append("Insights: \(keyInsights.joined(separator: "; "))")
        }
        if !broaderTheme.isEmpty {
            parts.append("Theme: \(broaderTheme)")
        }
        return parts.joined(separator: " | ")
    }
}

// MARK: - Meaning Anchor Service

@MainActor
final class MeaningAnchorService {
    private static let log = Logger(subsystem: "app.epistemos", category: "MeaningAnchor")

    private let triageService: TriageService
    private let graphState: GraphState
    private let modelContainer: ModelContainer

    init(triageService: TriageService, graphState: GraphState, modelContainer: ModelContainer) {
        self.triageService = triageService
        self.graphState = graphState
        self.modelContainer = modelContainer
    }

    // MARK: - Anchor Generation

    /// Generates a meaning anchor for a completed chat session.
    /// Only creates an anchor if the chat has meaningful content (3+ messages).
    func generateAnchor(for chatId: String) async {
        let context = modelContainer.mainContext

        // Fetch chat + messages
        let targetId = chatId
        let descriptor = FetchDescriptor<SDChat>(
            predicate: #Predicate { $0.id == targetId }
        )
        guard let chat = try? context.fetch(descriptor).first else {
            Self.log.warning("Anchor generation: chat \(chatId) not found")
            return
        }

        let messages = (chat.messages ?? []).sorted { $0.createdAt < $1.createdAt }
        guard messages.count >= 3 else { return }

        // Build conversation transcript for analysis
        var conversationLines: [String] = []
        for msg in messages {
            let role = msg.role == "user" ? "User" : "AI"
            let text = msg.content
            let end = text.index(text.startIndex, offsetBy: min(text.count, 300))
            conversationLines.append("\(role): \(text[text.startIndex..<end])")
        }
        let fullConversation = conversationLines.joined(separator: "\n")
        let endIdx = fullConversation.index(fullConversation.startIndex, offsetBy: min(fullConversation.count, 2000))
        let conversationSnippet = String(fullConversation[fullConversation.startIndex..<endIdx])
        let prompt = """
        Analyze this conversation and extract its meaning. Return a JSON object with these fields:
        - topic: one-line topic (what this conversation is about)
        - summary: 2-3 sentence summary capturing WHY this matters, not just what was discussed
        - keyInsights: array of 1-3 key insights or decisions made
        - broaderTheme: the broader project/goal this connects to
        - confidence: 0.0-1.0 how confident you are in this analysis

        Conversation:
        \(conversationSnippet)

        Return ONLY valid JSON, no markdown or explanation.
        """

        do {
            let response = try await triageService.generate(
                prompt: prompt,
                systemPrompt: "You are a conversation analyst. Extract structured meaning from conversations. Return only valid JSON.",
                operation: .summarize,
                contentLength: prompt.count,
                query: "meaning anchor generation"
            )

            guard let anchor = parseAnchorResponse(response, chatId: chatId, chatType: chat.chatType) else {
                Self.log.warning("Anchor generation: failed to parse response for chat \(chatId)")
                return
            }

            // Create graph node
            createGraphNode(for: anchor, chat: chat)

            Self.log.info("Meaning anchor created: \(anchor.topic) (confidence: \(String(format: "%.0f%%", anchor.confidence * 100)))")
        } catch {
            Self.log.error("Anchor generation failed: \(error.localizedDescription)")
        }
    }

    // MARK: - Response Parsing

    private func parseAnchorResponse(_ response: String, chatId: String, chatType: String) -> MeaningAnchor? {
        // Extract JSON from response (may have markdown wrapping)
        let cleaned = response
            .replacingOccurrences(of: "```json", with: "")
            .replacingOccurrences(of: "```", with: "")
            .trimmingCharacters(in: .whitespacesAndNewlines)

        guard let data = cleaned.data(using: .utf8) else { return nil }

        struct RawAnchor: Decodable {
            let topic: String?
            let summary: String?
            let keyInsights: [String]?
            let broaderTheme: String?
            let confidence: Double?
        }

        guard let raw = try? JSONDecoder().decode(RawAnchor.self, from: data) else { return nil }

        return MeaningAnchor(
            chatId: chatId,
            chatType: chatType,
            topic: raw.topic ?? "Untitled",
            summary: raw.summary ?? "",
            keyInsights: raw.keyInsights ?? [],
            relatedNoteIds: [],
            broaderTheme: raw.broaderTheme ?? "",
            confidence: raw.confidence ?? 0.5,
            generatedAt: .now
        )
    }

    // MARK: - Graph Integration

    private func createGraphNode(for anchor: MeaningAnchor, chat: SDChat) {
        let nodeId = UUID().uuidString

        var metadata = GraphNodeMetadata()
        metadata.originChatId = anchor.chatId
        metadata.abstract = anchor.summary
        metadata.clusterTheme = anchor.broaderTheme

        let node = GraphNodeRecord(
            id: nodeId,
            type: .idea,
            label: anchor.topic,
            sourceId: anchor.chatId,
            metadata: metadata,
            weight: max(0.5, anchor.confidence),
            createdAt: .now
        )

        // Add to graph via incremental path (avoids full rebuild)
        graphState.requestIncrementalAdd(node: node)

        // Create edges to related notes if chat was linked to a page
        if let linkedPageId = chat.linkedPageId,
           let linkedNode = graphState.store.node(bySourceId: linkedPageId, type: .note) {
            let edge = GraphEdgeRecord(
                id: UUID().uuidString,
                sourceNodeId: nodeId,
                targetNodeId: linkedNode.id,
                type: .related,
                weight: anchor.confidence,
                createdAt: .now
            )
            graphState.requestIncrementalAddEdge(edge)
        }

        // Compute embedding off main thread, push result back on MainActor
        let embeddingSvc = graphState.embeddingService
        let content = "\(anchor.topic). \(anchor.summary). \(anchor.keyInsights.joined(separator: ". "))"
        let embeddingNodeId = nodeId
        Task.detached(priority: .utility) {
            // computeBlockVectors is nonisolated — safe to call off-main
            let embeddings = embeddingSvc.computeBlockVectors(
                blocks: [(id: embeddingNodeId, content: content)]
            )
            guard !embeddings.isEmpty else { return }
            await MainActor.run {
                embeddingSvc.pushBlockEmbeddings(embeddings)
            }
        }
    }

    // MARK: - Batch Generation (Backfill)

    /// Generates anchors for all existing chats that don't have one yet.
    /// Runs in background, yielding between chats to avoid blocking.
    func backfillExistingChats() async {
        let context = modelContainer.mainContext

        guard let allChats = try? context.fetch(FetchDescriptor<SDChat>(
            sortBy: [SortDescriptor(\.createdAt, order: .reverse)]
        )) else { return }

        // Find chats that already have anchors (check graph for nodes with originChatId)
        let existingAnchorChatIds = Set(
            graphState.store.nodes.values
                .filter { $0.type == .idea && $0.metadata.originChatId != nil }
                .compactMap { $0.metadata.originChatId }
        )

        let chatsToProcess = allChats.filter { chat in
            !existingAnchorChatIds.contains(chat.id) &&
            (chat.messages?.count ?? 0) >= 3
        }

        Self.log.info("Backfill: \(chatsToProcess.count) chats to process")

        for (index, chat) in chatsToProcess.enumerated() {
            await generateAnchor(for: chat.id)

            // Yield between each chat — inference takes seconds, so this is
            // primarily to let SwiftUI animations and user interactions breathe
            try? await Task.sleep(for: .milliseconds(500))

            // Log progress every 10 chats
            if index % 10 == 9 {
                Self.log.info("Backfill progress: \(index + 1)/\(chatsToProcess.count)")
            }
        }

        Self.log.info("Backfill complete: processed \(chatsToProcess.count) chats")
    }
}
