import Foundation

// MARK: - ThoughtAttachmentBridge
//
// Wave 7.15 of the Extended Program Plan
// (`docs/audits/EXTENDED_PROGRAM_PLAN_2026_04_25.md` Wave 7.15).
//
// Bidirectional cross-reference between RawThought runs (Wave 3.1)
// and `.epdoc` documents (W7.1). Per the user's 2026-04-26
// direction:
//
//     "documents are attached to all thoughts in the pro system"
//
// The `EpdocProvenance.generatedByRun` field already records ONE
// direction (doc → run). This bridge adds the REVERSE direction
// (run → list of docs it produced) + maintains both views in a
// single store so a query in either direction is O(1) average.
//
// V1 scope (this commit):
//   - in-memory `ThoughtAttachmentBridge` actor
//   - bidirectional `attach(documentID:runID:)` edge
//   - O(1) lookups: `documents(generatedBy runID:)`,
//                   `runs(thatGenerated documentID:)`
//   - JSON sidecar at `<vault>/.epcache/thoughts-bridge.json`
//     (load + save via `loadFrom(url:)` / `saveTo(url:)`)
//   - dangling-reference detection (`prune(against:)`)
//
// V1.5 follow-ups (W7.15.b):
//   - hook the bridge into `RawThoughtsState.swift` so writing a
//     manifest auto-attaches its produced documents
//   - hook into `EpdocDocument.fileWrapper(ofType:)` so the save
//     path also writes to the bridge when `provenance.generatedByRun`
//     is populated
//   - SDPage augmentation: surface "this doc was generated by N
//     runs" in the inspector with click-through

// MARK: - Storage shape

/// On-disk format for the JSON sidecar. Forward-compat: every field
/// is optional so older readers tolerate newer writers.
nonisolated struct ThoughtAttachmentSnapshot: Codable, Sendable, Hashable {
    /// Schema discriminant. Bumped on incompatible disk-shape changes.
    let schemaVersion: Int
    /// Outgoing edges: every (documentID, runID) attachment.
    /// Sorted lexicographically by (documentID, runID) so the file is
    /// diff-friendly + reproducible across runs.
    let edges: [Edge]

    nonisolated struct Edge: Codable, Sendable, Hashable, Comparable {
        let documentID: String
        let runID: String

        static func < (lhs: Edge, rhs: Edge) -> Bool {
            (lhs.documentID, lhs.runID) < (rhs.documentID, rhs.runID)
        }

        enum CodingKeys: String, CodingKey {
            case documentID = "document_id"
            case runID = "run_id"
        }
    }

    static let currentSchemaVersion: Int = 1

    enum CodingKeys: String, CodingKey {
        case schemaVersion = "schema_version"
        case edges
    }
}

// MARK: - Bridge actor

public actor ThoughtAttachmentBridge {

    /// Forward index: documentID → set of run ids that produced it.
    private var docToRuns: [String: Set<String>] = [:]
    /// Reverse index: runID → set of document ids it produced.
    private var runToDocs: [String: Set<String>] = [:]

    public init() {}

    // MARK: - Attach / detach

    /// Record that `runID` produced `documentID`. Idempotent — calling
    /// twice with the same pair is a no-op.
    public func attach(documentID: String, runID: String) {
        docToRuns[documentID, default: []].insert(runID)
        runToDocs[runID, default: []].insert(documentID)
    }

    /// Convenience for "this run produced these N docs". One round
    /// trip per run instead of N actor hops.
    public func attach(documentIDs: [String], to runID: String) {
        for documentID in documentIDs {
            attach(documentID: documentID, runID: runID)
        }
    }

    /// Detach a single (doc, run) pair. Returns true if the pair was
    /// present + removed, false if it didn't exist.
    @discardableResult
    public func detach(documentID: String, runID: String) -> Bool {
        var hadEdge = false
        if var runs = docToRuns[documentID], runs.contains(runID) {
            runs.remove(runID)
            if runs.isEmpty {
                docToRuns.removeValue(forKey: documentID)
            } else {
                docToRuns[documentID] = runs
            }
            hadEdge = true
        }
        if var docs = runToDocs[runID], docs.contains(documentID) {
            docs.remove(documentID)
            if docs.isEmpty {
                runToDocs.removeValue(forKey: runID)
            } else {
                runToDocs[runID] = docs
            }
        }
        return hadEdge
    }

    /// Remove every edge touching `documentID` (e.g. when the doc is
    /// permanently deleted). Returns the number of edges dropped.
    @discardableResult
    public func detachAll(documentID: String) -> Int {
        guard let runs = docToRuns.removeValue(forKey: documentID) else {
            return 0
        }
        for runID in runs {
            if var docs = runToDocs[runID] {
                docs.remove(documentID)
                if docs.isEmpty {
                    runToDocs.removeValue(forKey: runID)
                } else {
                    runToDocs[runID] = docs
                }
            }
        }
        return runs.count
    }

    /// Remove every edge touching `runID`. Returns count of edges
    /// dropped.
    @discardableResult
    public func detachAll(runID: String) -> Int {
        guard let docs = runToDocs.removeValue(forKey: runID) else {
            return 0
        }
        for documentID in docs {
            if var runs = docToRuns[documentID] {
                runs.remove(runID)
                if runs.isEmpty {
                    docToRuns.removeValue(forKey: documentID)
                } else {
                    docToRuns[documentID] = runs
                }
            }
        }
        return docs.count
    }

    // MARK: - Queries

    /// Every document the run produced. Empty if the run is unknown.
    public func documents(generatedBy runID: String) -> [String] {
        Array(runToDocs[runID] ?? []).sorted()
    }

    /// Every run that produced the document. Empty if no run touched it.
    public func runs(thatGenerated documentID: String) -> [String] {
        Array(docToRuns[documentID] ?? []).sorted()
    }

    /// True iff the (doc, run) pair is in the index.
    public func contains(documentID: String, runID: String) -> Bool {
        docToRuns[documentID]?.contains(runID) ?? false
    }

    /// Total edge count. Sanity check for tests + the inspector
    /// "N attachments" badge.
    public func edgeCount() -> Int {
        // Each edge appears once per direction; sum over the forward
        // index and divide by 0 isn't right because the indices are
        // independent. Just count the forward side.
        docToRuns.values.reduce(0) { $0 + $1.count }
    }

    // MARK: - Snapshot serialization

    /// Snapshot the current state for sidecar serialization.
    func snapshot() -> ThoughtAttachmentSnapshot {
        var edges: [ThoughtAttachmentSnapshot.Edge] = []
        edges.reserveCapacity(edgeCount())
        for (documentID, runs) in docToRuns {
            for runID in runs {
                edges.append(.init(documentID: documentID, runID: runID))
            }
        }
        edges.sort()
        return ThoughtAttachmentSnapshot(
            schemaVersion: ThoughtAttachmentSnapshot.currentSchemaVersion,
            edges: edges
        )
    }

    /// Replace the in-memory state with a previously-snapshotted one.
    func restore(_ snapshot: ThoughtAttachmentSnapshot) {
        docToRuns.removeAll()
        runToDocs.removeAll()
        for edge in snapshot.edges {
            attach(documentID: edge.documentID, runID: edge.runID)
        }
    }

    /// Serialize to disk at `url`. Atomic write (temp file + rename)
    /// so a crash during save can't leave the sidecar half-written.
    public func saveTo(url: URL) throws {
        let snap = snapshot()
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let data = try encoder.encode(snap)
        try data.write(to: url, options: [.atomic])
    }

    /// Load from disk. Skips silently when the file doesn't exist
    /// (first launch). Throws if the file is present but malformed.
    public func loadFrom(url: URL) throws {
        guard FileManager.default.fileExists(atPath: url.path) else {
            return
        }
        let data = try Data(contentsOf: url)
        let snap = try JSONDecoder().decode(ThoughtAttachmentSnapshot.self, from: data)
        restore(snap)
    }

    // MARK: - Validation

    /// Drop every edge whose document id is NOT in `liveDocumentIDs`
    /// (i.e. the doc was deleted out from under the bridge). Returns
    /// the count of dangling edges removed. Symmetric prune for runs
    /// uses `prune(againstRunIDs:)`.
    @discardableResult
    public func prune(againstDocumentIDs liveIDs: Set<String>) -> Int {
        let dangling = docToRuns.keys.filter { !liveIDs.contains($0) }
        var removed = 0
        for documentID in dangling {
            removed += detachAll(documentID: documentID)
        }
        return removed
    }

    /// Drop every edge whose run id is NOT in `liveRunIDs`.
    @discardableResult
    public func prune(againstRunIDs liveIDs: Set<String>) -> Int {
        let dangling = runToDocs.keys.filter { !liveIDs.contains($0) }
        var removed = 0
        for runID in dangling {
            removed += detachAll(runID: runID)
        }
        return removed
    }
}
