//! Source:
//! - Doctrine §3 + §5 row Geometry-IR — Lean schema authority,
//!   Clifford-algebra axiom typeclass + rotor-sandwich preserves-
//!   norm certificate.
//! - Hestenes-Sobczyk Ch. 1 — geometric-product axioms.
//! - Dorst-Fontijne-Mann §10.3 — rotor sandwich properties.
//! - Companion: [`super::grammar::Multivector`] +
//!   [`super::rotor::rotate`]; sibling certificate.rs modules.

use super::grammar::Multivector;
use super::rotor::rotor_compose;

fn rotor_hash_suffix(r: &Multivector) -> String {
    const FNV_OFFSET: u64 = 0xcbf29ce484222325;
    const FNV_PRIME: u64 = 0x100000001b3;
    let mut h = FNV_OFFSET;
    for c in &r.components {
        for byte in c.to_bits().to_le_bytes() {
            h ^= byte as u64;
            h = h.wrapping_mul(FNV_PRIME);
        }
    }
    format!("{:016x}", h)
}

/// Emit a Lean 4 certificate for a [`Multivector`] interpreted as
/// a rotor. Carries three sorry-stubbed theorems:
///
/// 1. Clifford-algebra basis-vector axioms: e_i² = 1, e_i e_j +
///    e_j e_i = 0 for i ≠ j.
/// 2. Rotor sandwich preserves norm: ∥R̃ v R∥ = ∥v∥ for grade-1 v.
/// 3. Rotor composition: rotor_compose(r1, r2) v R = r1 r2 v (r1 r2)~.
pub fn lean_certificate(rotor: &Multivector) -> String {
    let suffix = rotor_hash_suffix(rotor);
    format!(
        "-- Generated by Geometry-IR certificate.rs (T5 Phase B6 iter-46)\n\
         -- Source: docs/fusion/PRIMITIVE_IR_STACK_DOCTRINE_2026_05_17.md §3 + §5 (row Geometry-IR)\n\
         -- Rotor signature: scalar = {scalar}, bivector = ({b12}, {b13}, {b23})\n\
         \n\
         theorem clifford_basis_axioms_{suffix} :\n\
         \x20   (e_1 * e_1 = 1 ∧ e_2 * e_2 = 1 ∧ e_3 * e_3 = 1) ∧\n\
         \x20   (e_1 * e_2 = -(e_2 * e_1) ∧ e_1 * e_3 = -(e_3 * e_1) ∧ e_2 * e_3 = -(e_3 * e_2)) := by\n\
         \x20 sorry  -- Hestenes-Sobczyk Ch. 1\n\
         \n\
         theorem rotor_sandwich_isometry_{suffix} :\n\
         \x20   ∀ (v : Multivector) (R : Multivector),\n\
         \x20     is_rotor R → ∥rotate v R∥ = ∥v∥ := by\n\
         \x20 sorry  -- Dorst-Fontijne-Mann §10.3 + Clifford axioms\n\
         \n\
         theorem rotor_composition_{suffix} :\n\
         \x20   ∀ (R1 R2 : Multivector) (v : Multivector),\n\
         \x20     rotate v (rotor_compose R1 R2) = rotate (rotate v R1) R2 := by\n\
         \x20 sorry  -- right-acting sandwich associativity\n\
         \n",
        suffix = suffix,
        scalar = rotor.scalar_part(),
        b12 = rotor.bivector_part().0,
        b13 = rotor.bivector_part().1,
        b23 = rotor.bivector_part().2,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cert_includes_clifford_axioms() {
        let r = Multivector::scalar(1.0);
        let c = lean_certificate(&r);
        assert!(c.contains("clifford_basis_axioms_"));
        assert!(c.contains("e_1 * e_1 = 1"));
        assert!(c.contains("e_1 * e_2 = -(e_2 * e_1)"));
    }

    #[test]
    fn cert_includes_rotor_isometry() {
        let r = Multivector::scalar(1.0);
        let c = lean_certificate(&r);
        assert!(c.contains("rotor_sandwich_isometry_"));
        assert!(c.contains("∥rotate v R∥ = ∥v∥"));
    }

    #[test]
    fn cert_includes_rotor_composition() {
        let r = Multivector::scalar(1.0);
        let c = lean_certificate(&r);
        assert!(c.contains("rotor_composition_"));
        assert!(c.contains("rotate v (rotor_compose R1 R2)"));
    }

    #[test]
    fn cert_carries_sorry_proof_bodies() {
        let r = Multivector::scalar(1.0);
        let c = lean_certificate(&r);
        assert_eq!(c.matches("sorry").count(), 3);
    }

    #[test]
    fn cert_includes_rotor_components_in_comment() {
        let r = Multivector::bivector(0.5, -0.3, 0.7);
        // Add scalar part so it looks like a rotor.
        let r = r.add(&Multivector::scalar(0.8));
        let c = lean_certificate(&r);
        assert!(c.contains("0.5"));
        assert!(c.contains("0.8"));
    }

    #[test]
    fn cert_header_cites_phase_b6_iter_46() {
        let r = Multivector::scalar(1.0);
        let c = lean_certificate(&r);
        assert!(c.contains("iter-46"));
    }

    #[test]
    fn cert_hash_differs_for_different_rotors() {
        let r1 = Multivector::scalar(1.0);
        let r2 = Multivector::bivector(1.0, 0.0, 0.0);
        assert_ne!(rotor_hash_suffix(&r1), rotor_hash_suffix(&r2));
    }

    #[test]
    fn cert_is_deterministic() {
        let r = Multivector::scalar(1.0);
        let c1 = lean_certificate(&r);
        let c2 = lean_certificate(&r);
        assert_eq!(c1, c2);
    }

    #[test]
    fn rotor_compose_function_exists() {
        // Smoke check that the path used in the cert text compiles.
        let r = Multivector::scalar(1.0);
        let _ = rotor_compose(&r, &r);
    }
}
