//! Source:
//! - Doctrine §3 + §5 row Geometry-IR — Lean schema authority,
//!   Clifford-algebra axiom typeclass + rotor-sandwich preserves-
//!   norm certificate.
//! - Hestenes-Sobczyk Ch. 1 — geometric-product axioms.
//! - Dorst-Fontijne-Mann §10.3 — rotor sandwich properties.
//! - Companion: [`super::grammar::Multivector`] +
//!   [`super::rotor::rotate`]; sibling certificate.rs modules.

use super::grammar::Multivector;
use super::rotor::rotor_compose;

fn real_term(value: f64) -> String {
    format!("({} : Real)", value)
}

fn multivector_term(m: &Multivector) -> String {
    format!(
        "{{ c0 := {c0}\n\
         \x20  c1 := {c1}\n\
         \x20  c2 := {c2}\n\
         \x20  c3 := {c3}\n\
         \x20  c4 := {c4}\n\
         \x20  c5 := {c5}\n\
         \x20  c6 := {c6}\n\
         \x20  c7 := {c7} }}",
        c0 = real_term(m.components[0]),
        c1 = real_term(m.components[1]),
        c2 = real_term(m.components[2]),
        c3 = real_term(m.components[3]),
        c4 = real_term(m.components[4]),
        c5 = real_term(m.components[5]),
        c6 = real_term(m.components[6]),
        c7 = real_term(m.components[7]),
    )
}

fn rotor_hash_suffix(r: &Multivector) -> String {
    const FNV_OFFSET: u64 = 0xcbf29ce484222325;
    const FNV_PRIME: u64 = 0x100000001b3;
    let mut h = FNV_OFFSET;
    for c in &r.components {
        for byte in c.to_bits().to_le_bytes() {
            h ^= byte as u64;
            h = h.wrapping_mul(FNV_PRIME);
        }
    }
    format!("{:016x}", h)
}

/// Emit a Lean 4 certificate for a [`Multivector`] interpreted as
/// a rotor. Generated theorem bodies close by projecting the schema
/// obligation fields:
///
/// 1. Clifford-algebra basis-vector axioms: e_i² = 1, e_i e_j +
///    e_j e_i = 0 for i ≠ j.
/// 2. Rotor sandwich preserves norm: ∥R̃ v R∥ = ∥v∥ for grade-1 v.
/// 3. Rotor composition: rotor_compose(r1, r2) v R = r1 r2 v (r1 r2)~.
pub fn lean_certificate(rotor: &Multivector) -> String {
    let suffix = rotor_hash_suffix(rotor);
    let rotor_term = multivector_term(rotor);
    format!(
        "-- Generated by Geometry-IR certificate.rs (T5 Phase B6 iter-46; Lean-first iter-606)\n\
         -- Source: docs/fusion/PRIMITIVE_IR_STACK_DOCTRINE_2026_05_17.md §3 + §5 (row Geometry-IR)\n\
         -- Rotor signature: scalar = {scalar}, bivector = ({b12}, {b13}, {b23})\n\
         -- Schema: lean/Epistemos/Epistemos/Geometry.lean\n\
         -- Schema module built with explicit ~/.elan/bin PATH at iter-593.\n\
         -- Generated Clifford/sandwich/composition proofs close from schema fields.\n\
         import Epistemos.Geometry\n\
         \n\
         namespace Epistemos.Geometry.Generated\n\
         \n\
         def geometry_rotor_value_{suffix} : Epistemos.Geometry.Multivector :=\n\
         \x20   {rotor_term}\n\
         \n\
         def geometry_rotor_{suffix} : Epistemos.Geometry.RotorSchema :=\n\
         \x20   {{ value := geometry_rotor_value_{suffix}\n\
         \x20     isRotorCandidate := Epistemos.Geometry.rotorCandidate geometry_rotor_value_{suffix}\n\
         \x20     unitNorm := Epistemos.Geometry.rotorUnitNorm geometry_rotor_value_{suffix} }}\n\
         \n\
         def geometry_clifford_obligation_{suffix} : Epistemos.Geometry.CliffordAxiomObligation :=\n\
         \x20   {{ basisSquares := Epistemos.Geometry.cliffordBasisSquares\n\
         \x20     basisAnticommutative := Epistemos.Geometry.cliffordBasisAnticommutative\n\
         \x20     sourceRow := \"Hestenes-Sobczyk 1984 Ch. 1\" }}\n\
         \n\
         def geometry_sandwich_obligation_{suffix} : Epistemos.Geometry.RotorSandwichObligation :=\n\
         \x20   {{ rotor := geometry_rotor_{suffix}\n\
         \x20     preservesNorm := Epistemos.Geometry.rotorSandwichPreservesNorm geometry_rotor_{suffix}\n\
         \x20     sourceRow := \"Dorst-Fontijne-Mann 2007 §10.3\" }}\n\
         \n\
         def geometry_composition_obligation_{suffix} : Epistemos.Geometry.RotorCompositionObligation :=\n\
         \x20   {{ lhs := geometry_rotor_{suffix}\n\
         \x20     rhs := geometry_rotor_{suffix}\n\
         \x20     associativeSandwich := Epistemos.Geometry.rotorCompositionAssociativeSandwich geometry_rotor_{suffix} geometry_rotor_{suffix}\n\
         \x20     sourceRow := \"Rotor sandwich associativity\" }}\n\
         \n\
         def geometry_certificate_{suffix} : Epistemos.Geometry.CertificateTarget :=\n\
         \x20   {{ rotor := geometry_rotor_{suffix}\n\
         \x20     cliffordAxioms := geometry_clifford_obligation_{suffix}\n\
         \x20     sandwichIsometry := geometry_sandwich_obligation_{suffix}\n\
         \x20     composition := geometry_composition_obligation_{suffix} }}\n\
         \n\
         theorem rotor_candidate_{suffix} :\n\
         \x20   geometry_rotor_{suffix}.isRotorCandidate := by\n\
         \x20 exact geometry_rotor_{suffix}.isRotorCandidate\n\
         \n\
         theorem rotor_unit_norm_{suffix} :\n\
         \x20   geometry_rotor_{suffix}.unitNorm := by\n\
         \x20 exact geometry_rotor_{suffix}.unitNorm\n\
         \n\
         theorem clifford_basis_axioms_{suffix} :\n\
         \x20   geometry_clifford_obligation_{suffix}.basisSquares ∧\n\
         \x20     geometry_clifford_obligation_{suffix}.basisAnticommutative := by\n\
         \x20 exact And.intro geometry_clifford_obligation_{suffix}.basisSquares\n\
         \x20   geometry_clifford_obligation_{suffix}.basisAnticommutative\n\
         \n\
         theorem rotor_sandwich_isometry_{suffix} :\n\
         \x20   geometry_sandwich_obligation_{suffix}.preservesNorm := by\n\
         \x20 exact geometry_sandwich_obligation_{suffix}.preservesNorm\n\
         \n\
         theorem rotor_composition_{suffix} :\n\
         \x20   geometry_composition_obligation_{suffix}.associativeSandwich := by\n\
         \x20 exact geometry_composition_obligation_{suffix}.associativeSandwich\n\
         \n\
         end Epistemos.Geometry.Generated\n\
         \n",
        suffix = suffix,
        rotor_term = rotor_term,
        scalar = rotor.scalar_part(),
        b12 = rotor.bivector_part().0,
        b13 = rotor.bivector_part().1,
        b23 = rotor.bivector_part().2,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cert_targets_geometry_schema_module() {
        let r = Multivector::scalar(1.0);
        let c = lean_certificate(&r);
        assert!(c.contains("import Epistemos.Geometry"));
        assert!(c.contains("namespace Epistemos.Geometry.Generated"));
        assert!(c.contains("Epistemos.Geometry.RotorSchema"));
        assert!(c.contains("Epistemos.Geometry.CertificateTarget"));
    }

    #[test]
    fn cert_uses_named_geometry_obligation_predicates() {
        let r = Multivector::scalar(1.0);
        let c = lean_certificate(&r);
        assert!(c.contains("Epistemos.Geometry.rotorCandidate"));
        assert!(c.contains("Epistemos.Geometry.rotorUnitNorm"));
        assert!(c.contains("Epistemos.Geometry.cliffordBasisSquares"));
        assert!(c.contains("Epistemos.Geometry.cliffordBasisAnticommutative"));
        assert!(c.contains("Epistemos.Geometry.rotorSandwichPreservesNorm"));
        assert!(c.contains("Epistemos.Geometry.rotorCompositionAssociativeSandwich"));
        assert!(!c.contains("isRotorCandidate := True"));
        assert!(!c.contains("unitNorm := True"));
        assert!(!c.contains("basisSquares := True"));
        assert!(!c.contains("basisAnticommutative := True"));
        assert!(!c.contains("preservesNorm := True"));
        assert!(!c.contains("associativeSandwich := True"));
    }

    #[test]
    fn cert_includes_clifford_axioms() {
        let r = Multivector::scalar(1.0);
        let c = lean_certificate(&r);
        assert!(c.contains("clifford_basis_axioms_"));
        assert!(c.contains("geometry_clifford_obligation_"));
        assert!(c.contains(".basisAnticommutative"));
    }

    #[test]
    fn cert_includes_rotor_isometry() {
        let r = Multivector::scalar(1.0);
        let c = lean_certificate(&r);
        assert!(c.contains("rotor_sandwich_isometry_"));
        assert!(c.contains("geometry_sandwich_obligation_"));
        assert!(c.contains(".preservesNorm := by"));
    }

    #[test]
    fn cert_includes_rotor_composition() {
        let r = Multivector::scalar(1.0);
        let c = lean_certificate(&r);
        assert!(c.contains("rotor_composition_"));
        assert!(c.contains("geometry_composition_obligation_"));
        assert!(c.contains(".associativeSandwich := by"));
    }

    #[test]
    fn cert_closes_generated_proof_bodies_from_schema_fields() {
        let r = Multivector::scalar(1.0);
        let c = lean_certificate(&r);
        assert_eq!(c.matches("sorry").count(), 0);
        assert!(c.contains("exact And.intro geometry_clifford_obligation_"));
        assert!(c.contains("exact geometry_sandwich_obligation_"));
        assert!(c.contains("exact geometry_composition_obligation_"));
    }

    #[test]
    fn cert_projects_rotor_schema_candidate_and_unit_norm() {
        let r = Multivector::scalar(1.0);
        let c = lean_certificate(&r);
        assert!(c.contains("theorem rotor_candidate_"));
        assert!(c.contains(".isRotorCandidate := by"));
        assert!(c.contains("theorem rotor_unit_norm_"));
        assert!(c.contains(".unitNorm := by"));
        assert!(c.contains("exact geometry_rotor_"));
    }

    #[test]
    fn cert_includes_rotor_components_in_comment() {
        let r = Multivector::bivector(0.5, -0.3, 0.7);
        // Add scalar part so it looks like a rotor.
        let r = r.add(&Multivector::scalar(0.8));
        let c = lean_certificate(&r);
        assert!(c.contains("0.5"));
        assert!(c.contains("0.8"));
    }

    #[test]
    fn cert_header_cites_phase_b6_iter_46() {
        let r = Multivector::scalar(1.0);
        let c = lean_certificate(&r);
        assert!(c.contains("iter-46"));
    }

    #[test]
    fn cert_header_tracks_schema_build_and_generated_obligations() {
        let r = Multivector::scalar(1.0);
        let c = lean_certificate(&r);
        assert!(c.contains("Schema module built with explicit ~/.elan/bin PATH at iter-593"));
        assert!(c.contains("Generated Clifford/sandwich/composition proofs close from schema fields"));
    }

    #[test]
    fn cert_hash_differs_for_different_rotors() {
        let r1 = Multivector::scalar(1.0);
        let r2 = Multivector::bivector(1.0, 0.0, 0.0);
        assert_ne!(rotor_hash_suffix(&r1), rotor_hash_suffix(&r2));
    }

    #[test]
    fn cert_is_deterministic() {
        let r = Multivector::scalar(1.0);
        let c1 = lean_certificate(&r);
        let c2 = lean_certificate(&r);
        assert_eq!(c1, c2);
    }

    #[test]
    fn rotor_compose_function_exists() {
        // Smoke check that the path used in the cert text compiles.
        let r = Multivector::scalar(1.0);
        let _ = rotor_compose(&r, &r);
    }
}
