import Testing

/// Owner latest correction:
/// Act uses the current Epistemos chat UI as the visible surface. Osaurus is
/// unbundled into engine, model/config, tools, permissions, dependency,
/// sandbox, and management pieces that are re-exposed through Epistemos chrome.
@Suite("Act surface = Epistemos chat with unbundled Osaurus capability")
struct ActSurfaceOsaurusUIDirectionGuardTests {

    @Test("RootView enters the current Epistemos Act chat surface with Osaurus underneath")
    func rootViewRoutesFusedEpistemosActSurface() throws {
        let app = try loadMirroredSourceTextFile("Epistemos/App/EpistemosApp.swift")
        let source = try loadMirroredSourceTextFile("Epistemos/App/RootView.swift")
        let chatView = try loadMirroredSourceTextFile("Epistemos/Views/Chat/ChatView.swift")
        let sharedAct = try loadMirroredSourceTextFile("Epistemos/LocalAgent/SharedActInference.swift")

        #expect(app.contains("static let submitActOsaurusPrompt"))
        #expect(app.contains("struct ActOsaurusPromptRequest"))
        #expect(app.contains("let fileAttachments: [FileAttachment]"))
        #expect(app.contains("let sessionId: UUID?"))
        #expect(source.contains("import OsaurusCore"))
        #expect(source.contains("ActEpistemosChatSurface("))
        #expect(source.contains("ChatView("))
        #expect(source.contains("actUsesOsaurus: true"))
        #expect(source.contains("availableOperatingModesOverride: [.agent]"))
        #expect(source.contains("composerMode: .osaurusAct"))
        #expect(source.contains("showsToolbarControls: false"))
        #expect(source.contains("forceActOsaurus: true"))
        #expect(source.contains("loadLegacyOsaurusTranscriptIfNeeded"))
        #expect(source.contains("authoredByProviderID: \"act\""))
        #expect(source.contains("resolvedModelLabel: actResolvedModelLabel(for: transcript.selectedModel)"))
        #expect(source.contains("return \"Act · \\(selectedModel)\""))
        #expect(source.contains("chat.addContextAttachment(attachment)"))
        #expect(source.contains("modelToolbarButton(title: actToolbarTitle)"))
        #expect(source.contains("ControlGroup {"))
        #expect(source.contains("historyToolbarButton"))
        #expect(source.contains("settingsToolbarButton"))
        #expect(source.contains("actMiniChatToolbarButton"))
        #expect(source.contains("actExportToolbarButton"))
        #expect(source.contains("MiniChatWindowController.shared.openChat("))
        #expect(source.contains("Button(action: openContextualSettingsWindow)"))
        #expect(source.contains("if showingActChatSurface || actLandingSurfaceVisible"))
        #expect(source.contains("NotificationCenter.default.post(name: .showActOsaurusSettings"))
        #expect(source.contains("ChatSidebarView {"))
        #expect(source.contains("initialPrompt: pendingActPrompt?.text"))
        #expect(source.contains("initialPromptId: pendingActPrompt?.id"))
        #expect(source.contains("initialContextAttachments: pendingActPrompt?.contextAttachments ?? []"))
        #expect(source.contains("initialFileAttachments: pendingActPrompt?.fileAttachments ?? []"))
        #expect(source.contains("for attachment in initialFileAttachments"))
        #expect(source.contains("chat.addAttachment(attachment)"))
        #expect(source.contains("onCurrentSessionChanged: { sessionId in"))
        #expect(source.contains("LandingView(onSubmitActPrompt:"))
        #expect(source.contains("WorkTerminalHostView(workspace: Self.workWorkspaceURL)"))
        #expect(source.contains("LocalAgentLoop.shouldRouteActThroughOsaurus()"))
        #expect(source.contains("WorkspaceModeSelection.current() == .act"))
        #expect(source.contains("actEpistemosChatSurface"))
        #expect(source.contains("#if !EPISTEMOS_APP_STORE"))
        #expect(source.contains("if showingActChatSurface { return true }"))
        #expect(source.contains("|| showingActChatSurface"))
        #expect(source.contains(".onReceive(NotificationCenter.default.publisher(for: .openActOsaurusSession))"))
        #expect(source.contains(".onReceive(NotificationCenter.default.publisher(for: .submitActOsaurusPrompt))"))
        #expect(source.contains("WorkspaceModeSelection.select(.act)"))
        #expect(chatView.contains("struct ChatView: View"))
        #expect(chatView.contains("var actUsesOsaurus: Bool = false"))
        #expect(chatView.contains("var composerMode: ChatInputComposerMode = .epistemos"))
        #expect(chatView.contains("var showsToolbarControls: Bool = true"))
        #expect(chatView.contains("ChatInputBar("))
        #expect(chatView.contains("showsOsaurusModelSection: composerMode == .osaurusAct"))
        #expect(sharedAct.contains("actStreamIfArmed("))
        #expect(sharedAct.contains("ActOsaurusStreamingHandler.make()"))
        #expect(sharedAct.contains("ActOsaurusVisibleStreamFilter.StreamState()"))

        #expect(!source.contains("EpistemosOsaurusChatHost("))
        #expect(!source.contains("onSubmitOverride: submitActPrompt"))
        #expect(!source.contains("actChat.pendingContextAttachments = initialContextAttachments"))
        #expect(!source.contains("onSelectActSession: { sessionId in"))
        #expect(!source.contains("NativeActChatView("))
        #expect(!source.contains("NativeActLandingView("))
        #expect(!source.contains("actRecentChats:"))
        #expect(!source.contains("selectedOsaurusSessionId"))
        #expect(!source.contains("actOsaurusChatHost"))
        #expect(!source.contains("epistemosOsaurusThemeTokens"))
        #expect(!source.contains("osaurusThemeTokens"))
    }

    @Test("Landing and Act share one route-aware recent-chat button")
    func landingAndActShareOneRecentChatsButton() throws {
        let landing = try loadMirroredSourceTextFile("Epistemos/Views/Landing/LandingView.swift")
        let root = try loadMirroredSourceTextFile("Epistemos/App/RootView.swift")
        let chatView = try loadMirroredSourceTextFile("Epistemos/Views/Chat/ChatView.swift")
        let slash = try loadMirroredSourceTextFile("Epistemos/Views/Chat/SlashCommandPopover.swift")

        #expect(root.contains("Label(\"History\", systemImage: \"sidebar.left\")"))
        #expect(root.contains("ChatSidebarView()"))
        #expect(root.contains("ChatSidebarView {"))
        #expect(root.contains("withAnimation(.easeOut(duration: 0.28))"))
        #expect(root.contains("actEntered = true"))
        #expect(root.contains(".frame(width: 300, height: 500)"))
        #expect(root.contains("if showingActChatSurface {"))
        #expect(root.contains("modelToolbarButton(title: actToolbarTitle)"))
        #expect(root.contains("ControlGroup {"))
        #expect(root.contains("actMiniChatToolbarButton"))
        #expect(root.contains("actExportToolbarButton"))
        #expect(chatView.contains("ToolbarItemGroup(placement: .primaryAction)"))
        #expect(chatView.contains("historyToolbarButton"))
        #expect(chatView.contains("if actUsesOsaurus {"))
        #expect(chatView.contains("actConfigurationToolbarButton"))
        #expect(chatView.contains("brainToolbarButton"))
        #expect(chatView.contains("miniChatToolbarButton"))
        #expect(chatView.contains("Label(\"Export\", systemImage: \"square.and.arrow.up\")"))
        #expect(chatView.contains("MotionTitle("))
        #expect(chatView.contains(".sharedBackgroundVisibility(.hidden)"))
        #expect(chatView.contains("showsActivityStrip && (chat.isStreaming || chat.isAgentExecuting)"))
        #expect(slash.contains("enum ActOsaurusSlashCommand"))
        #expect(slash.contains("case model"))
        #expect(slash.contains("case configure"))
        #expect(slash.contains("case tools"))
        #expect(!root.contains("ActOsaurusRecentChatsPopover"))
        #expect(!root.contains("EpistemosOsaurusSessionBridge.recentSessions"))
        #expect(!root.contains("Act chats"))
        #expect(!root.contains("actRecentChatsOwnsToolbarHistory"))
        #expect(!chatView.contains("onOpenActRecentChat"))
        #expect(landing.contains("var onSubmitActPrompt: ((String) -> Void)? = nil"))
        #expect(landing.contains("activateLandingSearch()"))
        #expect(landing.contains("activateLandingSearch(playHaptic: false)"))
        #expect(landing.contains("onSubmitActPrompt(trimmed)"))
        #expect(landing.contains(".allowsHitTesting(showingLandingStageCommand)"))
        #expect(landing.contains("private var isActSearchPage: Bool"))
        #expect(landing.contains("Ask Act... Type / for commands"))
        #expect(landing.contains("ActOsaurusSlashCommand.allCases.map(ComposerSlashCommandItem.osaurus)"))
        #expect(landing.contains("applyImmediateLandingOsaurusCommand"))
        #expect(landing.contains("NotificationCenter.default.post(name: .showActOsaurusSettings"))
        #expect(landing.contains("if isActSearchPage { return [.agent] }"))
        #expect(landing.contains("if isActSearchPage { return \"Act\" }"))
        #expect(!landing.contains("LandingActRecentChat"))
        #expect(!landing.contains("actRecentChats"))
        #expect(!landing.contains("Open recent Osaurus chat"))
    }

    @Test("Setup remains escapable for first-run users")
    func setupAssistantCanAlwaysFinish() throws {
        let app = try loadMirroredSourceTextFile("Epistemos/App/EpistemosApp.swift")
        let setup = try loadMirroredSourceTextFile("Epistemos/Views/Onboarding/SetupAssistantView.swift")
        let root = try loadMirroredSourceTextFile("Epistemos/App/RootView.swift")

        #expect(setup.contains("Button(\"Use App Now\")"))
        #expect(setup.contains("private func completeSetupNow()"))
        #expect(setup.contains("ui.needsSetup = false"))
        #expect(setup.contains("Button(vaultSync.vaultURL == nil ? \"Skip Vault\" : \"Next\")"))
        #expect(!setup.contains(".disabled(vaultSync.vaultURL == nil)"))
        #expect(app.contains("bootstrap.uiState.needsSetup = false"))
        #expect(root.contains("UserDefaults.standard.set(true, forKey: \"epistemos.setupComplete\")"))
    }

    @Test("Epistemos source owns visible Act while Osaurus source owns engine data")
    func epistemosSourceOwnsVisibleAct() throws {
        let root = try loadMirroredSourceTextFile("Epistemos/App/RootView.swift")
        let chatView = try loadMirroredSourceTextFile("Epistemos/Views/Chat/ChatView.swift")
        let inputBar = try loadMirroredSourceTextFile("Epistemos/Views/Chat/ChatInputBar.swift")
        let landing = try loadMirroredSourceTextFile("Epistemos/Views/Landing/LandingView.swift")
        let inlinePicker = try loadMirroredSourceTextFile("Epistemos/Views/Chat/InlineRuntimePickerPanel.swift")
        let actSettings = try loadMirroredSourceTextFile("Epistemos/Views/Settings/ActCloneSettingsView.swift")
        let presenter = try loadMirroredSourceTextFile("LocalPackages/osaurus/Packages/OsaurusCore/Epistemos/EpistemosOsaurusManagementPresenter.swift")
        let sessionBridge = try loadMirroredSourceTextFile("LocalPackages/osaurus/Packages/OsaurusCore/Epistemos/EpistemosOsaurusChatSessionBridge.swift")
        let actBridge = try loadMirroredSourceTextFile("Epistemos/ActOsaurus/ActOsaurusBridge.swift")
        let toolPrompt = try loadMirroredSourceTextFile("LocalPackages/osaurus/Packages/OsaurusCore/Services/ToolPermissionPromptService.swift")
        let providerPrompt = try loadMirroredSourceTextFile("LocalPackages/osaurus/Packages/OsaurusCore/Services/Provider/ProviderCredentialPromptService.swift")
        let pairingPrompt = try loadMirroredSourceTextFile("LocalPackages/osaurus/Packages/OsaurusCore/Services/PairingPromptService.swift")
        let bootstrap = try loadMirroredSourceTextFile("Epistemos/App/AppBootstrap.swift")
        let sharedAct = try loadMirroredSourceTextFile("Epistemos/LocalAgent/SharedActInference.swift")
        let pipeline = try loadMirroredSourceTextFile("Epistemos/Engine/PipelineService.swift")

        #expect(root.contains("struct ActEpistemosChatSurface"))
        #expect(root.contains("enum ActOsaurusNativePromptPresenter"))
        #expect(root.contains("ActNativeToolPermissionPromptView("))
        #expect(root.contains("ActNativeProviderCredentialPromptView("))
        #expect(root.contains("ActNativePairingPromptView("))
        #expect(root.contains("Text(\"Approve Act Tool\")"))
        #expect(root.contains("Text(\"Approve Act Pairing\")"))
        #expect(root.contains("EpistemosOsaurusManagementBridge.installNativeToolPermissionPresenter"))
        #expect(root.contains("EpistemosOsaurusManagementBridge.installNativeProviderCredentialPresenter"))
        #expect(root.contains("EpistemosOsaurusManagementBridge.installNativePairingPresenter"))
        #expect(root.contains("EpistemosOsaurusNativeToolPermissionDecision"))
        #expect(root.contains("EpistemosOsaurusNativePairingDecision"))
        #expect(root.contains("bootstrap.sovereignGate.confirm("))
        #expect(root.contains(".deviceOwnerAuthentication"))
        #expect(root.contains("ProviderCredentialResult?"))
        #expect(root.contains(".apiKey(key: apiKey.trimmingCharacters"))
        #expect(root.contains("ChatView("))
        #expect(root.contains("actUsesOsaurus: true"))
        #expect(root.contains("composerMode: .osaurusAct"))
        #expect(root.contains("showsToolbarControls: false"))
        #expect(root.contains("MainChatSubmissionRouter.submit("))
        #expect(root.contains("forceActOsaurus: true"))
        #expect(root.contains("loadLegacyOsaurusTranscriptIfNeeded"))
        #expect(root.contains("EpistemosOsaurusSessionBridge.loadTranscript(id: sessionId)"))
        #expect(root.contains("ActOsaurusVisibleStreamFilter.visibleStoredText"))
        #expect(root.contains("chat.addContextAttachment(attachment)"))
        #expect(root.contains("chat.addAttachment(attachment)"))
        #expect(root.contains("selectedActSessionId = request.sessionId"))
        #expect(root.contains("initialFileAttachments: pendingActPrompt?.fileAttachments ?? []"))
        #expect(!root.contains("EpistemosOsaurusChatHost("))
        #expect(!root.contains(".environment(actChat)"))
        #expect(!root.contains("ChatBrainSnapshot("))
        #expect(!root.contains("CapturedModelInput("))
        #expect(!root.contains("private var currentActModelID: String?"))
        #expect(chatView.contains("MessageBubble("))
        #expect(chatView.contains("ChatInputBar("))
        #expect(chatView.contains("ChatBrainPanelView("))
        #expect(chatView.contains("if showBrainPanel, !actUsesOsaurus"))
        #expect(chatView.contains("ActComputerUseApprovalOverlay()"))
        #expect(chatView.contains("ComputerUsePromptQueue.shared"))
        #expect(chatView.contains("queue.resolve(id: request.id, approved: outcome == .allowed)"))
        #expect(chatView.contains("sovereignGate.confirm("))
        #expect(chatView.contains("SovereignGateCategory(rawValue: \"osaurus-computer-use-\\(preview.effect.rawValue)"))
        #expect(chatView.contains("@State private var pendingActPrivacyReview: ActNativePrivacyReviewSheetState?"))
        #expect(chatView.contains("EpistemosOsaurusManagementBridge.registerNativePrivacyReviewPresenter"))
        #expect(chatView.contains("EpistemosOsaurusManagementBridge.unregisterNativePrivacyReviewPresenter"))
        #expect(chatView.contains("ActNativePrivacyReviewSheet(state: state, theme: theme)"))
        #expect(chatView.contains("private final class ActNativePrivacyReviewSheetState"))
        #expect(chatView.contains("private struct ActNativePrivacyReviewSheet: View"))
        #expect(chatView.contains("Choose what Act should replace before this request leaves the local privacy filter."))
        #expect(chatView.contains("Always approve in this conversation"))
        #expect(chatView.contains("@State private var pendingActSecretPrompt: ActNativeSecretPromptSheetState?"))
        #expect(chatView.contains("@State private var pendingActClarifyPrompt: ActNativeClarifyPromptSheetState?"))
        #expect(chatView.contains("EpistemosOsaurusChatSessionBridge.installNativeSecretPromptPresenter"))
        #expect(chatView.contains("EpistemosOsaurusChatSessionBridge.installNativeClarifyPromptPresenter"))
        #expect(chatView.contains("private final class ActNativeSecretPromptSheetState"))
        #expect(chatView.contains("private struct ActNativeSecretPromptSheet: View"))
        #expect(chatView.contains("private final class ActNativeClarifyPromptSheetState"))
        #expect(chatView.contains("private struct ActNativeClarifyPromptSheet: View"))
        #expect(chatView.contains("SecureField(\"Paste secret\""))
        #expect(chatView.contains("Answer this follow-up to continue the same Act run."))
        #expect(sessionBridge.contains("public enum EpistemosOsaurusChatSessionBridge"))
        #expect(sessionBridge.contains("public enum EpistemosOsaurusChatSessionEvent"))
        #expect(sessionBridge.contains("case thinkingDelta(String)"))
        #expect(sessionBridge.contains("case toolStarted(id: String, name: String, inputJson: String)"))
        #expect(sessionBridge.contains("case toolCompleted(id: String, result: String, isError: Bool)"))
        #expect(sessionBridge.contains("streamTurnEvents("))
        #expect(sessionBridge.contains("ChatSession()"))
        #expect(sessionBridge.contains("session.suppressesPersistence = true"))
        #expect(sessionBridge.contains("session.send(prompt)"))
        #expect(sessionBridge.contains("session.promptQueue.current"))
        #expect(sessionBridge.contains("emitAssistantThinkingDelta()"))
        #expect(sessionBridge.contains("emitAssistantToolEvents()"))
        #expect(sessionBridge.contains("EpistemosOsaurusNativeSecretPromptRequest"))
        #expect(sessionBridge.contains("EpistemosOsaurusNativeClarifyPromptRequest"))
        #expect(sessionBridge.contains("installNativeSecretPromptPresenter"))
        #expect(sessionBridge.contains("installNativeClarifyPromptPresenter"))
        #expect(sessionBridge.contains("state.submit(value)"))
        #expect(sessionBridge.contains("state.submit(answer)"))
        #expect(actBridge.contains("enum ActOsaurusStreamEvent"))
        #expect(actBridge.contains("runTurnEventStreamInProcess("))
        #expect(actBridge.contains("EpistemosOsaurusChatSessionBridge.streamTurnEvents("))
        #expect(actBridge.contains("Osaurus tool execution"))
        #expect(!actBridge.contains("CoreModelService.shared.generateStream("))
        #expect(sharedAct.contains("actEventStreamIfArmed("))
        #expect(sharedAct.contains("ActOsaurusStreamingHandler.makeEventStream()"))
        #expect(pipeline.contains("SharedActInference.actEventStreamIfArmed("))
        #expect(pipeline.contains("case .thinkingDelta(let text):"))
        #expect(pipeline.contains("case .toolStarted(let id, let name, let inputJson):"))
        #expect(pipeline.contains("case .toolCompleted(let id, let result, let isError):"))
        #expect(pipeline.contains("toolEventHandler?(.started(id: id, name: name, inputJson: inputJson))"))
        #expect(inputBar.contains("ActOsaurusSlashCommand.allCases"))
        #expect(inputBar.contains("onOpenActConfiguration"))
        #expect(inputBar.contains("showsOsaurusModelSection: composerMode == .osaurusAct"))
        #expect(landing.contains("showsOsaurusModelSection: isActSearchPage"))
        #expect(inlinePicker.contains("var showsOsaurusModelSection: Bool = false"))
        #expect(inlinePicker.contains("EpistemosOsaurusManagementBridge.modelPicks()"))
        #expect(inlinePicker.contains("EpistemosOsaurusManagementBridge.setCurrentModel(row.id)"))
        #expect(inlinePicker.contains("Text(\"ACT MODEL STACK\")"))
        #expect(actSettings.contains("Text(\"Osaurus model stack\")"))
        #expect(actSettings.contains("Text(\"Act runtime controls\")"))
        #expect(actSettings.contains("Text(\"Act capabilities\")"))
        #expect(actSettings.contains("Text(\"Providers and MCP\")"))
        #expect(actSettings.contains("Label(\"Osaurus Router\", systemImage: \"sparkles\")"))
        #expect(actSettings.contains("Label(\"Connect Providers\", systemImage: \"bolt.horizontal.circle\")"))
        #expect(actSettings.contains("Label(\"Disconnect Providers\", systemImage: \"bolt.slash.circle\")"))
        #expect(actSettings.contains("Label(\"Connect MCP\", systemImage: \"link.circle\")"))
        #expect(actSettings.contains("Label(\"Disconnect MCP\", systemImage: \"link.circle.fill\")"))
        #expect(actSettings.contains("Text(\"Sandbox and VM controls\")"))
        #expect(actSettings.contains("Label(\"Set Up Sandbox\", systemImage: \"shippingbox\")"))
        #expect(actSettings.contains("Label(\"Start\", systemImage: \"play.fill\")"))
        #expect(actSettings.contains("Label(\"Stop\", systemImage: \"stop.fill\")"))
        #expect(actSettings.contains("Label(\"Run Diagnostics\", systemImage: \"stethoscope\")"))
        #expect(actSettings.contains("ActSandboxDiagnosticNativeRow("))
        #expect(actSettings.contains("Text(\"Native permission rows\")"))
        #expect(actSettings.contains("Text(\"Tool approval policy\")"))
        #expect(actSettings.contains("Text(\"Computer Use prompts\")"))
        #expect(actSettings.contains("Text(\"Privacy filter\")"))
        #expect(actSettings.contains("Label(\"Privacy Filter\", systemImage: \"hand.raised.fill\")"))
        #expect(actSettings.contains("Label(\"Require Review for Background Sends\", systemImage: \"exclamationmark.shield.fill\")"))
        #expect(actSettings.contains("Text(\"Dependencies\")"))
        #expect(actSettings.contains("Label(\"Install / Repair Dependencies\", systemImage: \"wrench.adjustable.fill\")"))
        #expect(actSettings.contains("Text(\"Native permission surfaces\")"))
        #expect(actSettings.contains("Text(\"Complete Osaurus settings map\")"))
        #expect(actSettings.contains("actSettingsSnapshot = await EpistemosOsaurusManagementBridge.actSettingsSnapshot()"))
        #expect(actSettings.contains("osaurusQuickActions = EpistemosOsaurusManagementBridge.nativeSettingsQuickActions()"))
        #expect(actSettings.contains("systemPermissionRows = EpistemosOsaurusManagementBridge.systemPermissionRows()"))
        #expect(actSettings.contains("toolPermissionRows = EpistemosOsaurusManagementBridge.toolPermissionRows(maxCount: 60)"))
        #expect(actSettings.contains("computerUsePolicySnapshot = policySnapshot"))
        #expect(actSettings.contains("providerRuntimeSnapshot = EpistemosOsaurusManagementBridge.providerRuntimeSnapshot()"))
        #expect(actSettings.contains("privacyFilterSnapshot = EpistemosOsaurusManagementBridge.privacyFilterSnapshot()"))
        #expect(actSettings.contains("dependencySnapshot = EpistemosOsaurusManagementBridge.dependencySnapshot()"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.selectGlobalWorkingFolder()"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.clearGlobalWorkingFolder()"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.provisionSandbox()"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.startSandbox()"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.stopSandbox()"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.runSandboxDiagnostics()"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.connectRemoteProviders()"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.disconnectRemoteProviders()"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.connectMCPProviders()"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.disconnectMCPProviders()"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.repairSandboxPluginDependencies()"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.setPrivacyFilterEnabled(enabled)"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.setDefaultAgentToolsEnabled(enabled)"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.setMemoryEnabled(enabled)"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.setToolSelectionMode(rawValue)"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.requestSystemPermission(id)"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.openSystemPermissionSettings(id)"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.setToolPermissionPolicy(toolName: toolName, policyID: policyID)"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.setComputerUseGlobalPreset(rawValue)"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.setComputerUseAllowlistedApps(apps)"))
        #expect(actSettings.contains("ActSystemPermissionNativeRow("))
        #expect(actSettings.contains("ActToolPermissionNativeRow("))
        #expect(actSettings.contains("Permission Popups"))
        #expect(actSettings.contains("Computer Use Prompts"))
        #expect(actSettings.contains("Identity and Biometrics"))
        #expect(actSettings.contains("Sandbox and Host Files"))
        #expect(actSettings.contains("EpistemosOsaurusManagementBridge.managementEntries()"))
        #expect(actSettings.contains("@State private var presentedNativeSurface: ActNativeOsaurusSurface?"))
        #expect(actSettings.contains(".sheet(item: $presentedNativeSurface)"))
        #expect(actSettings.contains("ActNativeOsaurusSurfaceSheet("))
        #expect(actSettings.contains("private struct ActNativeOsaurusSurfaceSheet: View"))
        #expect(actSettings.contains("private enum ActNativeOsaurusSurfaceAction"))
        #expect(actSettings.contains("private func presentNativeSurface("))
        #expect(actSettings.contains("private func handleNativeSurfaceAction"))
        #expect(actSettings.contains("Section(\"Native State\")"))
        #expect(actSettings.contains("Section(\"Native Act Capability Surfaces\")"))
        #expect(!actSettings.contains("EpistemosOsaurusManagementBridge.showManagement(tabID:"))
        #expect(actSettings.contains("Every Act capability surface is indexed here in Epistemos chrome"))
        #expect(actSettings.contains("UI theme"))
        #expect(actSettings.contains("identity"))
        #expect(actSettings.contains("permissions"))
        #expect(actSettings.contains("privacy"))
        #expect(presenter.contains("public struct EpistemosOsaurusModelPick"))
        #expect(presenter.contains("public struct EpistemosOsaurusManagementEntry"))
        #expect(presenter.contains("public struct EpistemosOsaurusActSettingsSnapshot"))
        #expect(presenter.contains("public struct EpistemosOsaurusQuickAction"))
        #expect(presenter.contains("public struct EpistemosOsaurusSystemPermissionRow"))
        #expect(presenter.contains("public struct EpistemosOsaurusToolPermissionRow"))
        #expect(presenter.contains("public struct EpistemosOsaurusComputerUsePolicySnapshot"))
        #expect(presenter.contains("public struct EpistemosOsaurusSandboxDiagnosticRow"))
        #expect(presenter.contains("public struct EpistemosOsaurusProviderRuntimeSnapshot"))
        #expect(presenter.contains("public struct EpistemosOsaurusPrivacyFilterSnapshot"))
        #expect(presenter.contains("public struct EpistemosOsaurusDependencySnapshot"))
        #expect(presenter.contains("public struct EpistemosOsaurusNativeToolPermissionRequest"))
        #expect(presenter.contains("public enum EpistemosOsaurusNativeToolPermissionDecision"))
        #expect(presenter.contains("public typealias EpistemosOsaurusNativeProviderCredentialPresenter"))
        #expect(presenter.contains("public struct EpistemosOsaurusNativePairingRequest"))
        #expect(presenter.contains("public enum EpistemosOsaurusNativePairingDecision"))
        #expect(presenter.contains("public typealias EpistemosOsaurusNativePairingPresenter"))
        #expect(presenter.contains("public struct EpistemosOsaurusNativePrivacyReviewEntity"))
        #expect(presenter.contains("public struct EpistemosOsaurusNativePrivacyReviewRequest"))
        #expect(presenter.contains("public enum EpistemosOsaurusNativePrivacyReviewDecision"))
        #expect(presenter.contains("public struct EpistemosOsaurusNativePrivacyReviewPresenterToken"))
        #expect(presenter.contains("public typealias EpistemosOsaurusNativePrivacyReviewPresenter"))
        #expect(presenter.contains("static var privacyReviewTokens: [UUID: PresenterToken]"))
        #expect(presenter.contains("EpistemosOsaurusNativePromptPresenterStore"))
        #expect(presenter.contains("public static func actSettingsSnapshot() async"))
        #expect(presenter.contains("public static func nativeSettingsQuickActions()"))
        #expect(presenter.contains("public static func selectGlobalWorkingFolder() async"))
        #expect(presenter.contains("public static func clearGlobalWorkingFolder()"))
        #expect(presenter.contains("public static func provisionSandbox() async"))
        #expect(presenter.contains("public static func startSandbox() async"))
        #expect(presenter.contains("public static func stopSandbox() async"))
        #expect(presenter.contains("public static func runSandboxDiagnostics() async"))
        #expect(presenter.contains("public static func setDefaultAgentToolsEnabled"))
        #expect(presenter.contains("public static func setMemoryEnabled"))
        #expect(presenter.contains("public static func setToolSelectionMode"))
        #expect(presenter.contains("public static func systemPermissionRows()"))
        #expect(presenter.contains("public static func requestSystemPermission"))
        #expect(presenter.contains("public static func toolPermissionRows(maxCount: Int = 18)"))
        #expect(presenter.contains("public static func setToolPermissionPolicy"))
        #expect(presenter.contains("public static func computerUsePolicySnapshot()"))
        #expect(presenter.contains("public static func setComputerUseGlobalPreset"))
        #expect(presenter.contains("public static func setComputerUseAllowlistedApps"))
        #expect(presenter.contains("public static func providerRuntimeSnapshot()"))
        #expect(presenter.contains("RemoteProviderManager.shared.connectEnabledProviders()"))
        #expect(presenter.contains("MCPProviderManager.shared.connectEnabledProviders()"))
        #expect(presenter.contains("public static func privacyFilterSnapshot()"))
        #expect(presenter.contains("PrivacyFilterStore.snapshot()"))
        #expect(presenter.contains("PrivacyFilterStore.save(configuration)"))
        #expect(presenter.contains("public static func dependencySnapshot()"))
        #expect(presenter.contains("SandboxPluginManager.shared.verifyAndRepairAllPlugins()"))
        #expect(presenter.contains("public static func installNativeToolPermissionPresenter"))
        #expect(presenter.contains("public static func installNativeProviderCredentialPresenter"))
        #expect(presenter.contains("public static func installNativePairingPresenter"))
        #expect(presenter.contains("public static func registerNativePrivacyReviewPresenter"))
        #expect(presenter.contains("PrivacyReviewService.shared.registerPresenter"))
        #expect(presenter.contains("public static func unregisterNativePrivacyReviewPresenter"))
        #expect(presenter.contains("PrivacyReviewService.shared.unregisterPresenter(serviceToken)"))
        #expect(presenter.contains("state.setApproval(entity, to: approved)"))
        #expect(presenter.contains("state.confirm()"))
        #expect(presenter.contains("public static func modelPicks() async"))
        #expect(presenter.contains("public static func setCurrentModel"))
        #expect(!actSettings.contains("ManagementView("))
        #expect(toolPrompt.contains("EpistemosOsaurusNativePromptPresenterStore.toolPermissionPresenter"))
        #expect(toolPrompt.contains("EpistemosOsaurusNativeToolPermissionRequest("))
        #expect(toolPrompt.contains("case .alwaysAllow:"))
        #expect(toolPrompt.contains("ToolRegistry.shared.setPolicy(.auto, for: toolName)"))
        #expect(providerPrompt.contains("EpistemosOsaurusNativePromptPresenterStore.providerCredentialPresenter"))
        #expect(providerPrompt.contains("let nativeResult = await nativePresenter(request)"))
        #expect(pairingPrompt.contains("nativeApprovalInFlight"))
        #expect(pairingPrompt.contains("EpistemosOsaurusNativePromptPresenterStore.pairingPresenter"))
        #expect(pairingPrompt.contains("EpistemosOsaurusNativePairingRequest("))
        #expect(pairingPrompt.contains("case .approveTemporary:"))
        #expect(pairingPrompt.contains("case .approvePermanent:"))
        #expect(bootstrap.contains("ActOsaurusNativePromptPresenter.install()"))
    }

    @Test("Act and Mini Chat expose native tools for edit-capable Osaurus turns")
    func actAndMiniChatExposeNativeToolRuntime() throws {
        let root = try loadMirroredSourceTextFile("Epistemos/App/RootView.swift")
        let inputBar = try loadMirroredSourceTextFile("Epistemos/Views/Chat/ChatInputBar.swift")
        let miniChat = try loadMirroredSourceTextFile("Epistemos/Views/MiniChat/MiniChatView.swift")
        let miniController = try loadMirroredSourceTextFile("Epistemos/Views/MiniChat/MiniChatWindowController.swift")
        let graphChat = try loadMirroredSourceTextFile("Epistemos/Views/Graph/HologramSearchSidebar.swift")
        let graphWorkspace = try loadMirroredSourceTextFile("Epistemos/Views/Graph/GraphWorkspaceContainer.swift")
        let noteChat = try loadMirroredSourceTextFile("Epistemos/Views/Notes/NoteDetailWorkspaceView.swift")
        let notesSidebar = try loadMirroredSourceTextFile("Epistemos/Views/Notes/NotesSidebar.swift")
        let landing = try loadMirroredSourceTextFile("Epistemos/Views/Landing/LandingView.swift")
        let statusBar = try loadMirroredSourceTextFile("Epistemos/App/StatusBar.swift")
        let app = try loadMirroredSourceTextFile("Epistemos/App/EpistemosApp.swift")
        let htmlWorkspace = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceEditorView.swift")
        let chatState = try loadMirroredSourceTextFile("Epistemos/State/ChatState.swift")
        let commandCenter = try loadMirroredSourceTextFile("Epistemos/State/AgentCommandCenterState.swift")
        let appBootstrap = try loadMirroredSourceTextFile("Epistemos/App/AppBootstrap.swift")

        #expect(commandCenter.contains("func refreshExecutionCatalogsIfNeeded("))
        #expect(commandCenter.contains("refreshToolCatalog(from: mcpBridge"))
        #expect(inputBar.contains("@Environment(MCPBridge.self) private var mcpBridge"))
        #expect(inputBar.contains("private var showsToolPanelButton: Bool"))
        #expect(inputBar.contains("composerMode == .osaurusAct"))
        #expect(inputBar.contains("refreshExecutionCatalogsIfNeeded()"))
        #expect(inputBar.contains("compiledAllowedToolNames: composerMode == .osaurusAct"))
        #expect(inputBar.contains("? Array(enabledAppToolNames).sorted()"))
        #expect(inputBar.contains("return \"\\(enabledAppToolNames.count) app tools\""))
        #expect(miniChat.contains("@Environment(MCPBridge.self) private var mcpBridge"))
        #expect(miniChat.contains("private var showsToolPanelButton: Bool"))
        #expect(miniChat.contains("private var hasEnabledAppTools: Bool"))
        #expect(miniChat.contains("refreshExecutionCatalogsIfNeeded()"))
        #expect(miniChat.contains("compiledAllowedToolNames: Array(enabledAppToolNames).sorted()"))
        #expect(miniChat.contains("return \"\\(enabledAppToolNames.count) app tools\""))
        #expect(miniChat.contains("ActOsaurusSlashCommand.allCases.map(ComposerSlashCommandItem.osaurus)"))
        #expect(miniChat.contains("private func applyImmediateOsaurusCommand"))
        #expect(miniChat.contains("showsOsaurusModelSection: isOsaurusActMode"))
        #expect(miniChat.contains("NotificationCenter.default.post(name: .showActOsaurusSettings"))
        #expect(miniChat.contains("NotificationCenter.default.post(name: .openActOsaurusSession"))
        #expect(miniChat.contains("if persistedMiniChatExists(chatID)"))
        #expect(miniChat.contains("private func persistedMiniChatExists(_ chatID: String) -> Bool"))
        #expect(miniChat.contains("AppBootstrap.shared?.loadChat(chatId: chatID)"))
        #expect(miniChat.contains("authoredByProviderID: \"act\""))
        #expect(miniChat.contains("authoredByModelID: transcript.selectedModel"))
        #expect(miniChat.contains("runActPromptInMiniChat(trimmed, fileAttachments: fileAttachments)"))
        #expect(miniChat.contains("private func runActPromptInMiniChat(_ prompt: String, fileAttachments: [FileAttachment])"))
        #expect(miniChat.contains("SharedActInference.actEventStreamIfArmed("))
        #expect(miniChat.contains("threadState.setMiniChatPendingContentBlocks(pendingBlocks, chatID: chatID)"))
        #expect(miniChat.contains("threadState.setMiniChatActiveTool(name: name, inputJson: inputJson, chatID: chatID)"))
        #expect(miniChat.contains("authoredByProviderID: \"act\""))
        #expect(miniChat.contains("authoredByModelID: requestedModelID"))
        #expect(miniChat.contains("private func submitActPromptInMainChat"))
        #expect(miniChat.contains("ActOsaurusPromptRequest("))
        #expect(miniChat.contains("fileAttachments: fileAttachments"))
        #expect(miniChat.contains("sessionId: UUID(uuidString: chatID)"))
        #expect(miniChat.contains("NotificationCenter.default.post(name: .submitActOsaurusPrompt"))
        #expect(miniChat.contains("if isOsaurusActMode {"))
        #expect(miniChat.contains("clearComposerAfterSubmit()"))
        #expect(!miniChat.contains("if isOsaurusActMode {\n            submitActPromptInMainChat(trimmed"))
        #expect(miniChat.contains("EpistemosOsaurusSessionBridge.loadTranscript(id: sessionId)"))
        #expect(miniChat.contains("private var miniChatLegacyBody: some View"))
        #expect(miniChat.contains("MiniChatThread(chatID: chatID)"))
        #expect(miniChat.contains("MiniChatInputBar(chatID: chatID)"))
        #expect(!miniChat.contains("ActEpistemosChatSurface("))
        #expect(!miniChat.contains("actOsaurusSurfaceSessionId"))
        #expect(miniChat.contains("MiniChatWindowController.shared.openNewChat(preferredOperatingMode: .agent)"))
        #expect(miniChat.contains("private let composerMetrics = AssistantComposerMetrics.mainChat"))
        #expect(miniChat.contains("ChatCoordinator.queryContainsExplicitNoteWriteOperation(trimmed)"))
        #expect(miniChat.contains("ChatCoordinator.queryContainsExplicitFileOperation(trimmed)"))
        #expect(graphChat.contains("if LocalAgentLoop.shouldRouteActThroughOsaurus(), !modes.contains(.agent)"))
        #expect(graphChat.contains("private var isGraphOsaurusActMode: Bool"))
        #expect(graphChat.contains("private var graphSlashItems: [ComposerSlashCommandItem]"))
        #expect(graphChat.contains("ComposerSlashCommandItem.surfaceItems("))
        #expect(graphChat.contains("ChatComposerTextEditor("))
        #expect(graphChat.contains(".assistantComposerChrome("))
        #expect(graphChat.contains("ComposerControlStrip(spacing: 8, resetKey: graphComposerControlResetKey)"))
        #expect(graphChat.contains("AssistantSendButton("))
        #expect(graphChat.contains("graphSlashCommandTrigger"))
        #expect(graphChat.contains("SlashCommandPopover("))
        #expect(graphChat.contains("private func applyImmediateGraphOsaurusCommand"))
        #expect(graphChat.contains("NotificationCenter.default.post(name: .showActOsaurusSettings"))
        #expect(graphChat.contains("name: .submitActOsaurusPrompt"))
        #expect(graphChat.contains("ActOsaurusPromptRequest("))
        #expect(graphChat.contains("showsOsaurusModelSection: isGraphOsaurusActMode"))
        #expect(graphChat.contains("if isGraphOsaurusActMode || prediction.predicted == .agent || prediction.predicted == .research"))
        #expect(appBootstrap.contains("func routeGraphChatRequestIntoMainChat(_ request: GraphChatRequest)"))
        #expect(appBootstrap.contains("if LocalAgentLoop.shouldRouteActThroughOsaurus()"))
        #expect(appBootstrap.contains("NotificationCenter.default.post("))
        #expect(appBootstrap.contains("name: .submitActOsaurusPrompt"))
        #expect(appBootstrap.contains("ComposerReferenceHelpers.noteAttachment("))
        #expect(graphWorkspace.contains("MiniChatWindowController.shared.openNewChat("))
        #expect(graphWorkspace.contains("preferredOperatingMode: .agent"))
        #expect(noteChat.contains("if LocalAgentLoop.shouldRouteActThroughOsaurus(), !modes.contains(.agent)"))
        #expect(noteChat.contains("private var isNoteOsaurusActMode: Bool"))
        #expect(noteChat.contains("private var noteSlashItems: [ComposerSlashCommandItem]"))
        #expect(noteChat.contains("ChatComposerTextEditor("))
        #expect(noteChat.contains(".assistantComposerChrome("))
        #expect(noteChat.contains("ComposerControlStrip(spacing: 8, resetKey: noteComposerControlResetKey)"))
        #expect(noteChat.contains("AssistantSendButton("))
        #expect(noteChat.contains("noteSlashCommandTrigger"))
        #expect(noteChat.contains("SlashCommandPopover("))
        #expect(noteChat.contains("private func applyImmediateNoteOsaurusCommand"))
        #expect(noteChat.contains("NotificationCenter.default.post(name: .showActOsaurusSettings"))
        #expect(noteChat.contains("Ask Act about this note"))
        #expect(noteChat.contains("showsOsaurusModelSection: isNoteOsaurusActMode"))
        #expect(noteChat.contains("routeToolbarAskToMainChat(forceAct: true)"))
        #expect(noteChat.contains("let shouldUseAct = (forceAct || isNoteOsaurusActMode) && LocalAgentLoop.shouldRouteActThroughOsaurus()"))
        #expect(noteChat.contains("name: .submitActOsaurusPrompt"))
        #expect(noteChat.contains("ActOsaurusPromptRequest("))
        #expect(noteChat.contains("forceActOsaurus: routedMode == .agent"))
        #expect(noteChat.contains("preferredOperatingMode: .agent"))
        #expect(notesSidebar.contains("MiniChatWindowController.shared.openNewChat(preferredOperatingMode: .agent)"))
        #expect(landing.contains("MiniChatWindowController.shared.openNewChat(preferredOperatingMode: .agent)"))
        #expect(statusBar.contains("MiniChatWindowController.shared.openNewChat(preferredOperatingMode: .agent)"))
        #expect(app.contains("MiniChatWindowController.shared.openNewChat(preferredOperatingMode: .agent)"))
        #expect(htmlWorkspace.contains("preferredOperatingMode: .agent"))
        #expect(chatState.contains("attachments: [FileAttachment] = []"))
        #expect(chatState.contains("attachments: attachments"))
        #expect(root.contains("ChatView("))
        #expect(root.contains("actUsesOsaurus: true"))
        #expect(root.contains("composerMode: .osaurusAct"))
        #expect(root.contains("showsToolbarControls: false"))
        #expect(root.contains("loadLegacyOsaurusTranscriptIfNeeded"))
        #expect(!root.contains("EpistemosOsaurusChatHost("))
        #expect(root.contains("MiniChatWindowController.shared.openChat("))
        #expect(!root.contains("CapabilityManifestBuilder.render("))
        #expect(!root.contains("private var actEnabledNativeToolNames: [String]"))
        #expect(!root.contains("private var actToolDefinitionsJSON: String?"))
        #expect(!root.contains("runSharedActCoordinatorTurn(prompt: prompt"))
        #expect(miniController.contains("private static func defaultPreferredOperatingMode() -> EpistemosOperatingMode?"))
        #expect(miniController.contains("LocalAgentLoop.shouldRouteActThroughOsaurus() ? .agent : nil"))
        #expect(miniController.contains("preferredOperatingMode ?? Self.defaultPreferredOperatingMode()"))
        #expect(miniController.contains("func rebindChatWindow(from oldChatID: String, to newChatID: String)"))
        #expect(miniController.contains("windows[newChatID] = window"))
        #expect(miniController.contains("handleWindowClose(window, chatID: newChatID)"))
        #expect(!miniChat.contains("MiniChatWindowController.shared.openNewChat()"))
        #expect(!miniController.contains("MiniChatWindowController.shared.openNewChat()"))
        #expect(!statusBar.contains("MiniChatWindowController.shared.openNewChat()"))
        #expect(!app.contains("MiniChatWindowController.shared.openNewChat()"))
    }

    @Test("Osaurus engine and owner model bridge remain available under Epistemos chrome")
    func osaurusEngineKeepsOwnerModels() throws {
        let chatEngine = try loadMirroredSourceTextFile("LocalPackages/osaurus/Packages/OsaurusCore/Services/Chat/ChatEngine.swift")
        let coreModel = try loadMirroredSourceTextFile("LocalPackages/osaurus/Packages/OsaurusCore/Services/Inference/CoreModelService.swift")
        let bridge = try loadMirroredSourceTextFile("LocalPackages/osaurus/Packages/OsaurusCore/Epistemos/EpistemosModelBridge.swift")
        let presenter = try loadMirroredSourceTextFile("LocalPackages/osaurus/Packages/OsaurusCore/Epistemos/EpistemosOsaurusManagementPresenter.swift")
        let provider = try loadMirroredSourceTextFile("Epistemos/ActOsaurus/EpistemosOsaurusModelProvider.swift")
        let bootstrap = try loadMirroredSourceTextFile("Epistemos/App/AppBootstrap.swift")
        let sharedAct = try loadMirroredSourceTextFile("Epistemos/LocalAgent/SharedActInference.swift")
        let localAgent = try loadMirroredSourceTextFile("Epistemos/LocalAgent/LocalAgentLoop.swift")

        #expect(chatEngine.contains("EpistemosBridgedModelService()"))
        #expect(chatEngine.contains("EpistemosModelBridge.providedModelIds()"))
        #expect(coreModel.contains("EpistemosBridgedModelService()"))
        #expect(bridge.contains("public protocol EpistemosModelProvider"))
        #expect(bridge.contains("struct EpistemosBridgedModelService: ModelService"))
        #expect(presenter.contains("public static func modelPicks() async"))
        #expect(presenter.contains("public static func actSettingsSnapshot() async"))
        #expect(presenter.contains("public static func toolPermissionRows"))
        #expect(presenter.contains("public enum EpistemosOsaurusManagementBridge"))
        #expect(provider.contains("EpistemosModelBridge.register(EpistemosOsaurusModelProvider"))
        #expect(bootstrap.contains("EpistemosOsaurusModelProvider.register("))
        #expect(sharedAct.contains("actStreamIfArmed("))
        #expect(sharedAct.contains("ActOsaurusStreamingHandler.make()"))
        #expect(sharedAct.contains("var streamFilter = ActOsaurusVisibleStreamFilter.StreamState()"))
        #expect(sharedAct.contains("streamFilter.visibleDelta(from: token)"))
        #expect(sharedAct.contains("streamFilter.visibleDelta(from: text)"))
        #expect(sharedAct.contains("streamFilter.flushVisibleTail()"))
        #expect(sharedAct.contains("continuation.yield(.textDelta(visibleTail))"))
        #expect(sharedAct.contains("private var buffered = \"\""))
        #expect(sharedAct.contains("private static let knownSentinelPrefixes"))
        #expect(sharedAct.contains("private static let replacementSentinel: Character = \"\\u{FFFD}\""))
        #expect(sharedAct.contains("firstProtocolSentinelIndex(in: buffer)"))
        #expect(sharedAct.contains("isProtocolSentinel(at: index, in: text)"))
        #expect(sharedAct.contains("\"prefill:\""))
        #expect(sharedAct.contains("\"stats:\""))
        #expect(sharedAct.contains("case needsMoreInput"))
        #expect(sharedAct.contains("return flushIncomplete ? .skipped(text.endIndex) : .needsMoreInput"))
        #expect(localAgent.contains("? ActOsaurusGenerationHandler.make()"))
    }

}
