import Testing
@testable import Epistemos
import Foundation

// MARK: - Data Integrity Edge Case Tests
// Tests for corrupted data, boundary values, and integrity violations.

@Suite("Data Integrity - Corrupted JSON")
@MainActor
struct DataIntegrityCorruptedJSONTests {
    
    @Test("Corrupted JSON in metadata - invalid syntax")
    func corruptedJSONInvalidSyntax() {
        let node = SDGraphNode(type: .note, label: "Test")
        
        // Inject invalid JSON directly
        node.metadata = Data("{invalid json}".utf8)
        
        // Accessing meta should handle gracefully
        let meta = node.meta
        // Should return empty/default metadata, not crash
        #expect(meta.authors == nil)
        #expect(meta.year == nil)
    }
    
    @Test("Corrupted JSON - truncated")
    func truncatedJSON() {
        let node = SDGraphNode(type: .note, label: "Test")
        
        node.metadata = Data("{\"authors\": [\"A\", \"B\"".utf8)
        
        let meta = node.meta
        #expect(meta.authors == nil)
    }
    
    @Test("Corrupted JSON - wrong types")
    func wrongTypesJSON() {
        let node = SDGraphNode(type: .note, label: "Test")
        
        // year expects Int, give String
        node.metadata = Data("""
            {"year": "not a number", "authors": "not an array"}
            """.utf8)
        
        let meta = node.meta
        // Should handle type mismatches gracefully
        _ = meta
    }
    
    @Test("Corrupted JSON - null values")
    func nullValuesJSON() {
        let node = SDGraphNode(type: .note, label: "Test")
        
        node.metadata = Data("""
            {"year": null, "authors": null, "url": null}
            """.utf8)
        
        let meta = node.meta
        #expect(meta.year == nil)
        #expect(meta.authors == nil)
    }
    
    @Test("Corrupted JSON - extra fields")
    func extraFieldsJSON() {
        let node = SDGraphNode(type: .note, label: "Test")
        
        node.metadata = Data("""
            {"year": 2024, "unknownField": "value", "nested": {"key": "value"}}
            """.utf8)
        
        let meta = node.meta
        #expect(meta.year == 2024)
        // Should ignore unknown fields
    }
    
    @Test("Corrupted JSON - empty object")
    func emptyObjectJSON() {
        let node = SDGraphNode(type: .note, label: "Test")
        
        node.metadata = Data("{}".utf8)
        
        let meta = node.meta
        #expect(meta.year == nil)
        #expect(meta.authors == nil)
    }
    
    @Test("Corrupted JSON - binary garbage")
    func binaryGarbage() {
        let node = SDGraphNode(type: .note, label: "Test")
        
        var bytes: [UInt8] = []
        for _ in 0..<100 {
            bytes.append(UInt8.random(in: 0...255))
        }
        node.metadata = Data(bytes)
        
        let meta = node.meta
        // Should not crash on binary garbage
        _ = meta
    }
    
    @Test("Nil metadata access")
    func nilMetadata() {
        let node = SDGraphNode(type: .note, label: "Test")
        
        #expect(node.metadata == nil)
        
        let meta = node.meta
        #expect(meta.year == nil)
        #expect(meta.authors == nil)
    }
}

@Suite("Data Integrity - Missing SwiftData Fields")
@MainActor
struct DataIntegrityMissingFieldsTests {
    
    @Test("Node with empty ID")
    func emptyNodeID() {
        let node = SDGraphNode(type: .note, label: "Test")
        // id is auto-generated by default
        #expect(!node.id.isEmpty)
    }
    
    @Test("Node with empty type")
    func emptyNodeType() {
        let node = SDGraphNode(type: .note, label: "Test")
        // type has default
        #expect(!node.type.isEmpty)
    }
    
    @Test("Node with invalid type string")
    func invalidNodeType() {
        let node = SDGraphNode(type: .note, label: "Test")
        node.type = "invalidType"
        
        // nodeType computed property falls back to .note for unrecognized type strings.
        let resolvedType = node.nodeType
        #expect(resolvedType == .note)
    }
    
    @Test("Edge with empty source/target")
    func emptyEdgeEndpoints() {
        let edge = SDGraphEdge(source: "", target: "", type: .reference)
        
        #expect(edge.sourceNodeId == "")
        #expect(edge.targetNodeId == "")
    }
    
    @Test("Edge with missing type")
    func missingEdgeType() {
        let edge = SDGraphEdge(source: "a", target: "b", type: .reference)
        // type has default
        #expect(!edge.type.isEmpty)
    }
    
    @Test("Negative weights")
    func negativeWeights() {
        let node = SDGraphNode(type: .note, label: "Test", weight: -5.0)
        #expect(node.weight == -5.0)
        
        let edge = SDGraphEdge(source: "a", target: "b", type: .reference, weight: -10.0)
        #expect(edge.weight == -10.0)
    }
    
    @Test("Zero weights")
    func zeroWeights() {
        let node = SDGraphNode(type: .note, label: "Test", weight: 0)
        #expect(node.weight == 0)
        
        let edge = SDGraphEdge(source: "a", target: "b", type: .reference, weight: 0)
        #expect(edge.weight == 0)
    }
    
    @Test("Extreme weights")
    func extremeWeights() {
        let maxWeight = Double.greatestFiniteMagnitude
        let node = SDGraphNode(type: .note, label: "Test", weight: maxWeight)
        #expect(node.weight == maxWeight)
        
        let minWeight = -Double.greatestFiniteMagnitude
        let node2 = SDGraphNode(type: .note, label: "Test2", weight: minWeight)
        #expect(node2.weight == minWeight)
    }
}

@Suite("Data Integrity - Date Edge Cases")
@MainActor
struct DataIntegrityDateTests {
    
    @Test("Future dates in createdAt")
    func futureDates() {
        let future = Date(timeIntervalSinceNow: 86400 * 365) // 1 year from now
        
        let node = SDGraphNode(type: .note, label: "Future")
        node.createdAt = future
        
        #expect(node.createdAt == future)
    }
    
    @Test("Very old dates - epoch")
    func epochDate() {
        let epoch = Date(timeIntervalSince1970: 0)
        
        let node = SDGraphNode(type: .note, label: "Epoch")
        node.createdAt = epoch
        
        #expect(node.createdAt == epoch)
    }
    
    @Test("Distant past date")
    func distantPast() {
        let past = Date.distantPast
        
        let node = SDGraphNode(type: .note, label: "Ancient")
        node.createdAt = past
        
        #expect(node.createdAt == past)
    }
    
    @Test("Distant future date")
    func distantFuture() {
        let future = Date.distantFuture
        
        let node = SDGraphNode(type: .note, label: "Future")
        node.createdAt = future
        
        #expect(node.createdAt == future)
    }
    
    @Test("Negative time interval")
    func negativeTimeInterval() {
        let beforeEpoch = Date(timeIntervalSince1970: -1000000)
        
        let node = SDGraphNode(type: .note, label: "Before Epoch")
        node.createdAt = beforeEpoch
        
        #expect(node.createdAt == beforeEpoch)
    }
    
    @Test("Very large time interval")
    func largeTimeInterval() {
        let farFuture = Date(timeIntervalSince1970: 1e10)
        
        let node = SDGraphNode(type: .note, label: "Far Future")
        node.createdAt = farFuture
        
        #expect(node.createdAt == farFuture)
    }
    
    @Test("UpdatedAt before createdAt")
    func updatedBeforeCreated() {
        let node = SDGraphNode(type: .note, label: "Test")
        
        let created = Date.now
        let updated = Date(timeIntervalSinceNow: -3600) // 1 hour ago
        
        node.createdAt = created
        node.updatedAt = updated
        
        // This is logically inconsistent but should be allowed
        #expect(node.updatedAt < node.createdAt)
    }
}

@Suite("Data Integrity - Circular References")
@MainActor
struct DataIntegrityCircularReferenceTests {
    
    @Test("Self-loop edge")
    func selfLoopEdge() {
        let store = GraphStore()
        
        store.addNode(makeNode(id: "self"))
        
        let selfEdge = GraphEdgeRecord(
            id: "self-loop",
            sourceNodeId: "self",
            targetNodeId: "self",
            type: .reference,
            weight: 1.0,
            createdAt: .now
        )
        store.addEdge(selfEdge)
        
        // Self-loop creates odd adjacency
        let neighbors = store.neighbors(of: "self")
        #expect(neighbors.count == 1) // Self is neighbor
        #expect(store.adjacency["self"]?.contains("self") == true)
    }
    
    @Test("Mutual references")
    func mutualReferences() {
        let store = GraphStore()
        
        store.addNode(makeNode(id: "a"))
        store.addNode(makeNode(id: "b"))
        
        // a -> b
        store.addEdge(makeEdge(id: "e1", source: "a", target: "b"))
        // b -> a
        store.addEdge(makeEdge(id: "e2", source: "b", target: "a"))
        
        // Both should have each other as neighbors
        #expect(store.neighbors(of: "a").count == 1)
        #expect(store.neighbors(of: "b").count == 1)
    }
    
    @Test("Triangle cycle")
    func triangleCycle() {
        let store = GraphStore()
        
        for id in ["a", "b", "c"] {
            store.addNode(makeNode(id: id))
        }
        
        // a -> b -> c -> a
        store.addEdge(makeEdge(source: "a", target: "b"))
        store.addEdge(makeEdge(source: "b", target: "c"))
        store.addEdge(makeEdge(source: "c", target: "a"))
        
        // BFS should handle cycle without infinite loop
        let connected = store.connected(to: "a", maxDepth: 10)
        #expect(connected.count == 3)
    }
    
    @Test("Complex cyclic graph")
    func complexCyclicGraph() {
        let store = GraphStore()
        
        // Create multiple cycles
        for id in ["a", "b", "c", "d", "e"] {
            store.addNode(makeNode(id: id))
        }
        
        // Cycle 1: a-b-c-a
        store.addEdge(makeEdge(source: "a", target: "b"))
        store.addEdge(makeEdge(source: "b", target: "c"))
        store.addEdge(makeEdge(source: "c", target: "a"))
        
        // Cycle 2: c-d-e-c
        store.addEdge(makeEdge(source: "c", target: "d"))
        store.addEdge(makeEdge(source: "d", target: "e"))
        store.addEdge(makeEdge(source: "e", target: "c"))
        
        // Shortest path should handle cycles
        let path = store.query(.pathBetween(from: "a", to: "e", maxHops: 10))
        #expect(!path.isEmpty)
    }
    
    private func makeNode(id: String) -> GraphNodeRecord {
        GraphNodeRecord(
            id: id, type: .note, label: id, sourceId: nil,
            metadata: GraphNodeMetadata(), weight: 1.0,
            createdAt: .now, position: .zero, velocity: .zero
        )
    }
    
    private func makeEdge(id: String = UUID().uuidString, source: String, target: String) -> GraphEdgeRecord {
        GraphEdgeRecord(
            id: id, sourceNodeId: source, targetNodeId: target,
            type: .reference, weight: 1.0, createdAt: .now
        )
    }
}

@Suite("Data Integrity - Orphan Edges")
@MainActor
struct DataIntegrityOrphanEdgeTests {
    
    @Test("Edge pointing to deleted node")
    func edgeToDeletedNode() {
        let store = GraphStore()
        
        store.addNode(makeNode(id: "source"))
        store.addNode(makeNode(id: "target"))
        store.addEdge(makeEdge(source: "source", target: "target"))
        
        #expect(store.edgeCount == 1)
        
        // Remove target node
        store.removeNode("target")
        
        // Edge should be removed
        #expect(store.edgeCount == 0)
        #expect(store.edges(for: "source").isEmpty)
    }
    
    @Test("Edge with non-existent target")
    func edgeToNonExistentTarget() {
        let store = GraphStore()
        
        store.addNode(makeNode(id: "source"))
        
        let edge = GraphEdgeRecord(
            id: "orphan",
            sourceNodeId: "source",
            targetNodeId: "nonexistent",
            type: .reference,
            weight: 1.0,
            createdAt: .now
        )
        store.addEdge(edge)
        
        // Should be silently ignored
        #expect(store.edgeCount == 0)
    }
    
    @Test("Edge with non-existent source")
    func edgeFromNonExistentSource() {
        let store = GraphStore()
        
        store.addNode(makeNode(id: "target"))
        
        let edge = GraphEdgeRecord(
            id: "orphan",
            sourceNodeId: "nonexistent",
            targetNodeId: "target",
            type: .reference,
            weight: 1.0,
            createdAt: .now
        )
        store.addEdge(edge)
        
        // Should be silently ignored
        #expect(store.edgeCount == 0)
    }
    
    @Test("Both endpoints non-existent")
    func bothEndpointsNonExistent() {
        let store = GraphStore()
        
        let edge = GraphEdgeRecord(
            id: "orphan",
            sourceNodeId: "ghost1",
            targetNodeId: "ghost2",
            type: .reference,
            weight: 1.0,
            createdAt: .now
        )
        store.addEdge(edge)
        
        #expect(store.edgeCount == 0)
    }
    
    private func makeNode(id: String) -> GraphNodeRecord {
        GraphNodeRecord(
            id: id, type: .note, label: id, sourceId: nil,
            metadata: GraphNodeMetadata(), weight: 1.0,
            createdAt: .now, position: .zero, velocity: .zero
        )
    }
    
    private func makeEdge(source: String, target: String) -> GraphEdgeRecord {
        GraphEdgeRecord(
            id: "\(source)-\(target)",
            sourceNodeId: source, targetNodeId: target,
            type: .reference, weight: 1.0, createdAt: .now
        )
    }
    
    @Test("Edge index consistency")
    func edgeIndexConsistency() {
        let store = GraphStore()
        
        for i in 0..<5 {
            store.addNode(makeNode(id: "\(i)"))
        }
        
        for i in 0..<4 {
            store.addEdge(makeEdge(source: "\(i)", target: "\(i+1)"))
        }
        
        // Each node should have correct edge count
        #expect(store.edgesByNode["0"]?.count == 1)
        #expect(store.edgesByNode["1"]?.count == 2)
        #expect(store.edgesByNode["4"]?.count == 1)
    }
    
    @Test("Node lookup by source ID")
    func nodeLookupBySourceId() {
        let store = GraphStore()
        
        let node1 = GraphNodeRecord(
            id: "id1",
            type: .note,
            label: "Note",
            sourceId: "page-123",
            metadata: GraphNodeMetadata(),
            weight: 1.0,
            createdAt: .now,
            position: .zero,
            velocity: .zero
        )
        store.addNode(node1)
        
        let found = store.node(bySourceId: "page-123", type: .note)
        #expect(found?.id == "id1")
    }
    
    @Test("Multiple nodes same type different source")
    func multipleNodesSameType() {
        let store = GraphStore()
        
        for i in 0..<10 {
            let node = GraphNodeRecord(
                id: "id-\(i)",
                type: .note,
                label: "Note \(i)",
                sourceId: "page-\(i)",
                metadata: GraphNodeMetadata(),
                weight: 1.0,
                createdAt: .now,
                position: .zero,
                velocity: .zero
            )
            store.addNode(node)
        }
        
        #expect(store.nodes(ofType: .note).count == 10)
    }
    
    @Test("GraphStore fresh instance is empty")
    func graphStoreFreshEmpty() {
        let store = GraphStore()

        #expect(store.nodeCount == 0)
        #expect(store.edgeCount == 0)
        #expect(store.nodes.isEmpty)
        #expect(store.edges.isEmpty)
    }
    
    @Test("Link count with multiple edges")
    func linkCountWithMultipleEdges() {
        let store = GraphStore()
        
        store.addNode(makeNode(id: "center"))
        for i in 0..<5 {
            store.addNode(makeNode(id: "spoke-\(i)"))
            store.addEdge(makeEdge(source: "center", target: "spoke-\(i)"))
        }
        
        #expect(store.linkCount(for: "center") == 5)
    }
    
    @Test("Position hints storage")
    func positionHintsStorage() {
        let store = GraphStore()
        
        store.positionHints["test-node"] = SIMD2<Float>(100, 200)
        
        #expect(store.positionHints["test-node"] == SIMD2<Float>(100, 200))
    }
    
    @Test("Graph node types count")
    func graphNodeTypesCount() {
        #expect(GraphNodeType.allCases.count == 14)
    }
    
    @Test("Graph edge types count")
    func graphEdgeTypesCount() {
        let edgeTypes: [GraphEdgeType] = [.reference, .contains, .tagged, .mentions, .cites,
                                           .authored, .related, .quotes, .supports, .contradicts,
                                           .expands, .questions]
        #expect(edgeTypes.count == 12)
    }
    
    @Test("Node type display names")
    func nodeTypeDisplayNames() {
        for type in GraphNodeType.allCases {
            #expect(!type.displayName.isEmpty)
        }
    }
    
    @Test("Node type icons")
    func nodeTypeIcons() {
        for type in GraphNodeType.allCases {
            #expect(!type.icon.isEmpty)
        }
    }
    
    @Test("Node type rust indices")
    func nodeTypeRustIndices() {
        var indices: Set<UInt8> = []
        for type in GraphNodeType.allCases {
            indices.insert(type.rustIndex)
        }
        #expect(indices.count == GraphNodeType.allCases.count)
    }
}

@Suite("Data Integrity - String Edge Cases")
@MainActor
struct DataIntegrityStringTests {
    
    @Test("Null bytes in strings")
    func nullBytesInStrings() {
        let label = "Hello\0World"
        let node = SDGraphNode(type: .note, label: label)
        
        #expect(node.label.contains("\0"))
        
        // C string conversion should handle null bytes
        let cString = label.cString(using: .utf8)
        #expect(cString != nil)
    }
    
    @Test("Maximum string length")
    func maximumStringLength() {
        let maxLabel = String(repeating: "A", count: 100_000)
        let node = SDGraphNode(type: .note, label: maxLabel)
        
        #expect(node.label.count == 100_000)
    }
    
    @Test("Invalid UTF-8 sequences")
    func invalidUTF8() {
        // Invalid UTF-8 bytes
        let invalidBytes: [UInt8] = [0xC0, 0x80, 0xFF, 0xFE]
        
        // Creating string from invalid bytes
        if let invalidString = String(bytes: invalidBytes, encoding: .utf8) {
            let node = SDGraphNode(type: .note, label: invalidString)
            _ = node.label
        }
        
        // Fails gracefully if encoding fails
        #expect(String(bytes: invalidBytes, encoding: .utf8) == nil)
    }
    
    @Test("BMP and non-BMP characters")
    func bmpNonBmpCharacters() {
        // BMP: Basic Multilingual Plane (U+0000 to U+FFFF)
        // Non-BMP: Supplementary planes (U+10000+)
        
        let bmp = "ABC"
        let nonBmp = "𐍈𐌰𐍄𐌰𐌹" // Gothic letters
        let emoji = "👨‍👩‍👧‍👦" // Family emoji
        
        let node1 = SDGraphNode(type: .note, label: bmp)
        let node2 = SDGraphNode(type: .note, label: nonBmp)
        let node3 = SDGraphNode(type: .note, label: emoji)
        
        #expect(node1.label == bmp)
        #expect(node2.label == nonBmp)
        #expect(node3.label == emoji)
    }
    
    @Test("Surrogate pairs")
    func surrogatePairs() {
        // UTF-16 surrogate pairs are NOT valid Unicode scalars in Swift.
        // Test with a valid supplementary plane character instead (emoji).
        let supplementary = "\u{1F600}"  // Grinning face

        let node = SDGraphNode(type: .note, label: supplementary)
        #expect(!node.label.isEmpty)
        #expect(node.label == supplementary)
    }
}

@Suite("Data Integrity - Numeric Edge Cases")
@MainActor
struct DataIntegrityNumericTests {
    
    @Test("NaN in metadata")
    func nanInMetadata() {
        let node = SDGraphNode(type: .source, label: "Test")
        var meta = GraphNodeMetadata()
        // Int(Float.nan) traps in Swift — never call it. Test the guard directly.
        let value = Float.nan
        meta.year = value.isFinite ? Int(value) : nil
        node.meta = meta

        #expect(node.meta.year == nil)
    }
    
    @Test("Infinity in metadata")
    func infinityInMetadata() {
        let node = SDGraphNode(type: .source, label: "Test")
        var meta = GraphNodeMetadata()
        // year is Int?, can't directly store infinity
        // But we can test extreme values
        meta.year = Int.max
        node.meta = meta
        
        #expect(node.meta.year == Int.max)
    }
    
    @Test("Maximum integer values")
    func maximumIntegerValues() {
        let maxInt = Int.max
        let minInt = Int.min
        
        let meta = GraphNodeMetadata(
            evidenceGrade: nil,
            researchStage: maxInt,
            url: nil,
            authors: nil,
            quoteText: nil,
            year: maxInt,
            journal: nil,
            doi: nil,
            abstract: nil,
            clusterTheme: nil,
            originChatId: nil,
            originNoteId: nil
        )
        
        #expect(meta.year == maxInt)
        #expect(meta.researchStage == maxInt)
        
        let meta2 = GraphNodeMetadata(
            evidenceGrade: nil,
            researchStage: minInt,
            url: nil,
            authors: nil,
            quoteText: nil,
            year: minInt,
            journal: nil,
            doi: nil,
            abstract: nil,
            clusterTheme: nil,
            originChatId: nil,
            originNoteId: nil
        )
        
        #expect(meta2.year == minInt)
    }
    
    @Test("Floating point precision edge cases")
    func floatingPointPrecision() {
        let epsilon = Double.ulpOfOne
        let verySmall = Double.leastNormalMagnitude
        let veryLarge = Double.greatestFiniteMagnitude
        
        let node1 = SDGraphNode(type: .note, label: "Epsilon", weight: epsilon)
        let node2 = SDGraphNode(type: .note, label: "Tiny", weight: verySmall)
        let node3 = SDGraphNode(type: .note, label: "Huge", weight: veryLarge)
        
        #expect(node1.weight == epsilon)
        #expect(node2.weight == verySmall)
        #expect(node3.weight == veryLarge)
    }
    
    @Test("Denormalized floating point")
    func denormalizedFloat() {
        let denorm = Double.leastNonzeroMagnitude
        
        let node = SDGraphNode(type: .note, label: "Denorm", weight: denorm)
        #expect(node.weight == denorm)
    }
}

@Suite("Data Integrity - Legacy Migration")
@MainActor
struct DataIntegrityLegacyMigrationTests {
    
    @Test("Legacy node type - brainDump")
    func legacyBrainDump() {
        let migrated = GraphNodeType(legacy: "brainDump")
        #expect(migrated == .idea)
    }
    
    @Test("Legacy node type - insight")
    func legacyInsight() {
        let migrated = GraphNodeType(legacy: "insight")
        #expect(migrated == .idea)
    }
    
    @Test("Legacy node type - paper")
    func legacyPaper() {
        let migrated = GraphNodeType(legacy: "paper")
        #expect(migrated == .source)
    }
    
    @Test("Legacy node type - book")
    func legacyBook() {
        let migrated = GraphNodeType(legacy: "book")
        #expect(migrated == .source)
    }
    
    @Test("Legacy node type - thinker")
    func legacyThinker() {
        let migrated = GraphNodeType(legacy: "thinker")
        #expect(migrated == .source)
    }
    
    @Test("Legacy node type - concept")
    func legacyConcept() {
        let migrated = GraphNodeType(legacy: "concept")
        #expect(migrated == .tag)
    }
    
    @Test("Legacy node type - unknown")
    func legacyUnknown() {
        let migrated = GraphNodeType(legacy: "unknownType")
        #expect(migrated == .note) // Falls back to note
    }
    
    @Test("Legacy edge type - wikilink")
    func legacyWikilink() {
        let migrated = GraphEdgeType(legacy: "wikilink")
        #expect(migrated == .reference)
    }
    
    @Test("Legacy edge type - ideaLink")
    func legacyIdeaLink() {
        let migrated = GraphEdgeType(legacy: "ideaLink")
        #expect(migrated == .reference)
    }
    
    @Test("Legacy edge type - livesIn")
    func legacyLivesIn() {
        let migrated = GraphEdgeType(legacy: "livesIn")
        #expect(migrated == .contains)
    }
    
    @Test("Legacy edge type - mentionedIn")
    func legacyMentionedIn() {
        let migrated = GraphEdgeType(legacy: "mentionedIn")
        #expect(migrated == .mentions)
    }
    
    @Test("Legacy edge type - unknown")
    func legacyEdgeUnknown() {
        let migrated = GraphEdgeType(legacy: "unknownRelation")
        #expect(migrated == .reference) // Falls back to reference
    }
}

@Suite("Data Integrity - Graph Store Consistency")
@MainActor
struct DataIntegrityStoreConsistencyTests {
    
    @Test("Node count consistency")
    func nodeCountConsistency() {
        let store = GraphStore()
        
        for i in 0..<10 {
            store.addNode(makeNode(id: "\(i)"))
        }
        
        #expect(store.nodeCount == 10)
        #expect(store.nodes.count == 10)
        #expect(store.adjacency.count == 10)
        #expect(store.edgesByNode.count == 10)
    }
    
    @Test("Edge count consistency after removal")
    func edgeCountAfterRemoval() {
        let store = GraphStore()
        
        store.addNode(makeNode(id: "a"))
        store.addNode(makeNode(id: "b"))
        store.addNode(makeNode(id: "c"))
        
        store.addEdge(makeEdge(source: "a", target: "b"))
        store.addEdge(makeEdge(source: "b", target: "c"))
        
        #expect(store.edgeCount == 2)
        
        store.removeNode("b")
        
        #expect(store.edgeCount == 0)
        #expect(store.neighbors(of: "a").isEmpty)
        #expect(store.neighbors(of: "c").isEmpty)
    }
    
    @Test("Adjacency list symmetry")
    func adjacencySymmetry() {
        let store = GraphStore()
        
        store.addNode(makeNode(id: "a"))
        store.addNode(makeNode(id: "b"))
        store.addEdge(makeEdge(source: "a", target: "b"))
        
        // Adjacency should be symmetric
        #expect(store.adjacency["a"]?.contains("b") == true)
        #expect(store.adjacency["b"]?.contains("a") == true)
    }
    
    private func makeNode(id: String) -> GraphNodeRecord {
        GraphNodeRecord(
            id: id, type: .note, label: id, sourceId: nil,
            metadata: GraphNodeMetadata(), weight: 1.0,
            createdAt: .now, position: .zero, velocity: .zero
        )
    }
    
    private func makeEdge(source: String, target: String) -> GraphEdgeRecord {
        GraphEdgeRecord(
            id: "\(source)-\(target)",
            sourceNodeId: source, targetNodeId: target,
            type: .reference, weight: 1.0, createdAt: .now
        )
    }
}
