import Foundation
import Testing
@testable import Epistemos

// Goose web-only surface guards.
//
// Two layers:
//  1. Source invariants (pure, always run): prove the retired native-route router/toggles and
//     native route panels are gone after the owner cut the native rail and per-route panels.
//  2. Live parity (gated on a real Goose runtime): prove the Goose ACP provider/defaults data
//     source stays live-enumerated while the product path stays Goose WebView-only.

@Suite("Goose web-only surface source invariants")
@MainActor
struct GooseWebOnlySurfaceSourceTests {
    @Test("native Agent window keeps Goose primary and does not stack a second sidebar")
    func nativeAgentWindowKeepsGoosePrimary() throws {
        let sourceRoot = try sourceMirrorRootURL()
        #expect(!FileManager.default.fileExists(atPath: sourceRoot.appendingPathComponent(
            "Epistemos/Goose/GooseSurfaceRouter.swift",
            isDirectory: false
        ).path))
        #expect(!FileManager.default.fileExists(atPath: sourceRoot.appendingPathComponent(
            "Epistemos/Goose/GooseNativeModelsView.swift",
            isDirectory: false
        ).path))

        let root = try loadMirroredSourceTextFile("Epistemos/Agent/AgentSurfaceRootView.swift")
        #expect(root.contains("GooseWebSurfaceView(theme: theme)"))
        #expect(root.contains(".frame(maxWidth: .infinity, maxHeight: .infinity)"))
        #expect(root.contains(".ignoresSafeArea()"))
        #expect(!root.contains("ZStack"))
        #expect(!root.contains("GooseSurfaceStyle.background(for: theme)"))
        #expect(!root.contains("AgentRailDestination"))
        #expect(!root.contains("AgentNavigationRailView("))
        #expect(!root.contains("AgentLauncherPanelView("))
        #expect(!root.contains("routeShortcutButtons"))
        #expect(!root.contains(".keyboardShortcut(\"l\", modifiers: .command)"))
        #expect(!root.contains(".padding(.horizontal, 14)"))
        #expect(!root.contains(".clipShape(shape)"))
        #expect(!root.contains("shape.strokeBorder"))

        let window = try loadMirroredSourceTextFile("Epistemos/Agent/AgentSurfaceWindowController.swift")
        #expect(window.contains("window.titleVisibility = .hidden"))
        #expect(window.contains("window.backgroundColor = .clear"))
        #expect(window.contains("window.isOpaque = false"))
        #expect(window.contains("window.contentView = host"))
        #expect(window.contains("WindowThemeStyler.refreshChrome(of: window)"))
        #expect(window.contains("host.layer?.cornerRadius = 18"))
        #expect(window.contains("host.layer?.masksToBounds = true"))
        #expect(!window.contains("WindowThemeStyler.themedContentView"))
        #expect(!window.contains("WindowThemeStyler.apply(to: window"))

        let fallbackWindow = try loadMirroredSourceTextFile("Epistemos/Goose/GooseSurfaceWindowController.swift")
        #expect(fallbackWindow.contains("window.titleVisibility = .hidden"))
        #expect(fallbackWindow.contains("window.backgroundColor = .clear"))
        #expect(fallbackWindow.contains("window.isOpaque = false"))
        #expect(fallbackWindow.contains("window.contentView = host"))
        #expect(fallbackWindow.contains("WindowThemeStyler.refreshChrome(of: window)"))
        #expect(fallbackWindow.contains("host.layer?.cornerRadius = 18"))
        #expect(fallbackWindow.contains("host.layer?.masksToBounds = true"))
        #expect(!fallbackWindow.contains("WindowThemeStyler.themedContentView"))
        #expect(!fallbackWindow.contains("WindowThemeStyler.apply(to: window"))

        let webView = try loadMirroredSourceTextFile("Epistemos/Goose/GooseWebSurfaceView.swift")
        #expect(webView.contains("WebView(page)"))
        #expect(webView.contains(".ignoresSafeArea()"))
        #expect(webView.contains("nativeACPOverlay"))
        #expect(webView.contains("private func setWebRoute"))
        #expect(webView.contains("route: activeWebRoute"))
        #expect(!webView.contains("GooseSurfaceRouter()"))
        #expect(!webView.contains("GooseNativeModelsView("))
        #expect(!webView.contains("nativeModelsRouteIsActive"))
        #expect(!webView.contains("router.isNative"))
        #expect(!webView.contains("detailsPanel"))
        #expect(!webView.contains("detailsButton"))
        #expect(!webView.contains("Label(\"Manage models\""))

        let reskin = try loadMirroredSourceTextFile("scripts/stage-goose-native-reskin.mjs")
        #expect(reskin.contains("epistemos-native-high-quality-flat-polish"))
        #expect(reskin.contains("epistemos-native-claude-pixel-polish"))
        #expect(reskin.contains("epistemos-native-claude-pixel-contract"))
        #expect(reskin.contains("epistemos-native-claude-desktop-lock"))
        #expect(reskin.contains("epistemos-native-flat-source-surfaces"))
        #expect(reskin.contains("Surfaces separate by spacing, tint, and state, not hard boxes."))
        #expect(reskin.contains("Visual target: Claude's calm single-sidebar app shell"))
        #expect(reskin.contains("Claude-like flat: single Goose sidebar, quiet canvas"))
        #expect(reskin.contains("Claude-like\n   flat desktop shell"))
        #expect(reskin.contains("--epistemos-claude-bg: var(--color-background-primary);"))
        #expect(reskin.contains("--epistemos-claude-sidebar: color-mix(in srgb, var(--color-background-secondary) 72%, var(--color-background-primary));"))
        #expect(reskin.contains("--epistemos-claude-focus:"))
        #expect(reskin.contains("--epistemos-claude-composer-shadow:"))
        #expect(reskin.contains("--epistemos-pixel-accent: var(--epistemos-accent);"))
        #expect(reskin.contains("--epistemos-pixel-font:"))
        #expect(reskin.contains("navigation active rows borderless"))
        #expect(reskin.contains("rounded-[8px] px-2.5 py-1.5 text-[13px]"))
        #expect(reskin.contains("text-left flex-1 truncate font-sans tracking-normal"))
        #expect(reskin.contains("ep-pixel flex items-center gap-1"))
        #expect(reskin.contains("bg-background-primary/40"))
        #expect(reskin.contains("bg-background-primary/54 pb-2"))
        #expect(reskin.contains("bg-background-primary/54 p-3"))
        #expect(reskin.contains("bg-[var(--epistemos-accent)]/12"))
        #expect(reskin.contains("focus:bg-background-secondary/72 focus:outline-none focus:ring-0"))
        #expect(reskin.contains("focus-visible:bg-[var(--epistemos-accent)]/10 focus-visible:ring-0"))
        #expect(reskin.contains("focus-visible:bg-[var(--epistemos-accent)]/10 focus-visible:outline-none"))
        #expect(reskin.contains("rounded-[9px] p-1 space-y-0.5"))
        #expect(reskin.contains("select__menu z-[9999] absolute overflow-hidden"))
        #expect(reskin.contains("rounded-[11px] bg-background-primary/54"))
        #expect(reskin.contains("min-h-[128px] overflow-hidden bg-background-primary/54"))
        #expect(reskin.contains("absolute -bottom-2 right-2 whitespace-nowrap rounded-[8px] bg-background-secondary/72"))
        #expect(reskin.contains("mt-2 flex flex-wrap gap-2 bg-background-primary/24 p-4"))
        #expect(reskin.contains("rounded-[10px] bg-background-secondary/56 object-cover"))
        #expect(reskin.contains("rounded-[10px] bg-background-secondary/56 px-3 py-2"))
        #expect(reskin.contains("rounded-[8px] bg-background-primary/70 text-xs font-mono"))
        #expect(reskin.contains("bg-background-danger/35"))
        #expect(reskin.contains("return 'bg-background-success';"))
        #expect(reskin.contains("absolute -right-0.5 -top-0.5 h-2 w-2 rounded-full"))
        #expect(reskin.contains("rounded-full bg-background-success"))
        #expect(reskin.contains("rounded-[12px] bg-background-warning/55"))
        #expect(reskin.contains("min-h-9 rounded-[8px] px-3 py-2"))
        #expect(reskin.contains("rounded-[9px] bg-background-secondary/56"))
        #expect(reskin.contains("bg-background-success/55 text-text-success"))
        #expect(reskin.contains("rounded-[8px] bg-background-primary/60"))
        #expect(reskin.contains("bg-background-secondary/56 p-1"))
        #expect(reskin.contains("rounded-[12px] bg-background-primary/42 px-4 py-2.5"))
        #expect(reskin.contains("rounded-[8px] bg-background-secondary/60 px-2 py-1"))
        #expect(reskin.contains("rounded-[10px] bg-background-warning/35 px-4 py-1.5"))
        #expect(reskin.contains("bg-background-primary/54 hover:bg-background-secondary/56"))
        #expect(reskin.contains("rounded-[8px] bg-background-primary/60 px-2 py-1 text-sm"))
        #expect(reskin.contains("tool response detail separators borderless"))
        #expect(reskin.contains("goose-message-content overflow-hidden rounded-[12px] bg-background-primary/54"))
        #expect(reskin.contains("bg-background-secondary/62 px-3 py-2 text-xs font-sans"))
        #expect(reskin.contains("mx-auto my-2 w-full max-w-4xl rounded-[12px] bg-background-secondary/56"))
        #expect(reskin.contains("w-full resize-none rounded-[10px] bg-background-primary/60 text-sm leading-relaxed"))
        #expect(reskin.contains("mb-4 max-w-md rounded-[12px] bg-background-danger/35 p-4"))
        #expect(reskin.contains("rounded-[8px] bg-background-secondary/56 px-4 py-2"))
        #expect(reskin.contains("no-drag flex items-center gap-2 rounded-[8px] bg-background-primary/58"))
        #expect(reskin.contains("flex items-center justify-between bg-background-primary/42 p-6"))
        #expect(reskin.contains("w-full rounded-[10px] bg-background-primary/60 p-3 text-text-standard"))
        #expect(reskin.contains("flex justify-end gap-3 bg-background-primary/42 p-6"))
        #expect(reskin.contains("accent-[var(--epistemos-accent)]"))
        #expect(reskin.contains("space-y-2 rounded-[12px] bg-background-secondary/44 p-3"))
        #expect(reskin.contains("rounded-[12px] bg-background-secondary/56 px-4 py-3"))
        #expect(reskin.contains("rounded-[12px] bg-background-secondary/32 px-4 py-3"))
        #expect(reskin.contains("w-[900px] max-w-[90vw] flex-col overflow-hidden rounded-[14px]"))
        #expect(reskin.contains("w-[800px] max-w-[90vw] flex-col overflow-hidden rounded-[14px]"))
        #expect(reskin.contains("rounded-[10px] bg-background-secondary/60"))
        #expect(reskin.contains("w-full cursor-pointer rounded-[10px] p-3 transition-colors"))
        #expect(reskin.contains("mt-3 rounded-[12px] bg-background-secondary/44 p-3"))
        #expect(reskin.contains("rounded-[12px] bg-background-primary/34 px-3 py-2"))
        #expect(reskin.contains("rounded-[10px] bg-background-danger/35 p-3 text-sm text-text-danger"))
        #expect(reskin.contains("w-screen h-screen bg-transparent"))
        #expect(reskin.contains("relative flex h-full w-full flex-col overflow-hidden bg-transparent"))
        #expect(reskin.contains("bg-background-primary/58 px-6 pb-5 pt-14"))
        #expect(reskin.contains("ep-native-header-band flex flex-col rounded-[16px] bg-background-primary/42 p-4"))
        #expect(reskin.contains("rounded-[10px] bg-background-danger/28 p-3"))
        #expect(reskin.contains("goose-message-tool mt-1 rounded-[12px] bg-background-primary/54"))
        #expect(reskin.contains("focus:bg-background-secondary/72 focus:border-transparent"))
        #expect(reskin.contains("rounded-[8px] bg-background-secondary/44 px-2 py-1.5"))
        #expect(reskin.contains("ml-3 rounded-[8px] bg-background-secondary/40 px-3 py-1"))
        #expect(reskin.contains("rounded-[10px] bg-background-primary/60 p-3"))
        #expect(reskin.contains("min-h-0 overflow-hidden rounded-[12px] bg-background-secondary/54"))
        #expect(reskin.contains("flex shrink-0 items-center bg-background-primary/70 px-3"))
        #expect(reskin.contains(".goose-epistemos .bg-background-tertiary"))
        let desktopLock = try #require(reskin.components(separatedBy: "Epistemos Claude desktop lock").last)
        #expect(desktopLock.contains("""
.goose-epistemos :is(
  .bg-background-primary,
  .bg-background-default
) {
  background: transparent !important;
}
"""))
        #expect(!desktopLock.contains("""
.goose-epistemos :is(
  .bg-background-primary,
  .bg-background-tertiary,
  .bg-background-default
) {
  background: transparent !important;
}
"""))
        #expect(reskin.contains("[class~='bg-[var(--epistemos-accent)]']"))
        #expect(reskin.contains("color: var(--color-text-inverse) !important;"))
        #expect(reskin.contains(".ep-display"))
        #expect(reskin.contains(".ep-pixel"))
        #expect(reskin.contains(":is(h1, h2, h3, h4, h5, h6):not(.ep-display):not(.ep-pixel)"))
        #expect(reskin.contains("border-color: transparent !important;"))
        #expect(reskin.contains("border-width: 0 !important;"))
        #expect(reskin.contains("border-right-width: 0 !important;"))
        #expect(reskin.contains("box-shadow: none !important;"))
        #expect(reskin.contains("--tw-ring-shadow: 0 0 #0000 !important;"))
        #expect(reskin.contains("backdrop-filter: none !important;"))
        #expect(reskin.contains("background: var(--epistemos-claude-surface) !important;"))
        #expect(reskin.contains("box-shadow:"))
        #expect(reskin.contains("image-rendering: pixelated;"))
        #expect(reskin.contains("outline: none !important;"))
        #expect(reskin.contains("background: color-mix(in srgb, var(--epistemos-pixel-accent) 7%, var(--epistemos-claude-surface)) !important;"))
        #expect(reskin.contains("background: color-mix(in srgb, var(--epistemos-pixel-accent) 5%, var(--epistemos-claude-surface)) !important;"))
        #expect(reskin.contains(".goose-epistemos .goose-chat-input-card:focus-within"))
        #expect(reskin.contains("background: var(--epistemos-claude-focus) !important;"))
        #expect(reskin.contains("box-shadow: var(--epistemos-claude-composer-shadow) !important;"))
        #expect(reskin.contains("box-shadow: 0 18px 46px color-mix(in srgb, var(--epistemos-pixel-accent) 9%, transparent) !important;"))
        #expect(reskin.contains("epistemos-native-final-flat-pixel-audit"))
        #expect(reskin.contains("applyFinalBorderlessDriftSurfaces"))
        #expect(reskin.contains("h-11 w-full rounded-[8px] bg-background-primary/58"))
        #expect(reskin.contains("pointer-events-auto fixed z-50 w-[275px] overflow-hidden rounded-[12px]"))
        #expect(reskin.contains("max-h-[300px] overflow-y-auto rounded-[12px] bg-background-secondary/44"))
        #expect(reskin.contains(".replaceAll('#0066cc', 'var(--epistemos-pixel-accent)')"))
        #expect(reskin.contains(".replaceAll('#2997ff', 'var(--epistemos-pixel-accent)')"))
        #expect(reskin.contains("const paletteClassReplacements = ["))
        #expect(reskin.contains("['text-amber-700', 'text-text-warning']"))
        #expect(reskin.contains("['text-purple-700', 'text-[var(--epistemos-accent)]']"))
        #expect(reskin.contains("['bg-amber-50/10', 'bg-background-warning/35']"))
        #expect(reskin.contains("['bg-orange-400', 'bg-background-warning']"))
        #expect(reskin.contains("['fill-orange-400', 'fill-[var(--color-background-warning)]']"))
        #expect(!reskin.contains("outline: 2px solid color-mix"))
        #expect(!reskin.contains("focus-visible:ring-[3px] focus-visible:ring-[var(--epistemos-accent)]/20"))
        #expect(!reskin.contains("box-shadow: inset 0 0 0 1px var(--epistemos-claude-hairline)"))
        #expect(!reskin.contains("box-shadow: inset 0 0 0 1px var(--epistemos-flat-focus)"))
        #expect(!reskin.contains("goose-message-tool mt-1 rounded-[12px] border border-border-secondary bg-background-primary/68"))
        #expect(!reskin.contains("bg-background-primary/58 px-6 pb-5 pt-14 border-b border-border-secondary backdrop-blur-xl"))

        let stageScript = try loadMirroredSourceTextFile("stage-goose-web-ui.sh")
        #expect(stageScript.contains("Goose Web UI staging still contains blue/ring/outline visual leftovers."))
        #expect(stageScript.contains("Goose Web UI staging still contains hard border visual leftovers."))
        #expect(stageScript.contains("Goose Web UI staging still contains hardcoded Tailwind palette leftovers."))
        #expect(stageScript.contains("palettePattern"))
        #expect(stageScript.contains("fill|stroke"))
        #expect(stageScript.contains("Goose Web UI artifact still contains hardcoded Tailwind palette leftovers after bundle postprocess."))
        #expect(stageScript.contains("['text-orange-500', 'text-text-warning']"))
        #expect(stageScript.contains("outline-hidden|outline: 2px solid"))
        #expect(stageScript.contains("epistemos-native-claude-pixel-contract"))
        #expect(stageScript.contains("epistemos-native-claude-desktop-lock"))
        #expect(stageScript.contains("epistemos-native-flat-source-surfaces"))
        #expect(stageScript.contains("--tw-ring-shadow: 0 0 #0000 !important"))
        #expect(stageScript.contains("backdrop-filter: none !important"))
        #expect(stageScript.contains("background: var(--epistemos-claude-focus) !important"))
        #expect(stageScript.contains("--epistemos-claude-composer-shadow:"))
        #expect(stageScript.contains("box-shadow: var(--epistemos-claude-composer-shadow) !important;"))
        #expect(stageScript.contains(".goose-epistemos .bg-background-tertiary"))
        #expect(stageScript.contains("Goose Web UI final flat lock zeroes active bg-background-tertiary rows."))
        #expect(stageScript.contains("[class~='bg-[var(--epistemos-accent)]']"))
        #expect(stageScript.contains("color: var(--color-text-inverse) !important;"))
        #expect(stageScript.contains("bg-background-secondary/70"))
        #expect(stageScript.contains("bg-background-primary/40"))
        #expect(stageScript.contains("bg-background-primary/54 pb-2"))
        #expect(stageScript.contains("bg-background-primary/54 p-3"))
        #expect(stageScript.contains("bg-\\[var(--epistemos-accent)\\]/12"))
        #expect(stageScript.contains("focus:bg-background-secondary/72 focus:outline-none focus:ring-0"))
        #expect(stageScript.contains("focus-visible:bg-[var(--epistemos-accent)]/10 focus-visible:ring-0"))
        #expect(stageScript.contains("rounded-\\[9px\\] p-1 space-y-0.5"))
        #expect(stageScript.contains("select__menu z-\\[9999\\] absolute overflow-hidden"))
        #expect(stageScript.contains("rounded-\\[11px\\] bg-background-primary/54"))
        #expect(stageScript.contains("min-h-\\[128px\\] overflow-hidden bg-background-primary/54"))
        #expect(stageScript.contains("absolute -bottom-2 right-2 whitespace-nowrap rounded-\\[8px\\] bg-background-secondary/72"))
        #expect(stageScript.contains("mt-2 flex flex-wrap gap-2 bg-background-primary/24 p-4"))
        #expect(stageScript.contains("rounded-\\[10px\\] bg-background-secondary/56 object-cover"))
        #expect(stageScript.contains("rounded-\\[10px\\] bg-background-secondary/56 px-3 py-2"))
        #expect(stageScript.contains("rounded-\\[8px\\] bg-background-primary/70 text-xs font-mono"))
        #expect(stageScript.contains("bg-background-danger/35"))
        #expect(stageScript.contains("return 'bg-background-success';"))
        #expect(stageScript.contains("absolute -right-0.5 -top-0.5 h-2 w-2 rounded-full"))
        #expect(stageScript.contains("rounded-full bg-background-success"))
        #expect(stageScript.contains("rounded-\\[12px\\] bg-background-warning/55"))
        #expect(stageScript.contains("min-h-9 rounded-\\[8px\\] px-3 py-2"))
        #expect(stageScript.contains("rounded-\\[9px\\] bg-background-secondary/56"))
        #expect(stageScript.contains("bg-background-success/55 text-text-success"))
        #expect(stageScript.contains("rounded-[8px] bg-background-primary/60"))
        #expect(stageScript.contains("bg-background-secondary/56 p-1"))
        #expect(stageScript.contains("rounded-\\[12px\\] bg-background-primary/42 px-4 py-2.5"))
        #expect(stageScript.contains("rounded-\\[8px\\] bg-background-secondary/60 px-2 py-1"))
        #expect(stageScript.contains("rounded-\\[10px\\] bg-background-warning/35 px-4 py-1.5"))
        #expect(stageScript.contains("bg-background-primary/54 hover:bg-background-secondary/56"))
        #expect(stageScript.contains("rounded-\\[8px\\] bg-background-primary/60 px-2 py-1 text-sm"))
        #expect(stageScript.contains("bg-background-primary/24"))
        #expect(stageScript.contains("goose-message-content overflow-hidden rounded-\\[12px\\] bg-background-primary/54"))
        #expect(stageScript.contains("bg-background-secondary/62 px-3 py-2 text-xs font-sans"))
        #expect(stageScript.contains("mx-auto my-2 w-full max-w-4xl rounded-\\[12px\\] bg-background-secondary/56"))
        #expect(stageScript.contains("w-full resize-none rounded-\\[10px\\] bg-background-primary/60 text-sm leading-relaxed"))
        #expect(stageScript.contains("mb-4 max-w-md rounded-\\[12px\\] bg-background-danger/35 p-4"))
        #expect(stageScript.contains("rounded-\\[8px\\] bg-background-secondary/56 px-4 py-2"))
        #expect(stageScript.contains("no-drag flex items-center gap-2 rounded-\\[8px\\] bg-background-primary/58"))
        #expect(stageScript.contains("flex items-center justify-between bg-background-primary/42 p-6"))
        #expect(stageScript.contains("w-full rounded-\\[10px\\] bg-background-primary/60 p-3 text-text-standard"))
        #expect(stageScript.contains("flex justify-end gap-3 bg-background-primary/42 p-6"))
        #expect(stageScript.contains("accent-\\[var(--epistemos-accent)\\]"))
        #expect(stageScript.contains("space-y-2 rounded-\\[12px\\] bg-background-secondary/44 p-3"))
        #expect(stageScript.contains("rounded-\\[12px\\] bg-background-secondary/56 px-4 py-3"))
        #expect(stageScript.contains("rounded-\\[12px\\] bg-background-secondary/32 px-4 py-3"))
        #expect(stageScript.contains("w-\\[900px\\].*rounded-\\[14px\\] bg-background-primary/92"))
        #expect(stageScript.contains("w-\\[800px\\].*rounded-\\[14px\\] bg-background-primary/92"))
        #expect(stageScript.contains("rounded-\\[10px\\] bg-background-secondary/60"))
        #expect(stageScript.contains("w-full cursor-pointer rounded-\\[10px\\] p-3 transition-colors"))
        #expect(stageScript.contains("mt-3 rounded-\\[12px\\] bg-background-secondary/44 p-3"))
        #expect(stageScript.contains("rounded-\\[12px\\] bg-background-primary/34 px-3 py-2"))
        #expect(stageScript.contains("rounded-\\[10px\\] bg-background-danger/35 p-3 text-sm text-text-danger"))
        #expect(stageScript.contains("w-screen h-screen bg-transparent"))
        #expect(stageScript.contains("relative flex h-full w-full flex-col overflow-hidden bg-transparent"))
        #expect(stageScript.contains("bg-background-primary/58 px-6 pb-5 pt-14"))
        #expect(stageScript.contains("ep-native-header-band flex flex-col rounded-[16px] bg-background-primary/42 p-4"))
        #expect(stageScript.contains("rounded-[10px] bg-background-danger/28 p-3"))
        #expect(stageScript.contains("goose-message-tool mt-1 rounded-\\[12px\\] bg-background-primary/54"))
        #expect(stageScript.contains("rounded-\\[8px\\] bg-background-secondary/44 px-2 py-1.5"))
        #expect(stageScript.contains("ml-3 rounded-\\[8px\\] bg-background-secondary/40 px-3 py-1"))
        #expect(stageScript.contains("rounded-\\[10px\\] bg-background-primary/60 p-3"))
        #expect(stageScript.contains("min-h-0 overflow-hidden rounded-\\[12px\\] bg-background-secondary/54"))
        #expect(stageScript.contains("flex shrink-0 items-center bg-background-primary/70 px-3"))
        #expect(stageScript.contains("ep-pixel flex items-center gap-1"))
        #expect(stageScript.contains("epistemos-acp-session-mode-setting"))
        #expect(stageScript.contains("saveAcpSessionMode(sessionId, newMode)"))
        #expect(stageScript.contains("epistemos-acp-next-session-mode-default"))
        #expect(stageScript.contains("epistemos-acp-new-session-mode-default"))
        #expect(stageScript.contains("gooseMode: configuredGooseMode"))
        #expect(stageScript.contains("useChatContext()"))
        #expect(stageScript.contains("epistemos-acp-standalone-app-session"))
        #expect(stageScript.contains("getConfiguredGooseExtensions()"))
        #expect(stageScript.contains("gooseExtensionName(entry.extension) === extensionName"))
        #expect(stageScript.contains("acpChatSessionController.createSession(workingDir, appExtensions)"))
        #expect(stageScript.contains("epistemos-acp-standalone-app-session-cleanup"))
        #expect(stageScript.contains("epistemos-acp-permission-tools-list"))
        #expect(stageScript.contains("listAcpSessionTools(sessionId, extensionName)"))
        #expect(stageScript.contains("epistemos-acp-permission-save-unavailable"))
        #expect(stageScript.contains("permissionEditingUnavailable"))
        #expect(stageScript.contains("epistemos-acp-mcp-resource-read"))
        #expect(stageScript.contains("epistemos-acp-mcp-tool-call"))
        #expect(stageScript.contains("readAcpSessionResource(sessionId, resourceUri, extensionName)"))
        #expect(stageScript.contains("callAcpSessionTool(sessionId, fullToolName, args || {})"))
        #expect(stageScript.contains("epistemos-acp-disable-mcp-app-sampling-rest"))
        #expect(stageScript.contains("MCP app sampling is not available through Goose ACP yet"))
        #expect(stageScript.contains("epistemos-acp-skip-mcp-app-sampling-credentials"))
        #expect(stageScript.contains("epistemos-acp-disable-mcp-ui-proxy-rest"))
        #expect(stageScript.contains("epistemos-acp-hide-rest-free-onboarding"))
        #expect(stageScript.contains("USE_ACP_CHAT ? OWN_PROVIDER : null"))
        #expect(stageScript.contains("!USE_ACP_CHAT && selectedPath === FREE_OPTIONS"))
        #expect(stageScript.contains("epistemos-acp-provider-modal-custom-delete"))
        #expect(stageScript.contains("epistemos-acp-canonical-model-info"))
        #expect(stageScript.contains("listAcpProviderModels(provider)"))
        #expect(stageScript.contains("entry.name === model || entry.resolved_model === model"))
        #expect(stageScript.contains("modelInfo.input_token_cost != null"))
        #expect(stageScript.contains("epistemos-acp-dictation-config-ui"))
        #expect(stageScript.contains("epistemos-acp-dictation-secret-save-ui"))
        #expect(stageScript.contains("epistemos-acp-dictation-secret-delete-ui"))
        #expect(stageScript.contains("voice_dictation_provider: 'voiceDictationProvider'"))
        #expect(stageScript.contains("voice_dictation_preferred_mic: 'voiceDictationPreferredMic'"))
        #expect(stageScript.contains("epistemos-acp-dictation-models-list"))
        #expect(stageScript.contains("epistemos-acp-dictation-models-list-ui"))
        #expect(stageScript.contains("epistemos-acp-dictation-model-download-ui"))
        #expect(stageScript.contains("readAcpDictationModelDownloadProgress(modelId)"))
        #expect(stageScript.contains("epistemos-acp-dictation-model-delete-ui"))
        #expect(stageScript.contains("epistemos-acp-dictation-transcribe"))
        #expect(stageScript.contains("epistemos-acp-dictation-config-hook"))
        #expect(stageScript.contains("transcribeAcpDictation(base64, 'audio/wav', prov)"))
        #expect(stageScript.contains("epistemos-acp-huggingface-sign-in-prompt"))
        #expect(stageScript.contains("readAcpProviderConfigStatuses([HUGGINGFACE_PROVIDER])"))
        #expect(stageScript.contains("authenticateAcpProviderConfig(HUGGINGFACE_PROVIDER)"))
        #expect(stageScript.contains("epistemos-acp-disable-nostr-session-links"))
        #expect(stageScript.contains("const [nostrEnabled, setNostrEnabled] = useState(!USE_ACP_CHAT);"))
        #expect(stageScript.contains("setNostrEnabled(false); // epistemos-acp-disable-nostr-session-links"))
        #expect(stageScript.contains("epistemos-acp-renderer-telemetry-config"))
        #expect(stageScript.contains("readAcpProviderConfigValue(TELEMETRY_CONFIG_KEY)"))
        #expect(stageScript.contains("telemetryValue === 'true'"))
        #expect(stageScript.contains("epistemos-acp-hide-session-sharing"))
        #expect(stageScript.contains("const [tunnelDisabled, setTunnelDisabled] = useState(USE_ACP_CHAT);"))
        #expect(stageScript.contains("sharing: USE_ACP_CHAT ? 'models' : 'sharing'"))
        #expect(stageScript.contains("epistemos-acp-navigation-active-session"))
        #expect(stageScript.contains("export async function acpGetSessionListItem"))
        #expect(stageScript.contains("client.goose.sessionInfo_unstable({ sessionId })"))
        #expect(stageScript.contains("acpGetSessionListItem(activeSessionId)"))
        #expect(stageScript.contains("Goose Web UI navigation hook still calls REST getSession for active sessions."))
        #expect(stageScript.contains("epistemos-acp-session-details-route-to-chat"))
        #expect(stageScript.contains("epistemos-acp-hide-prompts-settings"))
        #expect(stageScript.contains("prompts: USE_ACP_CHAT ? 'models' : 'prompts'"))
        #expect(stageScript.contains("epistemos-acp-hide-session-history-sharing"))
        #expect(stageScript.contains("setCanShare(false); // epistemos-acp-hide-session-history-sharing"))
        #expect(stageScript.contains("epistemos-acp-stdio-extension-secret-env-values"))
        #expect(stageScript.contains("epistemos-acp-stdio-extension-server-env"))
        #expect(stageScript.contains("epistemos-acp-stdio-extension-secret-store-via-config"))
        #expect(stageScript.contains("epistemos-acp-block-http-extension-secret-env"))
        #expect(stageScript.contains("epistemos-acp-block-http-extension-secret-submit"))
        #expect(stageScript.contains("epistemos-acp-hide-security-settings"))
        #expect(stageScript.contains("epistemos-acp-telemetry-native-settings"))
        #expect(!stageScript.contains("epistemos-acp-hide-telemetry-settings"))
        #expect(stageScript.contains("epistemos-acp-hide-local-inference-settings"))
        #expect(stageScript.contains("epistemos-acp-hide-local-model-settings"))
        #expect(stageScript.contains("!USE_ACP_CHAT && currentProvider === 'local' && currentModel"))
        #expect(stageScript.contains("!USE_ACP_CHAT && isLocalModelSettingsOpen && currentModel"))
        #expect(stageScript.contains("epistemos-acp-hide-generic-config-settings"))
        #expect(stageScript.contains("epistemos-acp-defaults-reset-unavailable"))
        #expect(stageScript.contains("epistemos-acp-hide-reset-provider-settings"))

        let support = try loadMirroredSourceTextFile("Epistemos/Goose/GooseWebSurfaceSupport.swift")
        #expect(support.contains("nativeFeelScript(theme: theme)"))
        #expect(support.contains("--color-ring-primary: \\(accent) !important;"))
        #expect(support.contains("--epistemos-accent: \\(accent) !important;"))
        #expect(support.contains("document.documentElement.dataset.epistemosTheme"))
        #expect(!support.contains("EPISTEMOS_GOOSE_NATIVE_ROUTES"))
        #expect(!support.contains("epistemos.goose.nativeRoutes"))

    }
}

@Suite("Goose provider/defaults ACP data-source parity", .serialized)
@MainActor
struct GooseProviderDefaultsLiveParityTests {
    /// Goose's product path is WebView-only, but provider/model/default data must still come from
    /// live ACP methods rather than a Swift-maintained roster.
    @Test("live ACP providers/list + defaults/read remain resolvable (no hardcoded roster)")
    func gooseProviderDefaultsReachLiveParity() async throws {
        try await withLiveGooseACPClient(proofName: "goose-provider-defaults-parity") { _, _, client, _ in
            _ = try await withLiveTimeout(
                seconds: 12,
                description: "ACP initialize for Goose provider/defaults parity",
                onTimeout: { await client.close() },
                operation: { try await client.initialize() }
            )

            let inventory = try await withLiveTimeout(
                seconds: 20,
                description: "providers/list inventory (Goose web Models source)",
                onTimeout: { await client.close() },
                operation: { try await client.listGooseProviderInventory() }
            )
            #expect(!inventory.isEmpty, "Goose provider inventory must not be empty.")
            #expect(inventory.contains { !$0.models.isEmpty },
                    "No provider exposes inline models through providers/list.")

            let defaults = try await withLiveTimeout(
                seconds: 20,
                description: "defaults/read (Goose current model selection)",
                onTimeout: { await client.close() },
                operation: { try await client.readGooseDefaults() }
            )
            if let defaultProviderId = defaults.providerId {
                #expect(inventory.contains { $0.providerId == defaultProviderId },
                        "Default provider \(defaultProviderId) is not present in providers/list inventory.")
            }
        }
    }
}
