import Foundation
import Testing

@testable import Epistemos

@Suite("HTML Workspace source guards", .serialized)
nonisolated struct HTMLWorkspaceSourceGuardTests {
    private var repoRootURL: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
    }

    private func repoFileExists(_ relativePath: String) -> Bool {
        FileManager.default.fileExists(atPath: repoRootURL.appendingPathComponent(relativePath).path)
    }

    @Test("preview uses offline WKWebView defaults and no implicit app bridge")
    func previewUsesOfflineWKWebViewDefaults() throws {
        let previewSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspacePreviewView.swift")
        let previewDocumentSource = try loadMirroredSourceTextFile("Epistemos/Models/HTMLWorkspacePreviewDocument.swift")
        let packageSource = try loadMirroredSourceTextFile("Epistemos/Models/HTMLWorkspacePackage.swift")

        #expect(previewSource.contains("WKWebsiteDataStore.nonPersistent()"))
        #expect(previewSource.contains("loadHTMLString"))
        #expect(previewSource.contains("setURLSchemeHandler"))
        #expect(previewSource.contains("HTMLWorkspaceLocalResourceScheme.scheme"))
        #expect(previewSource.contains("HTMLWorkspacePreviewURL.baseURL"))
        #expect(previewSource.contains("HTMLWorkspacePreviewURLSchemeHandler"))
        #expect(previewSource.contains("resourceResponse(for:"))
        #expect(previewSource.contains("HTMLWorkspacePackageResources.resource(for: resourcePath, in: package)"))
        #expect(previewSource.contains("HTMLWorkspacePackageResources.packageRouteName(for: resourcePath)"))
        #expect(previewSource.contains("routeName == HTMLWorkspacePackageEntry.indexHTML || package.routes[routeName] != nil"))
        #expect(previewSource.contains("routeName: routeName == HTMLWorkspacePackageEntry.indexHTML ? nil : routeName"))
        #expect(previewSource.contains("themeGuardCSSOverride: themeGuardCSSOverride"))
        #expect(previewSource.contains("components[0] == HTMLWorkspacePackageEntry.routes"))
        #expect(previewSource.contains("components[1] == HTMLWorkspacePackageEntry.assets"))
        #expect(previewSource.contains("assetShellHash(for: package)"))
        #expect(!previewSource.contains("baseURL: nil"))
        #expect(previewSource.contains("allowNetwork == false"))
        #expect(previewSource.contains("decisionHandler(.cancel)"))
        #expect(previewSource.contains("allowedNetworkSchemes"))
        #expect(previewSource.contains("\"http\", \"https\""))
        #expect(previewSource.contains("syncSafeAPIHandler"))
        #expect(previewSource.contains("safeAPIEnabled"))
        #expect(previewSource.contains("HTMLWorkspaceSafeAPI.messageHandlerName"))
        #expect(previewSource.contains("HTMLWorkspaceSafeAPI.Command.fromMessageBody"))
        #expect(previewSource.contains("HTMLWorkspaceSafeAPI.diagnosticMessage"))
        #expect(previewSource.contains("HTMLWorkspaceSafeAPI.sourceName"))
        #expect(previewSource.contains("App bridge denied: sandbox gate is off"))
        #expect(previewSource.contains("App bridge rejected malformed message"))
        #expect(previewSource.contains("requestAppBridgeProbe"))
        #expect(previewSource.contains("appBridgeProbeScript"))
        #expect(previewSource.contains("HTMLWorkspaceApp"))
        #expect(previewSource.contains("manual probe"))
        #expect(previewSource.contains("app.request('ping', 'manual probe'"))
        #expect(previewSource.contains("roundtrip:"))
        #expect(!previewSource.contains("HTMLWorkspaceSafeAPI.deferredDiagnosticMessage"))
        #expect(previewSource.contains("message.name == HTMLWorkspaceSafeAPI.messageHandlerName"))
        #expect(previewSource.contains("HTMLWorkspaceConsoleBridge.enabled"))
        #expect(previewSource.contains("HTMLWorkspaceConsoleBridge.injectionScript"))
        #expect(previewSource.contains("onConsoleError != nil"))
        #expect(previewSource.contains("requestConsoleProbe"))
        #expect(previewSource.contains("consoleProbeScript"))
        #expect(previewSource.contains("HTML Workspace log probe"))
        #expect(previewSource.contains("HTML Workspace info probe"))
        #expect(previewSource.contains("HTML Workspace console probe"))
        #expect(previewSource.contains("HTML Workspace error probe"))
        #expect(previewSource.contains("HTML Workspace window error probe"))
        #expect(previewSource.contains("HTML Workspace rejection probe"))
        #expect(previewSource.contains("requestPythonProbe"))
        #expect(previewSource.contains("pendingPythonProbeNonce"))
        #expect(previewSource.contains("Python runtime manual probe"))
        #expect(previewSource.contains("pythonProbeScript"))
        #expect(previewSource.contains("HTML Workspace Python probe"))
        #expect(previewSource.contains("Python runtime probe:"))
        #expect(previewSource.contains("var routeName: String? = nil"))
        #expect(previewSource.contains("routeName: routeName"))
        #expect(previewSource.contains("routeName ?? HTMLWorkspacePackageEntry.indexHTML"))
        #expect(previewSource.contains("HTMLWorkspaceInspectorBridge.installScript"))
        #expect(previewSource.contains("HTMLWorkspaceInspectorBridge.probeScript"))
        #expect(previewSource.contains("requestInspectorProbe"))
        #expect(previewSource.contains("DOM inspector probe:"))
        #expect(previewSource.contains("onElementInspection"))
        #expect(previewDocumentSource.contains("nonisolated public enum HTMLWorkspacePreviewDocument"))
        #expect(previewDocumentSource.contains("HTMLWorkspacePreviewRuntime.script"))
        #expect(previewDocumentSource.contains("HTMLWorkspaceSafeAPI.messageHandlerName"))
        #expect(previewDocumentSource.contains("Object.defineProperty(window, 'HTMLWorkspaceApp'"))
        #expect(!packageSource.contains("nonisolated public enum HTMLWorkspacePreviewDocument"),
                "Preview rendering/runtime JS must stay out of the package model file.")
        let bridgeSource = try loadMirroredSourceTextFile("Epistemos/Engine/HTMLWorkspaceRuntimeBridges.swift")
        #expect(bridgeSource.contains("function classesFor(node, limit)"))
        #expect(bridgeSource.contains("classes: classesFor(node, 12)"))
        #expect(bridgeSource.contains("bounded(node.id, 128)"))
        #expect(bridgeSource.contains("__epistemosInspectElement"))
        #expect(bridgeSource.contains("__epistemosInspectorSelected"))
        #expect(bridgeSource.contains("data-epistemos-inspect"))
        #expect(bridgeSource.contains("data-epistemos-inspected"))
        #expect(previewSource.contains("canPatchDataOnly"))
        #expect(previewSource.contains("patchDataJSON"))
        #expect(previewSource.contains("evaluateJavaScript(script)"))
        #expect(previewSource.contains("onDOMSnapshot"))
        #expect(previewSource.contains("liveDOMSnapshotScript"))
        #expect(previewSource.contains("refreshLiveDOMSnapshot"))
        #expect(previewSource.contains("didFinish navigation"))
        #expect(previewSource.contains("__epistemosReplaceWorkspaceData"))
        #expect(previewSource.contains("lastRenderedShellIdentity"))
        #expect(previewSource.contains("EpdocWebViewShared.notifyWebViewCreated()"))
        #expect(previewSource.contains("EpdocWebViewShared.notifyWebViewDismantled()"))
        #expect(previewSource.components(separatedBy: "addUserScript(").count == 2,
                "Preview may install exactly one persistent user script: console capture. DOM inspection is toggled with evaluateJavaScript so it can be disabled.")
        #expect(previewSource.contains("source: HTMLWorkspaceConsoleBridge.injectionScript"),
                "The only persistent preview user script should be console capture.")
        #expect(!previewSource.contains("source: HTMLWorkspaceInspectorBridge.installScript"),
                "DOM inspector installScript must not be a persistent WKUserScript; it must remain runtime-toggleable.")
        #expect(previewSource.contains("webView.evaluateJavaScript(HTMLWorkspaceInspectorBridge.installScript)"))
        #expect(previewSource.contains("guard !isLoadingPreview, !webView.isLoading else { return }"))
        #expect(previewSource.contains("syncInspectorHandler(for: webView, allowScriptInstall: false)"))
        #expect(previewSource.contains("syncInspectorHandler(for: webView, allowScriptInstall: didLoadPage)"))
        #expect(previewSource.contains("if allowScriptInstall, shouldInstall, !isLoadingPreview, !webView.isLoading"))
        #expect(previewSource.contains("message.name == HTMLWorkspaceInspectorBridge.messageHandlerName,\n               isElementInspectorEnabled"))
        // Security gate: the app-bridge handler installs ONLY when BOTH the user-enabled flag AND the
        // per-package sandbox policy allow it — the sole barrier against arbitrary rendered HTML
        // obtaining an app bridge. Dropping either condition is a real privilege-escalation hole, so
        // pin the conjunction.
        #expect(previewSource.contains("safeAPIEnabled && package.manifest.sandboxPolicy.allowAppBridge"),
                "App-bridge install must require BOTH safeAPIEnabled AND the package's allowAppBridge sandbox policy.")
        // The app-bridge handler is torn down on detach — no leaked WKScriptMessageHandler across
        // workspace swaps (an installed-but-orphaned bridge is both a leak and a latent surface).
        #expect(previewSource.contains("removeScriptMessageHandler"))
        #expect(previewSource.contains("messageHandlerInstalled = false"))
        #expect(previewSource.contains("func detach(from webView: WKWebView) {"))
        #expect(previewSource.contains("isDetached = true"))
        #expect(previewSource.contains("pendingRender = nil"))
        #expect(previewSource.contains("webView.navigationDelegate = nil"))
        #expect(previewSource.contains("lastRenderedDataJSON = nil\n            webView.stopLoading()"))
    }

    @Test("HTML workspace exposes explicit attachment helpers")
    func htmlWorkspaceExposesExplicitAttachmentHelpers() throws {
        let chatTypes = try loadMirroredSourceTextFile("Epistemos/Models/ChatTypes.swift")
        let helpers = try loadMirroredSourceTextFile("Epistemos/Views/Chat/NotesMentionDropdown.swift")

        #expect(chatTypes.contains("case htmlWorkspace"))
        #expect(helpers.contains("htmlWorkspaceAttachment("))
        #expect(helpers.contains("htmlworkspace://"))
    }

    @Test("HTML Workspace is a separate document surface, not an Epdoc overload")
    func workspaceIsSeparateFromEpdoc() throws {
        let documentSource = try loadMirroredSourceTextFile("Epistemos/Engine/HTMLWorkspaceDocument.swift")
        let editorSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceEditorView.swift")
        let epdocSlash = try loadMirroredSourceTextFile("js-editor/src/extensions/slash-menu.ts")

        #expect(documentSource.contains("HTMLWorkspaceDocument: NSDocument"))
        #expect(documentSource.contains("com.epistemos.html-workspace"))
        #expect(documentSource.contains("HTMLWorkspaceDocumentThemedRoot"))
        #expect(documentSource.contains(".preferredColorScheme(ui.preferredColorScheme)"))
        #expect(editorSource.contains("HTMLWorkspacePreviewView("))
        #expect(editorSource.contains("MarkEditCodeEditorRepresentable("))
        #expect(!editorSource.contains("HTMLWorkspaceCodeEditor("))
        #expect(!editorSource.contains("TextEditor("))
        #expect(!repoFileExists("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceCodeEditor.swift"))
        #expect(epdocSlash.contains("id: 'html-workspace'"))
        #expect(!epdocSlash.contains("html-dom"))
    }

    @Test("existing HTML Workspace selection avoids the generic AppKit open path")
    func existingWorkspaceSelectionUsesHTMLWorkspaceOpenHelper() throws {
        let sidebarSource = try loadMirroredSourceTextFile("Epistemos/Views/Notes/NotesSidebar.swift")
        let graphSource = try loadMirroredSourceTextFile("Epistemos/Views/Graph/GraphWorkspaceContainer.swift")
        let controllerSource = try loadMirroredSourceTextFile("Epistemos/App/EpistemosDocumentController.swift")
        let documentSource = try loadMirroredSourceTextFile("Epistemos/Engine/HTMLWorkspaceDocument.swift")

        #expect(controllerSource.contains("func openHTMLWorkspaceDocument(at url: URL) throws -> HTMLWorkspaceDocument"))
        #expect(controllerSource.contains("FileWrapper(url: standardizedURL, options: [.immediate])"))
        #expect(controllerSource.contains("document.loadOpenedPackage(package, fileURL: standardizedURL)"))
        #expect(documentSource.contains("func loadOpenedPackage(_ package: HTMLWorkspacePackage, fileURL: URL)"))
        #expect(sidebarSource.contains("url.pathExtension == \"htmlworkspace\""))
        #expect(sidebarSource.contains("openHTMLWorkspaceDocument(at: url)"))
        #expect(graphSource.contains("openHTMLWorkspaceDocument(at: url)"))
    }

    @Test("editor preview updates are debounced and diagnostics are collapsible")
    func editorDebouncesPreviewAndCollapsesDiagnostics() throws {
        let editorSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceEditorView.swift")
        let panelsSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceEditorPanels.swift")
        let supportSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceEditorSupport.swift")
        let importerSource = try loadMirroredSourceTextFile("Epistemos/Models/HTMLWorkspaceHTMLImporter.swift")

        #expect(editorSource.contains("previewPackage"))
        #expect(editorSource.contains("previewUpdateTask"))
        #expect(editorSource.contains("Task.sleep"))
        #expect(editorSource.contains("HTMLWorkspacePreviewView("))
        #expect(editorSource.contains("package: previewPackage"))
        #expect(editorSource.contains("@State private var previewRouteName"))
        #expect(editorSource.contains("routeName: previewRouteName"))
        #expect(panelsSource.contains("Picker(\"Route\", selection: $previewRouteName)"))
        #expect(panelsSource.contains("Text(\"index.html\").tag(String?.none)"))
        #expect(editorSource.contains("HTMLWorkspacePDFExporter.export"))
        #expect(editorSource.contains("importHTML()"))
        #expect(editorSource.contains("exportHTML()"))
        #expect(editorSource.contains(#"Button("Export Site Folder""#))
        #expect(editorSource.contains("exportSiteFolder()"))
        #expect(editorSource.contains("statusText = summary.statusText"))
        #expect(supportSource.contains("enum HTMLWorkspaceSiteFolderExporter"))
        #expect(supportSource.contains("struct HTMLWorkspaceSiteFolderExportSummary"))
        #expect(supportSource.contains("route-relative asset mirror"))
        #expect(supportSource.contains("HTMLWorkspacePackage.validateRoutes(package.routes)"))
        #expect(supportSource.contains("HTMLWorkspacePackage.validateAssets(package.assets)"))
        #expect(supportSource.contains("routeName: routeName"))
        #expect(editorSource.contains("resourceMode: .inlinePackageAssets"))
        #expect(editorSource.contains("HTML saved (index route only)"))
        #expect(editorSource.contains("PDF saved (index route only)"))
        #expect(editorSource.contains("patchExampleOperation(for: pane)"))
        #expect(editorSource.contains(#""type":"setRoute""#))
        #expect(editorSource.contains("previewRenderIdentity"))
        #expect(editorSource.contains("HTMLWorkspacePreviewIdentity.viewIdentity(for: previewPackage)"))
        #expect(editorSource.contains("themeIdentity: workspaceThemeIdentity"))
        #expect(editorSource.contains("HTMLWorkspaceRegeneratePreview.loadingPackage"))
        #expect(editorSource.contains("HTMLWorkspaceRegeneratePreview.candidatePackage"))
        #expect(editorSource.contains("restorePreviewAfterRegenerate()"))
        #expect(editorSource.contains("@State private var pythonProbeNonce"))
        #expect(editorSource.contains(#"Button("Test Python Runtime""#))
        #expect(editorSource.contains("private func testPythonRuntime()"))
        #expect(editorSource.contains("currentHTMLWorkspaceDocument()"))
        #expect(editorSource.contains("document.save(nil)"))
        #expect(editorSource.contains("failedStatus("))
        #expect(editorSource.contains("error.localizedDescription"))
        #expect(importerSource.contains("generatedScriptIDs"))
        #expect(importerSource.contains(#""epistemos-workspace-runtime""#))
        #expect(importerSource.contains("scriptBodies(in: source)"))
        #expect(importerSource.contains("shouldImportScript(type:"))
        #expect(importerSource.contains(#"normalized == "module""#))
        #expect(editorSource.contains(".onChange(of: colorScheme)"))
        #expect(panelsSource.contains("DisclosureGroup"))
        #expect(panelsSource.contains("Console"))
        #expect(editorSource.contains("bridgeStatusText"))
        #expect(editorSource.contains(#""Bridge enabled""#))
        #expect(editorSource.contains("generationProvenanceText"))
        #expect(panelsSource.contains(#"inspectorRow("Provenance""#))
        #expect(editorSource.contains("@State private var liveDOMSnapshot"))
        #expect(editorSource.contains("onDOMSnapshot:"))
        #expect(editorSource.contains("domSnapshot.source.label"))
        #expect(editorSource.contains(#""Live DOM Outline""#))
        #expect(editorSource.split(separator: "\n", omittingEmptySubsequences: false).count < 1_750)
    }

    @Test("HTML Workspace panels use Epistemos theme tokens instead of raw status colors")
    func htmlWorkspacePanelsUseThemeTokens() throws {
        let editorSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceEditorView.swift")
        let panelsSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceEditorPanels.swift")

        #expect(editorSource.contains("headerFill: headerFill,\n            theme: workspaceTheme"))
        #expect(editorSource.contains("panelFill: panelFill,\n            theme: workspaceTheme,\n            onClear: clearConsole"))
        #expect(editorSource.contains("panelFill: panelFill,\n            theme: workspaceTheme,\n            onCopySelector: copyInspectorSelector"))
        #expect(editorSource.contains("workspaceTheme.textTertiary"))
        #expect(editorSource.contains("workspaceMetricFill"))
        #expect(!editorSource.contains("toolbar\n            Divider()\n            workspaceBody"))
        #expect(!editorSource.contains("sourceRail\n                    .frame(width: 118)\n                Divider()"))
        #expect(!editorSource.contains("sourceHeader\n                    Divider()"))
        #expect(!editorSource.contains("previewHeader\n                Divider()"))
        #expect(!editorSource.contains(".foregroundStyle(.secondary)"))
        #expect(!editorSource.contains(".background(.quaternary"))
        #expect(panelsSource.contains("let theme: EpistemosTheme"))
        #expect(panelsSource.contains("theme.textTertiary"))
        #expect(panelsSource.contains("theme.warning"))
        #expect(panelsSource.contains("theme.success"))
        #expect(panelsSource.contains("theme.error"))
        #expect(panelsSource.contains("fieldBackground"))
        #expect(!panelsSource.contains("Color.red"))
        #expect(!panelsSource.contains("Color.orange"))
        #expect(!panelsSource.contains(".foregroundStyle(.red"))
        #expect(!panelsSource.contains(".foregroundStyle(.orange"))
        #expect(!panelsSource.contains(".foregroundStyle(.green"))
        #expect(!panelsSource.contains(".foregroundStyle(.secondary"))
        #expect(!panelsSource.contains(".background(.quaternary"))
        #expect(!panelsSource.contains("Divider()"))
    }

    @Test("HTML Workspace live data feed is explicit and provenance-visible")
    func htmlWorkspaceLiveDataFeedIsExplicitAndProvenanceVisible() throws {
        let packageSource = try loadMirroredSourceTextFile("Epistemos/Models/HTMLWorkspacePackage.swift")
        let documentSource = try loadMirroredSourceTextFile("Epistemos/Engine/HTMLWorkspaceDocument.swift")
        let editorSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceEditorView.swift")
        let feedSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceDataFeed.swift")
        let templateSource = try loadMirroredSourceTextFile("Epistemos/Models/HTMLWorkspaceTemplates.swift")
        let hostSource = try loadMirroredSourceTextFile("Epistemos/Views/Workspace/ArtifactHostView.swift")

        #expect(packageSource.contains("struct HTMLWorkspaceDataFeed"))
        #expect(packageSource.contains("HTMLWorkspaceDataFeedJSONEnvelope"))
        #expect(packageSource.contains("case dataFeed = \"data_feed\""))
        #expect(templateSource.contains("applyVaultSearchDashboardTemplate"))
        #expect(templateSource.contains("HTMLWorkspaceDataFeedJSONEnvelope.staleDataJSON"))
        #expect(templateSource.contains("renderVaultResults"))
        #expect(templateSource.contains("htmlworkspace:datachange"))
        #expect(documentSource.contains("notifyPackageDidChange()"))
        #expect(documentSource.contains(".htmlWorkspacePackageDidChange"))
        #expect(editorSource.contains(".htmlWorkspaceDataFeed(package: $package, statusText: $statusText)"))
        #expect(editorSource.contains("HTMLWorkspaceDataFeedStatusStrip(package: package, compact: true)"))
        #expect(editorSource.contains("Configure Vault Search Feed"))
        #expect(editorSource.contains("configureVaultSearchFeed()"))
        #expect(editorSource.contains("package.isStarterTemplateContent"))
        #expect(editorSource.contains("applyVaultSearchDashboardTemplate"))
        #expect(editorSource.contains("HTMLWorkspaceDataFeed.vaultSearch"))
        #expect(editorSource.contains("HTMLWorkspaceDataFeedJSONEnvelope.staleDataJSON"))
        #expect(editorSource.contains("package.manifest.dataFeed = nil"))
        #expect(editorSource.contains(#""assets/\($0.key)"#))
        #expect(feedSource.contains("VaultSyncService.searchFullAsync"))
        #expect(feedSource.contains("NotificationCenter.default.publisher(for: .searchIndexDidUpdate)"))
        #expect(feedSource.contains("HTMLWorkspaceDataFeedRenderer.staleRender"))
        #expect(feedSource.contains(#""VaultSyncService.searchFullAsync""#))
        #expect(feedSource.contains(#"case epistemos = "_epistemos""#))
        #expect(feedSource.contains(#""stale":true"#) || feedSource.contains(#""stale": true"#))
        #expect(hostSource.contains("HTMLWorkspaceDataFeedStatusStrip(package: package)"))
        #expect(hostSource.contains(".htmlWorkspaceDataFeed(package: packageBinding, statusText: $dataFeedStatusText)"))
        #expect(hostSource.contains("setPackage(newPackage)"))
        #expect(hostSource.contains(".htmlWorkspacePackageDidChange"))
    }

    @Test("PDF export is timeout bounded on the macOS-26 WebPage API (no legacy WebKit NSView host)")
    func pdfExporterHasBoundedLoadAndCleanup() throws {
        let exporterSource = try loadMirroredSourceTextFile("Epistemos/Engine/HTMLWorkspacePDFExporter.swift")

        #expect(exporterSource.contains("HTMLWorkspacePDFExportError"))
        #expect(exporterSource.contains("loadTimeoutNanoseconds"))
        #expect(exporterSource.contains("loadTimedOut"))
        // Timeout must race the load stream; a passive deadline checked only on navigation events
        // still hangs if the WebPage stream stalls before emitting another event.
        #expect(exporterSource.contains("withThrowingTaskGroup(of: Void.self)"))
        #expect(exporterSource.contains("group.addTask {"))
        #expect(exporterSource.contains("waitForLoadFinished(page: page, html: html)"))
        #expect(exporterSource.contains("Task.sleep(nanoseconds: Self.loadTimeoutNanoseconds)"))
        #expect(exporterSource.contains("defer { group.cancelAll() }"))
        // macOS-26 SwiftUI WebKit migration: `WebPage` + a `NavigationDeciding` scheme allowlist (async policy,
        // not a delegate `decisionHandler`); content-sized PDF via `exported(as: .pdf(region: .rect(…)))`.
        #expect(exporterSource.contains("WebPage"))
        #expect(exporterSource.contains("NavigationDeciding"))
        #expect(exporterSource.contains("return .cancel"))
        #expect(exporterSource.contains("resourceMode: .inlinePackageAssets"))
        #expect(exporterSource.contains("exported(as: .pdf"))
        #expect(exporterSource.contains("height.isFinite"))
        // No legacy WebKit NSView host / delegate / dispatch-after paths survive the migration.
        #expect(!exporterSource.contains("WKWebView"))
        #expect(!exporterSource.contains("navigationDelegate"))
        #expect(!exporterSource.contains("DispatchQueue.main.asyncAfter"))
    }

    @Test("editor exposes data routes DOM assets and MarkEdit-backed source editing")
    func editorExposesDOMDataAssetsAndMarkEditBackedSourceEditing() throws {
        let editorSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceEditorView.swift")
        let supportSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceEditorSupport.swift")
        let markEditSource = try loadMirroredSourceTextFile("Epistemos/Views/Notes/MarkEditCoreEditorView.swift")

        #expect(supportSource.contains("case data"))
        #expect(supportSource.contains("case routes"))
        #expect(supportSource.contains("case dom"))
        #expect(supportSource.contains("case assets"))
        #expect(supportSource.contains("data.json"))
        #expect(supportSource.contains("routes/"))
        #expect(editorSource.contains("routeManifestText"))
        #expect(supportSource.contains("DOM Outline"))
        #expect(editorSource.contains("DocumentSourceRange.fullDocumentRange(for: sourceText(for: pane))"))
        #expect(!editorSource.contains("source.split(separator: \"\\n\", omittingEmptySubsequences: false).last"))
        #expect(editorSource.contains("MarkEditCodeEditorRepresentable("))
        #expect(supportSource.contains(#"case .html: "html""#))
        #expect(supportSource.contains(#"case .css: "css""#))
        #expect(supportSource.contains(#"case .js: "javascript""#))
        #expect(supportSource.contains(#"case .data: "json""#))
        #expect(editorSource.contains(#"@AppStorage("codeEditor.fontSize") private var sourceFontSize"#))
        #expect(editorSource.contains(#"@AppStorage("epistemos.codeEditor.showLineGutter") private var sourceShowLineGutter"#))
        #expect(markEditSource.contains("struct MarkEditCodeEditorRepresentable"))
        #expect(markEditSource.contains("mode: .code(language: language)"))
        #expect(markEditSource.contains("MarkEditCoreEditorBridge"))
    }

    @Test("package model uses requested file layout and guards traversal")
    func packageModelUsesMainJSAndPathGuards() throws {
        let packageSource = try loadMirroredSourceTextFile("Epistemos/Models/HTMLWorkspacePackage.swift")
        let previewDocumentSource = try loadMirroredSourceTextFile("Epistemos/Models/HTMLWorkspacePreviewDocument.swift")
        let resourceSource = try loadMirroredSourceTextFile("Epistemos/Models/HTMLWorkspacePackageResources.swift")
        let provenanceSource = try loadMirroredSourceTextFile("Epistemos/Models/HTMLWorkspaceGenerationProvenance.swift")
        let pythonRuntimeSource = try loadMirroredSourceTextFile("Epistemos/Engine/HTMLWorkspacePythonRuntime.swift")
        let routerSource = try loadMirroredSourceTextFile("Epistemos/Engine/HTMLWorkspacePatchRouter.swift")
        let supportSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceEditorSupport.swift")

        #expect(packageSource.contains("main.js"))
        #expect(packageSource.contains("data.json"))
        #expect(packageSource.contains(#"public static let routes = "routes""#))
        #expect(packageSource.contains("HTMLWorkspaceLocalResourceScheme"))
        #expect(packageSource.contains("contentSecurityPolicySource"))
        #expect(packageSource.contains("HTMLWorkspaceGenerationProvenance"))
        #expect(packageSource.contains("HTMLWorkspacePackageContentHasher"))
        #expect(packageSource.contains("generationProvenance"))
        #expect(packageSource.contains("generation_provenance"))
        #expect(packageSource.contains("producer: .agent"))
        #expect(packageSource.contains("HTMLWorkspaceGenerationProvenance.patchToolID"))
        #expect(packageSource.contains("reversibleSnapshot.name"))
        #expect(provenanceSource.contains("previous_content_hash"))
        #expect(provenanceSource.contains("reversible_snapshot_name"))
        #expect(provenanceSource.contains("generated_by_run"))
        #expect(provenanceSource.contains("html_workspace.patch"))
        #expect(provenanceSource.contains("displayText(currentContentHash:"))
        #expect(provenanceSource.contains(#""stale""#))
        #expect(resourceSource.contains("HTMLWorkspacePreviewResourceMode"))
        #expect(resourceSource.contains("case inlinePackageAssets"))
        #expect(resourceSource.contains("HTMLWorkspacePackageResources"))
        #expect(resourceSource.contains("packageWithInlineAssets"))
        #expect(resourceSource.contains("inlinePackageAssetReferences"))
        #expect(resourceSource.contains("packageRouteName"))
        #expect(resourceSource.contains("routeName: routeName"))
        #expect(resourceSource.contains("dataURL(for:"))
        #expect(resourceSource.contains("replaceDelimitedReference"))
        #expect(packageSource.contains("HTMLWorkspacePreviewTheme"))
        #expect(previewDocumentSource.contains("epistemos-theme-guard"))
        #expect(previewDocumentSource.contains("epistemos-font-face"))
        #expect(previewDocumentSource.contains("epistemos-theme-host"))
        #expect(previewDocumentSource.contains("HTMLWorkspacePreviewFonts"))
        #expect(previewDocumentSource.contains("MatrixtypeDisplay-9MyE5"))
        #expect(previewDocumentSource.contains("ChonkyPixels"))
        #expect(previewDocumentSource.contains("fontDataURL"))
        #expect(packageSource.contains("html[data-epistemos-theme] body :is(h1, h2, .workspace-title, [data-display-title])"))
        #expect(packageSource.contains("font-synthesis: none"))
        #expect(packageSource.contains("data-metric-value"))
        #expect(packageSource.contains("html[data-epistemos-theme] .metric-card strong"))
        #expect(supportSource.contains("background: var(--epistemos-workspace-bg) !important"))
        #expect(supportSource.contains("color: var(--epistemos-workspace-fg) !important"))
        #expect(packageSource.contains("body :is(main, section, article"))
        #expect(supportSource.contains("border-color: var(--epistemos-workspace-border)"))
        #expect(packageSource.contains("legacyScriptJS"))
        #expect(packageSource.contains("validatePackageFileName"))
        #expect(packageSource.contains("case replaceDataJSON"))
        #expect(packageSource.contains("case updateStyleRule"))
        #expect(packageSource.contains("case setRoute"))
        #expect(packageSource.contains("case removeRoute"))
        #expect(packageSource.contains("case addAsset"))
        #expect(packageSource.contains("case removeAsset"))
        #expect(packageSource.contains("case captureSnapshot"))
        #expect(packageSource.contains("case recordConsoleError"))
        #expect(packageSource.contains("case clearConsole"))
        #expect(!routerSource.contains("case clearConsole"))
        #expect(packageSource.contains("maxManifestBytes"))
        #expect(packageSource.contains("maxRouteCount"))
        #expect(packageSource.contains("maxRoutesTotalBytes"))
        #expect(packageSource.contains("maxAssetCount"))
        #expect(packageSource.contains("maxAssetsTotalBytes"))
        #expect(packageSource.contains("maxSnapshotsTotalBytes"))
        #expect(packageSource.contains("packageLimitExceeded"))
        #expect(packageSource.contains("validateAssets(updated.assets)"))
        #expect(packageSource.contains("validateSnapshots(updated.snapshots)"))
        #expect(packageSource.contains("!name.hasPrefix(\".\")"))
        #expect(packageSource.contains("CharacterSet.controlCharacters"))
        #expect(packageSource.contains("guard child.isRegularFile"))
        #expect(packageSource.contains("validateRoutes"))
        #expect(pythonRuntimeSource.contains("Bundle.main.url("))
        #expect(!pythonRuntimeSource.contains("Bundle.allBundles"))
        #expect(!pythonRuntimeSource.contains("Bundle.allFrameworks"))
        #expect(pythonRuntimeSource.contains("requiredResourceNames.allSatisfy"))
        #expect(pythonRuntimeSource.contains("static var missingRequiredResourceNames"))
        #expect(pythonRuntimeSource.contains("static var availabilityStatusText"))
        #expect(pythonRuntimeSource.contains("allowedResourceNames.contains(fileName)"))
        #expect(pythonRuntimeSource.contains("static let assetFingerprint"))
        #expect(pythonRuntimeSource.contains("Data(contentsOf: url)"))
        #expect(!pythonRuntimeSource.contains("attributesOfItem"))
        #expect(supportSource.contains("HTMLWorkspacePythonDemoScaffold"))
        #expect(supportSource.contains("window.HTMLWorkspace.python"))
        #expect(supportSource.contains("runtime.missingResources"))
        #expect(supportSource.contains("data-python-output"))
        #expect(packageSource.contains("HTMLWorkspaceDocumentReplacement"))
        #expect(packageSource.contains("case replaceDocument(HTMLWorkspaceDocumentReplacement)"))
        #expect(packageSource.contains("case setDataFeed(HTMLWorkspaceDataFeed?)"))
        #expect(packageSource.contains(#"error: "Feed pending""#))
        #expect(packageSource.contains("reversibleSnapshots(for:"))
        #expect(packageSource.contains(#""pre-replace-"#))
    }

    @Test("bundled Pyodide WASM is data-only for app packaging")
    func bundledPyodideWASMIsDataOnly() throws {
        let wasmURL = repoRootURL.appendingPathComponent("Epistemos/Resources/Pyodide/pyodide.asm.wasm")
        #expect(FileManager.default.fileExists(atPath: wasmURL.path))

        let attributes = try FileManager.default.attributesOfItem(atPath: wasmURL.path)
        let permissions = try #require(attributes[.posixPermissions] as? NSNumber).intValue

        #expect((permissions & 0o111) == 0, "Pyodide WASM must not be executable on disk.")
    }

    @Test("document surface exposes structured patch hooks without Epdoc internals")
    func documentExposesPatchHooks() throws {
        let documentSource = try loadMirroredSourceTextFile("Epistemos/Engine/HTMLWorkspaceDocument.swift")
        let bridgeSource = try loadMirroredSourceTextFile("Epistemos/Engine/EpdocEditorBridge.swift")
        let surfaceSource = try loadMirroredSourceTextFile("Epistemos/Models/DocumentSurface.swift")

        #expect(surfaceSource.contains("struct DocumentSurface"))
        #expect(surfaceSource.contains("enum DocumentSurfaceKind"))
        #expect(surfaceSource.contains("enum DocumentSurfacePane"))
        #expect(surfaceSource.contains("case routes"))
        #expect(surfaceSource.contains("struct DocumentSourceRange"))
        #expect(surfaceSource.contains("static func fullDocumentRange(for source: String)"))
        #expect(surfaceSource.contains(#"source.lastIndex(of: "\n")"#))
        #expect(surfaceSource.contains("enum DocumentSurfaceCapability"))
        #expect(documentSource.contains("applyPatch("))
        #expect(documentSource.contains("chatContextSnapshot("))
        #expect(documentSource.contains("generationProvenance: package.manifest.generationProvenance"))
        #expect(!documentSource.contains("EpdocDocument"))
        #expect(bridgeSource.contains("epistemos-doc"))
    }

    @Test("document save refuses starter template overwrite of existing workspaces")
    func documentSaveRefusesStarterTemplateOverwrite() throws {
        let documentSource = try loadMirroredSourceTextFile("Epistemos/Engine/HTMLWorkspaceDocument.swift")
        let packageSource = try loadMirroredSourceTextFile("Epistemos/Models/HTMLWorkspacePackage.swift")

        #expect(packageSource.contains("isStarterTemplateContent"))
        #expect(documentSource.contains("validateNoStarterTemplateOverwrite"))
        #expect(documentSource.contains("Refusing to overwrite an existing HTML Workspace with the starter template"))
        #expect(documentSource.contains("existingPackage(at: existingFileURL)"))
        #expect(documentSource.contains("!existingPackage.isStarterTemplateContent"))
    }

    @Test("HTML Workspace DOM outline extracts attribute values instead of names")
    func htmlWorkspaceDOMOutlineExtractsAttributeValues() throws {
        let editorSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceDOMOutline.swift")

        #expect(editorSource.contains("captureAttribute(\"id\""))
        #expect(editorSource.contains("captureAttribute(\"class\""))
        #expect(editorSource.contains("match.numberOfRanges > 1"))
        #expect(editorSource.contains("Range(match.range(at: 1), in: attributes)"))
        #expect(!editorSource.contains("Range(match.range(at: 2), in: attributes)"))
    }

    @Test("HTML Workspace edits route through structured patch commands")
    func htmlWorkspaceRoutesStructuredPatches() throws {
        let routerSource = try loadMirroredSourceTextFile("Epistemos/Engine/HTMLWorkspacePatchRouter.swift")
        let editorSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceEditorView.swift")
        let regenerateSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceRegenerateSurface.swift")
        let previewSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceRegeneratePreview.swift")
        let supportSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceEditorSupport.swift")
        let chatTypes = try loadMirroredSourceTextFile("Epistemos/Models/ChatTypes.swift")

        #expect(routerSource.contains("epistemos-html-workspace-patch"))
        #expect(routerSource.contains("containsPatchBlock(in response: String)"))
        #expect(regenerateSource.contains("HTMLWorkspacePatchCommandParser.containsPatchBlock(in: response)"))
        #expect(regenerateSource.contains("String(value.prefix(limit + 32))"))
        #expect(regenerateSource.contains("String(bounded.prefix(limit - 3)) + \"...\""))
        #expect(previewSource.contains("String(instruction.prefix(240 + 32))"))
        #expect(previewSource.contains("String(trimmed.prefix(240 - 3)) + \"...\""))
        #expect(!regenerateSource.contains("response.contains(\"```\\(HTMLWorkspacePatchCommandParser.fencedLanguage)\""))
        #expect(routerSource.contains("HTMLWorkspacePatchCommandBatch"))
        #expect(routerSource.contains("expected_content_hash"))
        #expect(routerSource.contains("maxOperations"))
        #expect(routerSource.contains("replaceDataJSON"))
        #expect(routerSource.contains("setDataFeed"))
        #expect(routerSource.contains("case replaceDocument"))
        #expect(routerSource.contains("case regenerate"))
        #expect(routerSource.contains("case setRoute"))
        #expect(routerSource.contains("case removeRoute"))
        #expect(routerSource.contains("case removeAsset"))
        #expect(routerSource.contains("case restoreSnapshot"))
        #expect(routerSource.contains("applyingAtomically(to:"))
        #expect(routerSource.contains("document.setPackage(stagedPackage)"))
        #expect(routerSource.contains("Provenance: \\(snapshot.generationProvenance?.displayText(currentContentHash: snapshot.contentHash)"))
        #expect(routerSource.contains("Full-surface replacement: use replaceDocument/regenerate"))
        #expect(routerSource.contains("Live data operation: setDataFeed"))
        #expect(routerSource.contains("window.webkit.messagehandlers"))
        #expect(routerSource.contains("applyPatchCommands"))
        #expect(routerSource.contains("var visible = response"))
        #expect(routerSource.contains("Allowed Operations:"))
        #expect(routerSource.contains("replaceDocument, regenerate"))
        #expect(routerSource.contains("setRoute, removeRoute"))
        #expect(routerSource.contains("addAsset, removeAsset, captureSnapshot, restoreSnapshot"))
        #expect(supportSource.contains("allowedPatchOperations"))
        #expect(supportSource.contains(#""setDataFeed""#))
        #expect(supportSource.contains(#""setRoute", "removeRoute""#))
        #expect(supportSource.contains(#""addAsset", "removeAsset", "captureSnapshot", "restoreSnapshot""#))
        #expect(supportSource.contains(#""replaceDocument", "regenerate""#))
        #expect(editorSource.contains("restorePreviousSurface()"))
        #expect(editorSource.contains(#"Button("Add Route""#))
        #expect(editorSource.contains(#"Button("Remove Route""#))
        #expect(editorSource.contains(#"Button("Add Asset""#))
        #expect(editorSource.contains(#"Button("Remove Asset""#))
        #expect(editorSource.contains("@State private var selectedRouteName"))
        #expect(editorSource.contains("private var routeSourceEditor: some View"))
        #expect(editorSource.contains("Picker(\"Route\", selection: routeSelectionBinding)"))
        #expect(editorSource.contains("private var routeSelectionBinding: Binding<String>"))
        #expect(editorSource.contains("private func routeBodyBinding(for routeName: String) -> Binding<String>"))
        #expect(editorSource.contains("workspaceCodeEditor("))
        #expect(editorSource.contains("identity: \"routes-\\(routeName)\""))
        #expect(editorSource.contains("private func addRoute()"))
        #expect(editorSource.contains("private func removeRoute()"))
        #expect(editorSource.contains("private func normalizedRouteName(_ rawName: String) -> String"))
        #expect(editorSource.contains("HTMLWorkspacePatchApplier.apply(.setRoute(name: name, html: html), to: package)"))
        #expect(editorSource.contains("HTMLWorkspacePatchApplier.apply(.removeRoute(name: name), to: package)"))
        #expect(editorSource.contains("HTMLWorkspacePatchApplier.apply("))
        #expect(editorSource.contains(".addAsset(HTMLWorkspaceAsset(name: name, data: data))"))
        #expect(editorSource.contains("HTMLWorkspacePatchApplier.apply(.removeAsset(name: name), to: package)"))
        #expect(editorSource.contains(#""routes/assets/\($0.key)  route-relative mirror""#))
        #expect(editorSource.contains("selectedPane = .assets"))
        #expect(editorSource.contains("selectedPane = .routes"))
        #expect(!routerSource.contains("var visible = parseResult.cleanedText"))
        #expect(chatTypes.contains("contextAttachments"))
    }

    @Test("new visual creation routes to HTML Workspace, not Mermaid")
    func newVisualCreationRoutesToHTMLWorkspace() throws {
        let slash = try loadMirroredSourceTextFile("js-editor/src/extensions/slash-menu.ts")
        let inbound = try loadMirroredSourceTextFile("js-editor/src/bridge/inbound.ts")
        let outbound = try loadMirroredSourceTextFile("js-editor/src/bridge/outbound.ts")
        let editorIndex = try loadMirroredSourceTextFile("js-editor/src/index.ts")
        let legacyDiagram = try loadMirroredSourceTextFile("js-editor/src/extensions/legacy-diagram-node.ts")
        let editorManifest = try loadMirroredSourceTextFile("js-editor/package.json")
        let webpack = try loadMirroredSourceTextFile("js-editor/webpack.config.js")
        let toolbar = try loadMirroredSourceTextFile("Epistemos/Views/Epdoc/EpdocEditorToolbar.swift")
        let dock = try loadMirroredSourceTextFile("Epistemos/Views/Epdoc/EpdocCopilotDockView.swift")
        let bridge = try loadMirroredSourceTextFile("Epistemos/Engine/EpdocEditorBridge.swift")
        let app = try loadMirroredSourceTextFile("Epistemos/App/EpistemosApp.swift")

        #expect(slash.contains("requestHTMLWorkspace"))
        #expect(slash.contains("id: 'html-workspace'"))
        #expect(!slash.contains("insertMermaid"))
        #expect(!slash.contains("RESEARCH_DIAGRAM_TEMPLATES"))
        #expect(!slash.contains("mermaid-flowchart"))
        #expect(!slash.contains("type: 'mermaid'"))
        #expect(!inbound.contains("insertEpdocGraphFromDocument"))
        #expect(outbound.contains("type: 'requestHTMLWorkspace'"))
        #expect(toolbar.contains("openHTMLWorkspace"))
        #expect(!toolbar.contains("insertEpdocGraphFromDocument"))
        #expect(dock.contains("requestHTMLWorkspace"))
        #expect(!dock.contains("insertEpdocGraphFromDocument"))
        #expect(bridge.contains("case requestHTMLWorkspace"))
        #expect(app.contains("New HTML Workspace"))
        #expect(editorIndex.contains("LegacyDiagramNode"))
        #expect(!editorIndex.contains("MermaidNode"))
        #expect(legacyDiagram.contains("Compatibility-only schema node"))
        #expect(legacyDiagram.contains("name: 'mermaid'"))
        #expect(legacyDiagram.contains("data-legacy-diagram"))
        #expect(!legacyDiagram.contains("loadMermaid"))
        #expect(!legacyDiagram.contains("mermaid.min.js"))
        #expect(!repoFileExists("js-editor/src/extensions/mermaid-node.ts"))
        #expect(!editorManifest.contains(#""mermaid":"#))
        #expect(!editorManifest.contains(#""mermaid": "#))
        #expect(!webpack.contains("vendor/mermaid"))
        #expect(!webpack.contains("mermaid.min.js"))
    }
}

@Suite("HTML Workspace DOM outline regressions", .serialized)
// UAS-EXEMPT: source-guard test fixture, not persisted substrate data.
nonisolated struct HTMLWorkspaceDOMOutlineRegressionTests {
    @Test("handles id and class attributes without capture crashes")
    func handlesAttributesWithoutCaptureCrash() {
        let outline = HTMLWorkspaceDOMOutline.outline(
            for: #"<main id="hero" class="workspace shell"><section data-panel="notes"></section></main>"#
        )

        #expect(outline.contains("<main#hero.workspace.shell>"))
        #expect(outline.contains("<section> data"))
    }

    @Test("DOM snapshot records source kind and node count")
    func snapshotRecordsSourceKindAndNodeCount() {
        let snapshot = HTMLWorkspaceDOMOutline.snapshot(
            for: #"<main><section data-panel="notes"></section></main>"#,
            source: .live
        )

        #expect(snapshot.source == .live)
        #expect(snapshot.nodeCount == 2)
        #expect(snapshot.outline.contains("<section> data"))
    }
}

@Suite("HTML Workspace MarkEdit source editor regressions", .serialized)
// UAS-EXEMPT: source-guard test fixture, not persisted substrate data.
nonisolated struct HTMLWorkspaceMarkEditSourceEditorRegressionTests {
    @Test("source panes use the app code editor CoreEditor path")
    func sourcePanesUseAppCodeEditorCoreEditorPath() throws {
        let editorSource = try loadMirroredSourceTextFile("Epistemos/Views/HTMLWorkspace/HTMLWorkspaceEditorView.swift")

        #expect(editorSource.contains("private func workspaceCodeEditor("))
        #expect(editorSource.contains("identity: String? = nil"))
        #expect(editorSource.contains("MarkEditCodeEditorRepresentable("))
        #expect(editorSource.contains("cursorLine: $sourceCursorLine"))
        #expect(editorSource.contains("cursorColumn: $sourceCursorColumn"))
        #expect(editorSource.contains("totalLines: $sourceTotalLines"))
        #expect(editorSource.contains("showLineNumbers: sourceShowLineGutter"))
        #expect(!editorSource.contains("HTMLWorkspaceCodeEditor("))
        #expect(!editorSource.contains("TextEditor("))
    }
}
