import Testing
import Foundation

@testable import Epistemos

// SS-HW (owner 2026-06-20: "the html workspace does not work as well but idk if its marked as such").
// These pin the HONEST capability ledger: live means proven in-app, not merely wired in code.
// The advanced seams have code wiring, but shared out-of-lane compile blockers can stop launch before
// in-app proof, so they must stay non-live until current in-app proof exists.
@Suite("SS-HW — honest HTML Workspace capability status")
struct SSHWCapabilityStatusTests {

    @Test("the live capabilities are the real working ones")
    func liveCapabilitiesAreReal() {
        let live = HTMLWorkspaceCapabilityStatus.capabilities.filter(\.isLive).map(\.name)
        #expect(live.contains { $0.contains("editing") })
        #expect(live.contains { $0.contains("preview") })
        #expect(live.contains { $0.contains("patch") })
        #expect(live.contains { $0.contains("routes") })
        #expect(live.contains { $0.contains("data.json") })
        #expect(live.contains { $0.contains("Live-DOM outline") })
        #expect(!live.contains { $0.contains("Full-surface regenerate") })
        #expect(!live.contains { $0.contains("App message-bridge") })
        #expect(!live.contains { $0.contains("JS console") })
        #expect(!live.contains { $0.contains("DOM picker") })
        #expect(!live.contains { $0.contains("Python") })
    }

    @Test("advanced seams remain non-live until current in-app proof exists")
    func advancedSeamsRemainNonLiveUntilInAppProofExists() {
        let appBridge = HTMLWorkspaceCapabilityStatus.capabilities.first { $0.name == "App message-bridge" }
        #expect(appBridge?.isLive == false)
        #expect(appBridge?.note.contains("Sandbox-gated") == true)
        #expect(appBridge?.note.contains("response event") == true)
        #expect(appBridge?.note.contains("required command-matched correlated response events") == true)
        #expect(appBridge?.note.contains("promise request helper") == true)
        #expect(appBridge?.note.contains("insertable demo scaffold") == true)
        #expect(appBridge?.note.contains("awaits current in-app proof") == true)
        let regenerate = HTMLWorkspaceCapabilityStatus.capabilities.first { $0.name == "Full-surface regenerate" }
        #expect(regenerate?.isLive == false)
        #expect(regenerate?.note.contains("one-click stream-to-preview/apply") == true)
        #expect(regenerate?.note.contains("primary stream context-query auto-attach") == true)
        #expect(regenerate?.note.contains("hash-matched preview apply gating") == true)
        #expect(regenerate?.note.contains("visible revert") == true)
        #expect(regenerate?.note.contains("revert snapshot preserved through snapshot churn") == true)
        #expect(regenerate?.note.contains("snapshot-backed revert enablement") == true)
        #expect(regenerate?.note.contains("pixel-captioned presets") == true)
        #expect(regenerate?.note.contains("advanced manual fallback") == true)
        #expect(regenerate?.note.contains("workspace-context grounding") == true)
        #expect(regenerate?.note.contains("bounded context payloads") == true)
        #expect(regenerate?.note.contains("explicit recent-capture context feed") == true)
        #expect(regenerate?.note.contains("explicit standalone note context feed") == true)
        #expect(regenerate?.note.contains("recent-note fallback") == true)
        #expect(regenerate?.note.contains("explicit PDF-note context feed") == true)
        #expect(regenerate?.note.contains("explicit folder-note context feed") == true)
        #expect(regenerate?.note.contains("explicit meeting-note context feed") == true)
        #expect(regenerate?.note.contains("explicit web-clip context feed") == true)
        #expect(regenerate?.note.contains("explicit recent-chat context feed") == true)
        #expect(regenerate?.note.contains("explicit provenance-claim context feed") == true)
        #expect(regenerate?.note.contains("explicit graph-related-note context feed") == true)
        #expect(regenerate?.note.contains("normalized explicit context metadata") == true)
        #expect(regenerate?.note.contains("context metadata/source labels") == true)
        #expect(regenerate?.note.contains("context metadata/source labels/status fields") == true)
        #expect(regenerate?.note.contains("source-family feed metadata provenance") == true)
        #expect(regenerate?.note.contains("provenance-aware vault-data preset prompts") == true)
        #expect(regenerate?.note.contains("required-source availability metadata that survives data-feed refresh") == true)
        #expect(regenerate?.note.contains("manifest-hash-stamped context feeds") == true)
        #expect(regenerate?.note.contains("structured prompt context records") == true)
        #expect(regenerate?.note.contains("stable drag context IDs") == true)
        #expect(regenerate?.note.contains("selected-preview prompt targeting") == true)
        #expect(regenerate?.note.contains("target-aware stream loading preview") == true)
        #expect(regenerate?.note.contains("source-kind compact feed status") == true)
        #expect(regenerate?.note.contains("source-kind compact feed status with required-source availability") == true)
        #expect(regenerate?.note.contains("in-preview context picker") == true)
        #expect(regenerate?.note.contains("source-visible in-preview context picker") == true)
        #expect(regenerate?.note.contains("source-visible preview context sidebar") == true)
        #expect(regenerate?.note.contains("native payload-aware generated drop zones") == true)
        #expect(regenerate?.note.contains("labelled stale status") == true)
        #expect(regenerate?.note.contains("generated dashboard section nav") == true)
        #expect(regenerate?.note.contains("generated data-backed context picker") == true)
        #expect(regenerate?.note.contains("generated data-backed context picker with pick-to-pin") == true)
        #expect(regenerate?.note.contains("generated context app-bridge event recording") == true)
        #expect(regenerate?.note.contains("generated pinned-context tray") == true)
        #expect(regenerate?.note.contains("in-memory generated pinned-context tray") == true)
        #expect(regenerate?.note.contains("persisted generated pinned-context tray") == false)
        #expect(regenerate?.note.contains("generated drag-to-pin context tray") == true)
        #expect(regenerate?.note.contains("generated data-backed sorting") == true)
        #expect(regenerate?.note.contains("scoped context-tab visible counts") == true)
        #expect(regenerate?.note.contains("clickable tabbed vault result detail panes") == true)
        #expect(regenerate?.note.contains("awaits current in-app proof") == true)
        let python = HTMLWorkspaceCapabilityStatus.capabilities.first { $0.name == "Python (Pyodide / WASM)" }
        #expect(python?.isLive == false)
        #expect(python?.note.contains("local/blob worker CSP") == true)
        #expect(python?.note.contains("insertable demo scaffold") == true)
        #expect(python?.note.contains("runtime probe") == true)
        #expect(python?.note.contains("awaits current in-app proof") == true)
        let domPicker = HTMLWorkspaceCapabilityStatus.capabilities.first { $0.name == "DOM picker / style inspector" }
        #expect(domPicker?.isLive == false)
        #expect(domPicker?.note.contains("hover-highlighted picker") == true)
        #expect(domPicker?.note.contains("escaped selector copy") == true)
        #expect(domPicker?.note.contains("focused style edits") == true)
        #expect(domPicker?.note.contains("awaits current in-app proof") == true)
        #expect(domPicker?.note.contains("open-panel probe path") == true)
    }

    @Test("counts + summary are consistent + honest")
    func countsAndSummaryConsistent() throws {
        let total = HTMLWorkspaceCapabilityStatus.capabilities.count
        #expect(HTMLWorkspaceCapabilityStatus.liveCount + HTMLWorkspaceCapabilityStatus.deferredCount == total)
        #expect(HTMLWorkspaceCapabilityStatus.liveCount < total)
        #expect(HTMLWorkspaceCapabilityStatus.deferredCount == 5)
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("data.json"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("routes"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("HTML/PDF"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("site folders"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("route-relative asset mirrors"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("live DOM outline"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("current in-app proof"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("Full regenerate stream-to-preview/apply/revert UX"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("primary stream context-query auto-attach"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("hash-matched preview apply gating"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("revert snapshot preserved through snapshot churn"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("snapshot-backed revert enablement"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("pixel-captioned presets"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("workspace-context grounding"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("bounded context payloads"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("explicit recent-capture context feed"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("explicit standalone note context feed"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("recent-note fallback"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("explicit PDF-note context feed"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("explicit folder-note context feed"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("explicit meeting-note context feed"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("explicit web-clip context feed"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("explicit recent-chat context feed"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("explicit provenance-claim context feed"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("explicit graph-related-note context feed"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("normalized explicit context metadata"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("context metadata/source labels"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("context metadata/source labels/status fields"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("source-family feed metadata provenance"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("provenance-aware vault-data preset prompts"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("required-source availability metadata that survives data-feed refresh"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("manifest-hash-stamped context feeds"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("structured prompt context records"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("stable drag context IDs"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("validated read-only context drops"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("feed-envelope source/query/limit matching"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("selected-preview prompt targeting"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("target-aware stream loading preview"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("source-kind compact feed status"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("source-kind compact feed status with required-source availability"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("in-preview context picker"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("source-visible in-preview context picker"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("source-visible preview context sidebar"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("native payload-aware generated drop zones"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("labelled stale status"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("generated dashboard section nav"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("generated data-backed context picker"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("generated data-backed context picker with pick-to-pin"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("generated context app-bridge event recording"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("generated pinned-context tray"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("in-memory generated pinned-context tray"))
        #expect(!HTMLWorkspaceCapabilityStatus.summary.contains("persisted generated pinned-context tray"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("generated drag-to-pin context tray"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("generated data-backed sorting"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("scoped context-tab visible counts"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("clickable tabbed vault result detail panes"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("app bridge demo/runtime with promise requests"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("hover-highlighted DOM picker"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("focused style edits"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("Pyodide"))
        #expect(HTMLWorkspaceCapabilityStatus.summary.contains("local/blob worker CSP"))
        let source = try loadMirroredSourceTextFile("Epistemos/Engine/HTMLWorkspaceCapabilityStatus.swift")
        #expect(source.contains("out-of-lane build error"))
        #expect(!source.contains("Landing compile error"))
    }
}
