//! Source:
//! - Doctrine §3 + §5 row Scan-IR — Lean schema authority, monoid-
//!   associativity certificate per state-transition `⊕`.
//! - Blelloch CMU-CS-90-190 — parallel-scan correctness rests on
//!   associativity of the operator.
//! - Dao/Gu arXiv:2405.21060 §6 — SSD parallel-block scan;
//!   correctness vs sequential is the theorem this cert asserts.
//! - Companion: [`super::grammar`] (the ScanProgram we certify);
//!   [`super::lowering::ssd_block_scan`] (the routine the theorem
//!   claims is equivalent to [`super::evaluator::sequential_scan`]);
//!   sibling certificate.rs modules for EML-IR (iter-13) and
//!   Tropical-IR (iter-22).
//!
//! # Scan-IR Lean certificate
//!
//! Emits Lean 4 source as a String targeting `Epistemos.Scan`.
//! `lake build` remains gated by the T5 blocker ledger until
//! `elan`/`lean`/`lake` are available in `PATH`. The emitted
//! theorem obligations:
//!
//! 1. **Monoid associativity** for the user-supplied op `⊕`:
//!    `∀ (a b c : T), (a ⊕ b) ⊕ c = a ⊕ (b ⊕ c)`.
//! 2. **Left-identity** for the user-supplied `identity`:
//!    `∀ (x : T), identity ⊕ x = x`.
//! 3. **SSD parallel-block scan equivalence**: under (1) and (2),
//!    `ssd_block_scan(op, prog, identity, B) = sequential_scan(op, prog)`
//!    for any block size `B ≥ 1`.
//!
//! Theorem (3) is the Phase B3 §4.I:892 acceptance bound. Proofs
//! remain sorry-tracked until the associativity/identity lemmas and
//! Dao-Gu block-scan equivalence lemma are supplied.

use super::grammar::ScanProgram;
use std::fmt::Debug;

/// Stable FNV-1a hash of the scan program's length + step count.
/// (We can't hash a generic T without `Hash` bounds; the length
/// alone gives a useful disambiguation across programs.)
fn program_hash_suffix<T>(program: &ScanProgram<T>) -> String {
    const FNV_OFFSET: u64 = 0xcbf29ce484222325;
    const FNV_PRIME: u64 = 0x100000001b3;
    let mut h = FNV_OFFSET;
    h ^= program.step_count() as u64;
    h = h.wrapping_mul(FNV_PRIME);
    h ^= program.output_count() as u64;
    h = h.wrapping_mul(FNV_PRIME);
    format!("{:016x}", h)
}

/// Emit a Lean 4 certificate for a [`ScanProgram`].
///
/// The output is a single block carrying three sorry-stubbed
/// theorems: monoid-associativity, left-identity, and SSD
/// equivalence. `T` is a type parameter referenced as `T` in the
/// emitted Lean source; the caller is responsible for matching
/// the symbol in the Lean import scope.
pub fn lean_certificate<T: Debug>(program: &ScanProgram<T>) -> String {
    let suffix = program_hash_suffix(program);
    let n = program.step_count();
    format!(
        "-- Generated by Scan-IR certificate.rs (T5 Phase B3 iter-28)\n\
         -- Source: docs/fusion/PRIMITIVE_IR_STACK_DOCTRINE_2026_05_17.md §3 + §5 (row Scan-IR)\n\
         -- ScanProgram: step_count = {n}, output_count = {oc}\n\
         -- T3 coordination: F-SemiseparableBlockScan-Correctness gate\n\
         -- Schema: lean/Epistemos/Epistemos/Scan.lean\n\
         import Epistemos.Scan\n\
         \n\
         namespace Epistemos.Scan.Generated\n\
         \n\
         theorem scan_monoid_assoc_{suffix} :\n\
         \x20   ∀ (T : Type) (op : T → T → T) (a b c : T),\n\
         \x20     op (op a b) c = op a (op b c) := by\n\
         \x20 sorry  -- caller-supplied op MUST be associative\n\
         \n\
         theorem scan_left_identity_{suffix} :\n\
         \x20   ∀ (T : Type) (op : T → T → T) (identity x : T),\n\
         \x20     op identity x = x := by\n\
         \x20 sorry  -- caller-supplied identity MUST be a left-identity\n\
         \n\
         theorem scan_ssd_equivalence_{suffix} :\n\
         \x20   ∀ (T : Type) (op : T → T → T) (identity : T)\n\
         \x20     (initial : T) (inputs : List T) (B : Nat),\n\
         \x20     B ≥ 1 →\n\
         \x20     ssd_block_scan op initial inputs identity B =\n\
         \x20       sequential_scan op initial inputs := by\n\
         \x20 sorry  -- Dao/Gu §6: under associativity + left-identity\n\
         \n\
         theorem scan_certificate_target_shape_{suffix} :\n\
         \x20   ∀ (T : Type) (w : Epistemos.Scan.MonoidWitness T)\n\
         \x20     (program : Epistemos.Scan.Program T) (output : List T),\n\
         \x20     output = Epistemos.Scan.sequentialScan w.op program.initial program.inputs →\n\
         \x20     Nonempty (Epistemos.Scan.CertificateTarget T) := by\n\
         \x20 intro T w program output h\n\
         \x20 exact ⟨{{ monoid := w, program := program, output := output, output_matches := h }}⟩\n\
         \n\
         end Epistemos.Scan.Generated\n\
         \n",
        n = n,
        oc = program.output_count(),
        suffix = suffix,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn certificate_includes_monoid_assoc_theorem() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3]);
        let c = lean_certificate(&p);
        assert!(c.contains("scan_monoid_assoc_"));
        assert!(c.contains("op (op a b) c = op a (op b c)"));
    }

    #[test]
    fn certificate_includes_left_identity_theorem() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3]);
        let c = lean_certificate(&p);
        assert!(c.contains("scan_left_identity_"));
        assert!(c.contains("op identity x = x"));
    }

    #[test]
    fn certificate_includes_ssd_equivalence_theorem() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3]);
        let c = lean_certificate(&p);
        assert!(c.contains("scan_ssd_equivalence_"));
        assert!(c.contains("ssd_block_scan"));
        assert!(c.contains("sequential_scan"));
    }

    #[test]
    fn certificate_targets_scan_schema_module() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3]);
        let c = lean_certificate(&p);
        assert!(c.contains("import Epistemos.Scan"));
        assert!(c.contains("Epistemos.Scan.MonoidWitness"));
        assert!(c.contains("Epistemos.Scan.CertificateTarget"));
    }

    #[test]
    fn certificate_carries_step_count_comment() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3, 4, 5]);
        let c = lean_certificate(&p);
        assert!(c.contains("step_count = 5"));
        assert!(c.contains("output_count = 6"));
    }

    #[test]
    fn certificate_carries_sorry_proof_bodies() {
        let p = ScanProgram::new(0i64, vec![]);
        let c = lean_certificate(&p);
        assert_eq!(c.matches("sorry").count(), 3);
    }

    #[test]
    fn certificate_header_cites_phase_b3_iter_28() {
        let p = ScanProgram::new(0i64, vec![]);
        let c = lean_certificate(&p);
        assert!(c.contains("iter-28"));
    }

    #[test]
    fn certificate_header_mentions_t3_coordination() {
        let p = ScanProgram::new(0i64, vec![]);
        let c = lean_certificate(&p);
        assert!(c.contains("F-SemiseparableBlockScan-Correctness"));
    }

    #[test]
    fn certificate_uses_stable_hash_for_same_length() {
        let p1 = ScanProgram::new(0i64, vec![1, 2, 3]);
        let p2 = ScanProgram::new(99i64, vec![10, 20, 30]);
        // Same step_count + output_count → same hash suffix.
        assert_eq!(program_hash_suffix(&p1), program_hash_suffix(&p2));
    }

    #[test]
    fn certificate_hash_differs_for_different_lengths() {
        let p1 = ScanProgram::new(0i64, vec![1, 2, 3]);
        let p2 = ScanProgram::new(0i64, vec![1, 2, 3, 4]);
        assert_ne!(program_hash_suffix(&p1), program_hash_suffix(&p2));
    }

    #[test]
    fn certificate_is_deterministic_for_same_program() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3]);
        let c1 = lean_certificate(&p);
        let c2 = lean_certificate(&p);
        assert_eq!(c1, c2);
    }
}
