//! Source:
//! - Doctrine §3 + §5 row Scan-IR — Lean schema authority, monoid-
//!   associativity certificate per state-transition `⊕`.
//! - Blelloch CMU-CS-90-190 — parallel-scan correctness rests on
//!   associativity of the operator.
//! - Dao/Gu arXiv:2405.21060 §6 — SSD parallel-block scan;
//!   correctness vs sequential is the theorem this cert asserts.
//! - Companion: [`super::grammar`] (the ScanProgram we certify);
//!   [`super::lowering::ssd_block_scan`] (the routine the theorem
//!   claims is equivalent to [`super::evaluator::sequential_scan`]);
//!   sibling certificate.rs modules for EML-IR (iter-13) and
//!   Tropical-IR (iter-22).
//!
//! # Scan-IR Lean certificate
//!
//! Emits Lean 4 source as a String targeting `Epistemos.Scan`.
//! The committed schema module built with explicit `~/.elan/bin`
//! PATH, and obligations were sharpened through iter-698 with zero
//! sorries in committed Lean sources.
//! The emitted theorem obligations:
//!
//! 1. **Monoid associativity** closed from `MonoidWitness.assoc`
//!    through `Epistemos.Scan.scanAssociativeOp`.
//! 2. **Identity laws** closed from `MonoidWitness.left_identity`
//!    and `MonoidWitness.right_identity` through the Scan schema
//!    predicates.
//! 3. **SSD parallel-block scan equivalence**: under the witness,
//!    routed through `Epistemos.Scan.ssdEquivalentToSequential`.
//! 4. **Certificate target construction**: a direct
//!    `Epistemos.Scan.CertificateTarget` term from the supplied
//!    sequential-output equality.
//!
//! Theorem (3) is the Phase B3 §4.I:892 acceptance bound and closes
//! only when the caller supplies `Epistemos.Scan.SSDEquivalenceLemma`.

use super::grammar::ScanProgram;
use std::fmt::Debug;

/// Stable FNV-1a hash of the scan program's length + step count.
/// (We can't hash a generic T without `Hash` bounds; the length
/// alone gives a useful disambiguation across programs.)
fn program_hash_suffix<T>(program: &ScanProgram<T>) -> String {
    const FNV_OFFSET: u64 = 0xcbf29ce484222325;
    const FNV_PRIME: u64 = 0x100000001b3;
    let mut h = FNV_OFFSET;
    h ^= program.step_count() as u64;
    h = h.wrapping_mul(FNV_PRIME);
    h ^= program.output_count() as u64;
    h = h.wrapping_mul(FNV_PRIME);
    format!("{:016x}", h)
}

/// Emit a Lean 4 certificate for a [`ScanProgram`].
///
/// The output is a single block carrying witness-closed monoid
/// associativity and left-identity theorems plus one SSD equivalence
/// theorem closed from an explicit `SSDEquivalenceLemma` witness.
pub fn lean_certificate<T: Debug>(program: &ScanProgram<T>) -> String {
    let suffix = program_hash_suffix(program);
    let n = program.step_count();
    format!(
        "-- Generated by Scan-IR certificate.rs (T5 Phase B3 iter-28; Lean-first iter-602)\n\
         -- Source: docs/fusion/PRIMITIVE_IR_STACK_DOCTRINE_2026_05_17.md §3 + §5 (row Scan-IR)\n\
         -- ScanProgram: step_count = {n}, output_count = {oc}\n\
         -- T3 coordination: F-SemiseparableBlockScan-Correctness gate\n\
         -- Schema: lean/Epistemos/Epistemos/Scan.lean\n\
         -- Schema module built with explicit ~/.elan/bin PATH; obligations sharpened through iter-698.\n\
         -- Generated SSD proof body closes from explicit SSDEquivalenceLemma.\n\
         -- Generated monoid law bundle closes from MonoidWitness.scanLawWitnesses.\n\
         -- Generated SSD obligation predicate closes from SSDEquivalenceObligation.toSchemaPredicate.\n\
         import Epistemos.Scan\n\
         \n\
         namespace Epistemos.Scan.Generated\n\
         \n\
         theorem scan_monoid_assoc_{suffix} :\n\
         \x20   ∀ (T : Type) (w : Epistemos.Scan.MonoidWitness T),\n\
         \x20     Epistemos.Scan.scanAssociativeOp w.op := by\n\
         \x20 intro T w\n\
         \x20 exact w.assoc\n\
         \n\
         theorem scan_left_identity_{suffix} :\n\
         \x20   ∀ (T : Type) (w : Epistemos.Scan.MonoidWitness T),\n\
         \x20     Epistemos.Scan.scanLeftIdentity w.op w.identity := by\n\
         \x20 intro T w\n\
         \x20 exact w.left_identity\n\
         \n\
         theorem scan_right_identity_{suffix} :\n\
         \x20   ∀ (T : Type) (w : Epistemos.Scan.MonoidWitness T),\n\
         \x20     Epistemos.Scan.scanRightIdentity w.op w.identity := by\n\
         \x20 intro T w\n\
         \x20 exact w.right_identity\n\
         \n\
         theorem scan_monoid_laws_{suffix} :\n\
         \x20   ∀ (T : Type) (w : Epistemos.Scan.MonoidWitness T),\n\
         \x20     Epistemos.Scan.scanAssociativeOp w.op ∧\n\
         \x20       Epistemos.Scan.scanLeftIdentity w.op w.identity ∧\n\
         \x20       Epistemos.Scan.scanRightIdentity w.op w.identity := by\n\
         \x20 intro T w\n\
         \x20 exact Epistemos.Scan.MonoidWitness.scanLawWitnesses w\n\
         \n\
         theorem scan_ssd_equivalence_{suffix} :\n\
         \x20   ∀ (T : Type) (_ssdLemma : Epistemos.Scan.SSDEquivalenceLemma T)\n\
         \x20     (w : Epistemos.Scan.MonoidWitness T)\n\
         \x20     (initial : T) (inputs : List T) (B : Nat),\n\
         \x20     B ≥ 1 →\n\
         \x20     Epistemos.Scan.ssdEquivalentToSequential w.op w.identity initial inputs B := by\n\
         \x20 intro T ssdLemma w initial inputs B hB\n\
         \x20 exact Epistemos.Scan.SSDEquivalenceLemma.discharge ssdLemma w initial inputs B hB\n\
         \n\
         theorem scan_ssd_obligation_predicate_{suffix} :\n\
         \x20   ∀ (T : Type) (o : Epistemos.Scan.SSDEquivalenceObligation T),\n\
         \x20     Epistemos.Scan.ssdEquivalentToSequential\n\
         \x20       o.monoid.op o.monoid.identity o.initial o.inputs o.blockSize := by\n\
         \x20 intro T o\n\
         \x20 exact Epistemos.Scan.SSDEquivalenceObligation.toSchemaPredicate o\n\
         \n\
         def scan_certificate_target_{suffix}\n\
         \x20   (T : Type) (w : Epistemos.Scan.MonoidWitness T)\n\
         \x20   (program : Epistemos.Scan.Program T) (output : List T)\n\
         \x20   (h : output = Epistemos.Scan.sequentialScan w.op program.initial program.inputs) :\n\
         \x20   Epistemos.Scan.CertificateTarget T :=\n\
         \x20   {{ monoid := w\n\
         \x20     program := program\n\
         \x20     output := output\n\
         \x20     output_matches := h }}\n\
         \n\
         theorem scan_certificate_output_matches_{suffix}\n\
         \x20   (T : Type) (w : Epistemos.Scan.MonoidWitness T)\n\
         \x20   (program : Epistemos.Scan.Program T) (output : List T)\n\
         \x20   (h : output = Epistemos.Scan.sequentialScan w.op program.initial program.inputs) :\n\
         \x20   (scan_certificate_target_{suffix} T w program output h).output_matches = h := by\n\
         \x20 rfl\n\
         \n\
         theorem scan_certificate_output_sequential_{suffix}\n\
         \x20   (T : Type) (w : Epistemos.Scan.MonoidWitness T)\n\
         \x20   (program : Epistemos.Scan.Program T) (output : List T)\n\
         \x20   (h : output = Epistemos.Scan.sequentialScan w.op program.initial program.inputs) :\n\
         \x20   (scan_certificate_target_{suffix} T w program output h).output =\n\
         \x20     Epistemos.Scan.sequentialScan w.op program.initial program.inputs := by\n\
         \x20 exact Epistemos.Scan.CertificateTarget.outputMatchesSequential\n\
         \x20   (scan_certificate_target_{suffix} T w program output h)\n\
         \n\
         end Epistemos.Scan.Generated\n\
         \n",
        n = n,
        oc = program.output_count(),
        suffix = suffix,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn proof_body_sorry_count(certificate: &str) -> usize {
        certificate
            .lines()
            .filter(|line| line.trim_start().starts_with("sorry  --"))
            .count()
    }

    #[test]
    fn certificate_includes_monoid_assoc_theorem() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3]);
        let c = lean_certificate(&p);
        assert!(c.contains("scan_monoid_assoc_"));
        assert!(c.contains("Epistemos.Scan.scanAssociativeOp w.op"));
    }

    #[test]
    fn certificate_includes_left_identity_theorem() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3]);
        let c = lean_certificate(&p);
        assert!(c.contains("scan_left_identity_"));
        assert!(c.contains("Epistemos.Scan.scanLeftIdentity w.op w.identity"));
    }

    #[test]
    fn certificate_includes_ssd_equivalence_theorem() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3]);
        let c = lean_certificate(&p);
        assert!(c.contains("scan_ssd_equivalence_"));
        assert!(c.contains("Epistemos.Scan.ssdEquivalentToSequential"));
    }

    #[test]
    fn certificate_targets_scan_schema_module() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3]);
        let c = lean_certificate(&p);
        assert!(c.contains("import Epistemos.Scan"));
        assert!(c.contains("Epistemos.Scan.MonoidWitness"));
        assert!(c.contains("Epistemos.Scan.CertificateTarget"));
    }

    #[test]
    fn certificate_constructs_scan_target_directly() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3]);
        let c = lean_certificate(&p);
        assert!(c.contains("def scan_certificate_target_"));
        assert!(c.contains("Epistemos.Scan.CertificateTarget T :="));
        assert!(c.contains("output_matches := h"));
        assert!(!c.contains("Nonempty (Epistemos.Scan.CertificateTarget T)"));
    }

    #[test]
    fn certificate_projects_scan_target_output_match() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3]);
        let c = lean_certificate(&p);
        assert!(c.contains("theorem scan_certificate_output_matches_"));
        assert!(c.contains("(scan_certificate_target_"));
        assert!(c.contains(".output_matches = h := by"));
        assert!(c.contains("theorem scan_certificate_output_sequential_"));
        assert!(c.contains("Epistemos.Scan.CertificateTarget.outputMatchesSequential"));
    }

    #[test]
    fn certificate_uses_named_scan_obligation_predicates() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3]);
        let c = lean_certificate(&p);
        assert!(c.contains("Epistemos.Scan.scanAssociativeOp"));
        assert!(c.contains("Epistemos.Scan.scanLeftIdentity"));
        assert!(c.contains("Epistemos.Scan.ssdEquivalentToSequential"));
        assert!(!c.contains("ssd_block_scan"));
        assert!(!c.contains("sequential_scan"));
    }

    #[test]
    fn certificate_closes_monoid_laws_from_witness() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3]);
        let c = lean_certificate(&p);
        assert!(c.contains("w : Epistemos.Scan.MonoidWitness T"));
        assert!(c.contains("theorem scan_monoid_laws_"));
        assert!(c.contains("exact Epistemos.Scan.MonoidWitness.scanLawWitnesses w"));
        assert!(c.contains("exact w.assoc"));
        assert!(c.contains("exact w.left_identity"));
        assert!(c.contains("Epistemos.Scan.scanRightIdentity w.op w.identity"));
        assert!(c.contains("exact w.right_identity"));
        assert!(!c.contains("caller-supplied op MUST"));
        assert_eq!(proof_body_sorry_count(&c), 0);
    }

    #[test]
    fn certificate_carries_step_count_comment() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3, 4, 5]);
        let c = lean_certificate(&p);
        assert!(c.contains("step_count = 5"));
        assert!(c.contains("output_count = 6"));
    }

    #[test]
    fn certificate_closes_ssd_equivalence_from_schema_lemma() {
        let p = ScanProgram::new(0i64, vec![]);
        let c = lean_certificate(&p);
        assert_eq!(proof_body_sorry_count(&c), 0);
        assert!(c.contains("(_ssdLemma : Epistemos.Scan.SSDEquivalenceLemma T)"));
        assert!(!c.contains("(ssdLemma : Epistemos.Scan.SSDEquivalenceLemma T)"));
        assert!(c.contains(
            "exact Epistemos.Scan.SSDEquivalenceLemma.discharge ssdLemma w initial inputs B hB"
        ));
        assert!(!c.contains("exact ssdLemma.statement w initial inputs B hB"));
    }

    #[test]
    fn certificate_routes_ssd_obligation_to_schema_predicate() {
        let p = ScanProgram::new(0i64, vec![]);
        let c = lean_certificate(&p);
        assert!(c.contains("theorem scan_ssd_obligation_predicate_"));
        assert!(c.contains("(o : Epistemos.Scan.SSDEquivalenceObligation T)"));
        assert!(c.contains("exact Epistemos.Scan.SSDEquivalenceObligation.toSchemaPredicate o"));
    }

    #[test]
    fn certificate_header_cites_phase_b3_iter_28() {
        let p = ScanProgram::new(0i64, vec![]);
        let c = lean_certificate(&p);
        assert!(c.contains("iter-28"));
    }

    #[test]
    fn certificate_header_mentions_t3_coordination() {
        let p = ScanProgram::new(0i64, vec![]);
        let c = lean_certificate(&p);
        assert!(c.contains("F-SemiseparableBlockScan-Correctness"));
    }

    #[test]
    fn certificate_header_tracks_schema_build_and_generated_obligation() {
        let p = ScanProgram::new(0i64, vec![]);
        let c = lean_certificate(&p);
        assert!(c.contains(
            "Schema module built with explicit ~/.elan/bin PATH; obligations sharpened through iter-698"
        ));
        assert!(c.contains("Generated SSD proof body closes from explicit SSDEquivalenceLemma"));
        assert!(c.contains(
            "Generated monoid law bundle closes from MonoidWitness.scanLawWitnesses"
        ));
        assert!(c.contains(
            "Generated SSD obligation predicate closes from SSDEquivalenceObligation.toSchemaPredicate"
        ));
        assert!(!c.contains("lake build remains gated"));
    }

    #[test]
    fn certificate_uses_stable_hash_for_same_length() {
        let p1 = ScanProgram::new(0i64, vec![1, 2, 3]);
        let p2 = ScanProgram::new(99i64, vec![10, 20, 30]);
        // Same step_count + output_count → same hash suffix.
        assert_eq!(program_hash_suffix(&p1), program_hash_suffix(&p2));
    }

    #[test]
    fn certificate_hash_differs_for_different_lengths() {
        let p1 = ScanProgram::new(0i64, vec![1, 2, 3]);
        let p2 = ScanProgram::new(0i64, vec![1, 2, 3, 4]);
        assert_ne!(program_hash_suffix(&p1), program_hash_suffix(&p2));
    }

    #[test]
    fn certificate_is_deterministic_for_same_program() {
        let p = ScanProgram::new(0i64, vec![1, 2, 3]);
        let c1 = lean_certificate(&p);
        let c2 = lean_certificate(&p);
        assert_eq!(c1, c2);
    }
}
