//! Source:
//! - Doctrine §3 + §5 row Info-IR — Lean schema authority,
//!   Bregman-positivity certificate obligation.
//! - Amari (Springer 2016) Ch. 6 §6.2 — Bregman divergence
//!   positivity from convexity of A.
//! - Companion: [`super::grammar`] (the InfoExpr we certify);
//!   sibling certificate.rs modules for EML-IR (iter-13),
//!   Tropical-IR (iter-22), Scan-IR (iter-28).
//!
//! # Info-IR Lean certificate
//!
//! Emits Lean 4 source as a String. Does not typecheck (Lean
//! toolchain pin per Wave J B.0.5 is Phase C).
//!
//! The emitted theorem statements:
//!
//! 1. **Bregman positivity**: `KL(P, Q) ≥ 0`.
//! 2. **Bregman non-degeneracy**: `KL(P, Q) = 0 ⟺ P = Q`.
//! 3. **Mirror-descent ↔ Bregman-projected-gradient equivalence**
//!    per Beck-Teboulle 2003 §2.

use super::grammar::{ExpFamily, InfoExpr};

fn family_name(family: &ExpFamily) -> String {
    match family {
        ExpFamily::Bernoulli => "Bernoulli".to_string(),
        ExpFamily::Categorical { k } => format!("Categorical_{}", k),
        ExpFamily::Gaussian { variance } => {
            // Variance encoded with finite precision in the theorem name.
            format!("Gaussian_var_{}", (variance * 1e6) as i64)
        }
    }
}

fn expr_hash_suffix(expr: &InfoExpr) -> String {
    const FNV_OFFSET: u64 = 0xcbf29ce484222325;
    const FNV_PRIME: u64 = 0x100000001b3;
    let mut h = FNV_OFFSET;
    let tag = match expr {
        InfoExpr::LogPartition { .. } => b'L',
        InfoExpr::DualMap { .. } => b'D',
        InfoExpr::KlProjection { .. } => b'K',
    };
    h ^= tag as u64;
    h = h.wrapping_mul(FNV_PRIME);
    match expr {
        InfoExpr::LogPartition { natural_params, .. }
        | InfoExpr::DualMap { natural_params, .. } => {
            for v in natural_params {
                for byte in v.to_bits().to_le_bytes() {
                    h ^= byte as u64;
                    h = h.wrapping_mul(FNV_PRIME);
                }
            }
        }
        InfoExpr::KlProjection { p_params, q_params, .. } => {
            for v in p_params.iter().chain(q_params.iter()) {
                for byte in v.to_bits().to_le_bytes() {
                    h ^= byte as u64;
                    h = h.wrapping_mul(FNV_PRIME);
                }
            }
        }
    }
    format!("{:016x}", h)
}

/// Emit a Lean 4 certificate for an [`InfoExpr`]. Carries
/// Bregman-positivity, Bregman-non-degeneracy, and mirror-descent
/// equivalence theorems (all sorry-stubbed).
pub fn lean_certificate(expr: &InfoExpr) -> String {
    let family = family_name(expr.family());
    let suffix = expr_hash_suffix(expr);
    format!(
        "-- Generated by Info-IR certificate.rs (T5 Phase B4 iter-34)\n\
         -- Source: docs/fusion/PRIMITIVE_IR_STACK_DOCTRINE_2026_05_17.md §3 + §5 (row Info-IR)\n\
         -- Family: {family}\n\
         \n\
         theorem info_bregman_positivity_{suffix} :\n\
         \x20   ∀ (p q : ℝ^n), KL_{family} p q ≥ 0 := by\n\
         \x20 sorry  -- Amari Ch. 6 §6.2: convexity of A ⇒ B_A ≥ 0\n\
         \n\
         theorem info_bregman_non_degeneracy_{suffix} :\n\
         \x20   ∀ (p q : ℝ^n), KL_{family} p q = 0 ↔ p = q := by\n\
         \x20 sorry  -- strict convexity of A on its natural domain\n\
         \n\
         theorem info_mirror_descent_equivalence_{suffix} :\n\
         \x20   ∀ (theta : ℝ^n) (grad : ℝ^n) (step : ℝ),\n\
         \x20     mirror_descent_step {family} theta grad step =\n\
         \x20       bregman_projected_gradient_step {family} theta grad step := by\n\
         \x20 sorry  -- Beck-Teboulle 2003 §2\n\
         \n",
        family = family,
        suffix = suffix,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn certificate_has_positivity_theorem() {
        let e = InfoExpr::log_partition(ExpFamily::Bernoulli, vec![0.0]).unwrap();
        let c = lean_certificate(&e);
        assert!(c.contains("info_bregman_positivity_"));
        assert!(c.contains("KL_Bernoulli p q ≥ 0"));
    }

    #[test]
    fn certificate_has_non_degeneracy_theorem() {
        let e = InfoExpr::log_partition(ExpFamily::Bernoulli, vec![0.0]).unwrap();
        let c = lean_certificate(&e);
        assert!(c.contains("info_bregman_non_degeneracy_"));
        assert!(c.contains("KL_Bernoulli p q = 0 ↔ p = q"));
    }

    #[test]
    fn certificate_has_mirror_descent_equivalence() {
        let e = InfoExpr::log_partition(ExpFamily::Bernoulli, vec![0.0]).unwrap();
        let c = lean_certificate(&e);
        assert!(c.contains("info_mirror_descent_equivalence_"));
        assert!(c.contains("bregman_projected_gradient_step"));
    }

    #[test]
    fn family_name_categorical_includes_k() {
        let e = InfoExpr::log_partition(
            ExpFamily::Categorical { k: 5 },
            vec![0.0, 0.0, 0.0, 0.0],
        )
        .unwrap();
        let c = lean_certificate(&e);
        assert!(c.contains("Categorical_5"));
    }

    #[test]
    fn family_name_gaussian_includes_variance() {
        let e = InfoExpr::log_partition(
            ExpFamily::Gaussian { variance: 2.5 },
            vec![1.0],
        )
        .unwrap();
        let c = lean_certificate(&e);
        // 2.5 * 1e6 as i64 = 2500000
        assert!(c.contains("Gaussian_var_2500000"));
    }

    #[test]
    fn three_sorry_proof_bodies() {
        let e = InfoExpr::log_partition(ExpFamily::Bernoulli, vec![0.0]).unwrap();
        let c = lean_certificate(&e);
        assert_eq!(c.matches("sorry").count(), 3);
    }

    #[test]
    fn header_cites_phase_b4_iter_34() {
        let e = InfoExpr::log_partition(ExpFamily::Bernoulli, vec![0.0]).unwrap();
        let c = lean_certificate(&e);
        assert!(c.contains("iter-34"));
    }

    #[test]
    fn hash_distinguishes_log_partition_from_dual_map() {
        let lp = InfoExpr::log_partition(ExpFamily::Bernoulli, vec![0.5]).unwrap();
        let dm = InfoExpr::dual_map(ExpFamily::Bernoulli, vec![0.5]).unwrap();
        assert_ne!(expr_hash_suffix(&lp), expr_hash_suffix(&dm));
    }

    #[test]
    fn hash_is_stable_across_calls() {
        let e = InfoExpr::log_partition(ExpFamily::Bernoulli, vec![0.0]).unwrap();
        assert_eq!(expr_hash_suffix(&e), expr_hash_suffix(&e));
    }

    #[test]
    fn deterministic_for_same_input() {
        let e = InfoExpr::log_partition(ExpFamily::Bernoulli, vec![0.0]).unwrap();
        let c1 = lean_certificate(&e);
        let c2 = lean_certificate(&e);
        assert_eq!(c1, c2);
    }
}
