//! Source:
//! - iter-1 audit `docs/audits/EML_IR_AUDIT_2026_05_17.md` §6 item 4
//!   ("Lean certificate emission ... a function
//!    `lean_certificate(&EmlExpr) → String` that emits a Lean 4 term
//!    whose typechecking proves the tree well-formed under the
//!    branch-safe typing").
//! - Phase A close-out `docs/audits/PHASE_A_CLOSEOUT_2026_05_17.md`
//!   §3 (iter-13 deliverable).
//! - Doctrine `docs/fusion/PRIMITIVE_IR_STACK_DOCTRINE_2026_05_17.md`
//!   §3 ("Lean schema authority — every IR has a Lean 4 schema
//!    module ... per-tree certificate emission").
//! - Companion: [`super::branched`] (the typestate this module
//!   emits certificates for); [`super::grammar`] (the bare EmlExpr
//!   the emitter walks).
//!
//! # Lean 4 certificate emission
//!
//! This module emits Lean 4 source as a String targeting
//! `Epistemos.EML`. `lake build` remains gated by the T5 blocker
//! ledger until `elan`/`lean`/`lake` are available in `PATH`. The
//! emitter's live obligation is schema-shaped Lean source for the
//! branch-safety, evaluator equality, and positive-value proof rows.
//!
//! The emitted term for a tree is:
//!
//! - `(1 : ℝ)` for an [`super::grammar::EmlExpr::One`] leaf.
//! - `(Real.exp <left> - Real.log <right>)` for an `Eml(l, r)`.
//!
//! The full certificate for a [`super::branched::PositiveEmlExpr`]
//! is a Lean source block targeting `Epistemos.EML.CertificateTarget`:
//!
//! ```text
//! -- Generated by EML-IR certificate.rs (iter-13)
//! import Epistemos.EML
//! namespace Epistemos.EML.Generated
//! noncomputable def eml_expr_<hash> : Epistemos.EML.Expr := ...
//! theorem eml_branch_safe_<hash> :
//!     Epistemos.EML.BranchSafe eml_expr_<hash> := by
//!   sorry
//! noncomputable def eml_certificate_<hash> :
//!     Epistemos.EML.CertificateTarget := ...
//! ```
//!
//! The `sorry` bodies are explicit proof obligations: branch-safe
//! construction, evaluator equality, and positive runtime value.
//! Closing them is gated on the Lean toolchain.
//!
//! ## What the emitter guarantees today
//!
//! - **Schema targeting.** The emitted source imports
//!   `Epistemos.EML` and constructs an `Epistemos.EML.Expr` plus
//!   `Epistemos.EML.CertificateTarget`.
//! - **Round-trip-with-evaluator.** The emitted cached value
//!   matches `PositiveEmlExpr::value()` exactly.
//! - **Determinism.** Same input → same emitted string (no
//!   floating-point formatting drift in the term portion).

use super::branched::PositiveEmlExpr;
use super::grammar::EmlExpr;

/// Lean 4 term for an [`EmlExpr`] subtree.
///
/// Recursive: `One` lowers to `(1 : ℝ)`; `Eml(l, r)` lowers to
/// `(Real.exp <l-term> - Real.log <r-term>)`.
pub fn lean_term(expr: &EmlExpr) -> String {
    match expr {
        EmlExpr::One => "(1 : ℝ)".to_string(),
        EmlExpr::Eml(l, r) => {
            format!(
                "(Real.exp {} - Real.log {})",
                lean_term(l),
                lean_term(r)
            )
        }
    }
}

/// Lean schema constructor term for an [`EmlExpr`] subtree.
///
/// This targets `lean/Epistemos/Epistemos/EML.lean`, not the
/// real-valued semantic expression. Generated certificates use this
/// term to construct `Epistemos.EML.Expr` values.
pub fn lean_expr_term(expr: &EmlExpr) -> String {
    match expr {
        EmlExpr::One => "Epistemos.EML.Expr.one".to_string(),
        EmlExpr::Eml(l, r) => {
            format!(
                "(Epistemos.EML.Expr.eml {} {})",
                lean_expr_term(l),
                lean_expr_term(r)
            )
        }
    }
}

/// Stable per-tree hash for the certificate name. Uses Rust's
/// default `Hasher` indirectly via `format!`-based serialization
/// of the bare expression (deterministic since `EmlExpr` is a
/// simple ADT with `#[derive(Debug)]`).
fn tree_hash_suffix(expr: &EmlExpr) -> String {
    // Stable structural hash: walk the tree and accumulate an
    // FNV-1a 64-bit hash of the canonical "1" / "E" symbols.
    // FNV-1a chosen for determinism + no_std-friendliness.
    const FNV_OFFSET: u64 = 0xcbf29ce484222325;
    const FNV_PRIME: u64 = 0x100000001b3;
    fn step(expr: &EmlExpr, h: &mut u64) {
        match expr {
            EmlExpr::One => {
                *h ^= b'1' as u64;
                *h = h.wrapping_mul(FNV_PRIME);
            }
            EmlExpr::Eml(l, r) => {
                *h ^= b'E' as u64;
                *h = h.wrapping_mul(FNV_PRIME);
                step(l, h);
                *h ^= b',' as u64;
                *h = h.wrapping_mul(FNV_PRIME);
                step(r, h);
                *h ^= b')' as u64;
                *h = h.wrapping_mul(FNV_PRIME);
            }
        }
    }
    let mut h = FNV_OFFSET;
    step(expr, &mut h);
    format!("{:016x}", h)
}

/// Full Lean 4 certificate for a runtime-validated tree. The
/// theorem statement asserts the tree's value is strictly positive;
/// branch-safety and evaluator equality remain sorry-tracked until
/// their source lemmas are supplied.
pub fn lean_certificate(p: &PositiveEmlExpr) -> String {
    let expr_term = lean_expr_term(p.as_expr());
    let semantic_term = lean_term(p.as_expr());
    let suffix = tree_hash_suffix(p.as_expr());
    let value = p.value();
    format!(
        "-- Generated by EML-IR certificate.rs (T5 Phase B1 iter-13)\n\
         -- Source: docs/fusion/PRIMITIVE_IR_STACK_DOCTRINE_2026_05_17.md §3\n\
         -- Schema: lean/Epistemos/Epistemos/EML.lean\n\
         -- Runtime-validated value: {value}\n\
         -- Semantic term: {semantic_term}\n\
         import Epistemos.EML\n\
         \n\
         namespace Epistemos.EML.Generated\n\
         \n\
         noncomputable def eml_expr_{suffix} : Epistemos.EML.Expr :=\n\
         \x20   {expr_term}\n\
         \n\
         noncomputable def eml_value_{suffix} : ℝ :=\n\
         \x20   {value}\n\
         \n\
         theorem eml_branch_safe_{suffix} :\n\
         \x20   Epistemos.EML.BranchSafe eml_expr_{suffix} := by\n\
         \x20 sorry  -- runtime typestate: PositiveEmlExpr carries branch-safe construction\n\
         \n\
         theorem eml_eval_matches_{suffix} :\n\
         \x20   Epistemos.EML.Expr.eval eml_expr_{suffix} = eml_value_{suffix} := by\n\
         \x20 sorry  -- runtime evaluator cached this exact value\n\
         \n\
         theorem eml_positive_value_{suffix} :\n\
         \x20   0 < eml_value_{suffix} := by\n\
         \x20 norm_num [eml_value_{suffix}]\n\
         \n\
         noncomputable def eml_certificate_{suffix} : Epistemos.EML.CertificateTarget :=\n\
         \x20   {{ expr := eml_expr_{suffix}\n\
         \x20     value := eml_value_{suffix}\n\
         \x20     branch_safe := eml_branch_safe_{suffix}\n\
         \x20     value_matches := eml_eval_matches_{suffix}\n\
         \x20     positive_value := eml_positive_value_{suffix} }}\n\
         \n\
         end Epistemos.EML.Generated\n",
        value = value,
        suffix = suffix,
        expr_term = expr_term,
        semantic_term = semantic_term,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lean_term_one_leaf() {
        assert_eq!(lean_term(&EmlExpr::One), "(1 : ℝ)");
    }

    #[test]
    fn lean_term_eml_one_one() {
        let e = EmlExpr::eml(EmlExpr::One, EmlExpr::One);
        assert_eq!(
            lean_term(&e),
            "(Real.exp (1 : ℝ) - Real.log (1 : ℝ))"
        );
    }

    #[test]
    fn lean_term_nested_eml() {
        // eml(eml(One, One), One)
        let inner = EmlExpr::eml(EmlExpr::One, EmlExpr::One);
        let outer = EmlExpr::eml(inner, EmlExpr::One);
        let lt = lean_term(&outer);
        // Outer wraps inner; check both Real.exp and Real.log present.
        assert!(lt.contains("Real.exp (Real.exp"));
        assert!(lt.contains("Real.log (1 : ℝ)"));
    }

    #[test]
    fn lean_term_is_deterministic() {
        let e = EmlExpr::eml(
            EmlExpr::eml(EmlExpr::One, EmlExpr::One),
            EmlExpr::One,
        );
        let a = lean_term(&e);
        let b = lean_term(&e);
        assert_eq!(a, b);
    }

    #[test]
    fn lean_expr_term_one_leaf_targets_schema_constructor() {
        assert_eq!(lean_expr_term(&EmlExpr::One), "Epistemos.EML.Expr.one");
    }

    #[test]
    fn certificate_targets_eml_schema_module() {
        let p = PositiveEmlExpr::one();
        let c = lean_certificate(&p);
        assert!(c.contains("import Epistemos.EML"));
        assert!(c.contains("namespace Epistemos.EML.Generated"));
        assert!(c.contains("Epistemos.EML.CertificateTarget"));
    }

    #[test]
    fn tree_hash_is_stable_across_calls() {
        let e = EmlExpr::eml(EmlExpr::One, EmlExpr::One);
        assert_eq!(tree_hash_suffix(&e), tree_hash_suffix(&e));
    }

    #[test]
    fn tree_hash_differs_for_different_trees() {
        let a = EmlExpr::eml(EmlExpr::One, EmlExpr::One);
        let b = EmlExpr::eml(
            EmlExpr::eml(EmlExpr::One, EmlExpr::One),
            EmlExpr::One,
        );
        assert_ne!(tree_hash_suffix(&a), tree_hash_suffix(&b));
    }

    #[test]
    fn tree_hash_distinguishes_left_vs_right_nest() {
        // eml(eml(One, One), One)  vs  eml(One, eml(One, One))
        // Two distinct trees that both evaluate to non-trivial values.
        let left_nest = EmlExpr::eml(
            EmlExpr::eml(EmlExpr::One, EmlExpr::One),
            EmlExpr::One,
        );
        let right_nest = EmlExpr::eml(
            EmlExpr::One,
            EmlExpr::eml(EmlExpr::One, EmlExpr::One),
        );
        assert_ne!(
            tree_hash_suffix(&left_nest),
            tree_hash_suffix(&right_nest)
        );
    }

    #[test]
    fn certificate_contains_term() {
        let p = PositiveEmlExpr::one();
        let c = lean_certificate(&p);
        assert!(c.contains("(1 : ℝ)"));
    }

    #[test]
    fn certificate_contains_runtime_value() {
        let p = PositiveEmlExpr::one();
        let c = lean_certificate(&p);
        assert!(c.contains("Runtime-validated value: 1"));
    }

    #[test]
    fn certificate_carries_sorry_proof_body() {
        let p = PositiveEmlExpr::one();
        let c = lean_certificate(&p);
        assert!(c.contains("sorry"));
    }

    #[test]
    fn certificate_closes_positive_value_from_runtime_number() {
        let p = PositiveEmlExpr::one();
        let c = lean_certificate(&p);
        assert!(c.contains("eml_positive_value_"));
        assert!(c.contains("norm_num [eml_value_"));
        assert_eq!(c.matches("sorry").count(), 2);
    }

    #[test]
    fn certificate_carries_positivity_goal() {
        let p = PositiveEmlExpr::one();
        let c = lean_certificate(&p);
        assert!(c.contains("0 < eml_value_"));
    }

    #[test]
    fn certificate_header_cites_phase_b1_iter_13() {
        let p = PositiveEmlExpr::one();
        let c = lean_certificate(&p);
        assert!(c.contains("iter-13"));
    }

    #[test]
    fn certificate_for_eml_one_one_emits_e_value() {
        // eml(One, One) evaluates to e ≈ 2.718.
        let b = super::super::branched::BranchedEmlExpr::eml(
            super::super::branched::BranchedEmlExpr::one(),
            PositiveEmlExpr::one(),
        );
        let p = b.try_into_positive().unwrap();
        let c = lean_certificate(&p);
        // The cached value formatted into the comment should be e.
        assert!(c.contains("2.71828"));
    }

    #[test]
    fn certificate_theorem_name_uses_tree_hash() {
        let p = PositiveEmlExpr::one();
        let c = lean_certificate(&p);
        // Format: theorem eml_branch_safe_<16-hex-chars>
        assert!(c.contains("theorem eml_branch_safe_"));
        // Hex suffix is 16 characters of [0-9a-f].
        let needle = "eml_branch_safe_";
        let pos = c.find(needle).unwrap();
        let after = &c[pos + needle.len()..];
        let suffix: String = after.chars().take(16).collect();
        assert_eq!(suffix.len(), 16);
        assert!(suffix.chars().all(|ch| ch.is_ascii_hexdigit()));
    }

    #[test]
    fn certificate_is_deterministic_for_same_input() {
        let p = PositiveEmlExpr::one();
        let c1 = lean_certificate(&p);
        let c2 = lean_certificate(&p);
        assert_eq!(c1, c2);
    }
}
