//! Source:
//! - iter-1 audit `docs/audits/EML_IR_AUDIT_2026_05_17.md` §6 item 4
//!   ("Lean certificate emission ... a function
//!    `lean_certificate(&EmlExpr) → String` that emits a Lean 4 term
//!    whose typechecking proves the tree well-formed under the
//!    branch-safe typing").
//! - Phase A close-out `docs/audits/PHASE_A_CLOSEOUT_2026_05_17.md`
//!   §3 (iter-13 deliverable).
//! - Doctrine `docs/fusion/PRIMITIVE_IR_STACK_DOCTRINE_2026_05_17.md`
//!   §3 ("Lean schema authority — every IR has a Lean 4 schema
//!    module ... per-tree certificate emission").
//! - Companion: [`super::branched`] (the typestate this module
//!   emits certificates for); [`super::grammar`] (the bare EmlExpr
//!   the emitter walks).
//!
//! # Lean 4 certificate emission
//!
//! This module emits Lean 4 source as a String. It does NOT
//! typecheck the emitted term — Lean toolchain pin verification
//! is deferred to Phase C (Wave J B.0.5; the locked stack 4.29.1
//! awaits a manual setup pass per `eml/mod.rs:33-35`). The Phase
//! B1 acceptance is that the emitter produces syntactically
//! plausible Lean 4 that a Phase C typechecker pass can validate.
//!
//! The emitted term for a tree is:
//!
//! - `(1 : ℝ)` for an [`super::grammar::EmlExpr::One`] leaf.
//! - `(Real.exp <left> - Real.log <right>)` for an `Eml(l, r)`.
//!
//! The full certificate for a [`super::branched::PositiveEmlExpr`]
//! is a Lean theorem statement:
//!
//! ```text
//! -- Generated by EML-IR certificate.rs (iter-13)
//! theorem eml_branch_safe_<hash> :
//!     let v := <term>
//!     v > 0 := by
//!   -- runtime-validated value: <cached f64>
//!   sorry
//! ```
//!
//! The `sorry` body is intentional: the proof would discharge
//! the positivity obligation from the cached value, which is
//! Phase C work (needs the Lean toolchain).
//!
//! ## What the emitter guarantees today
//!
//! - **Structural correctness.** The emitted term is well-formed
//!   Lean 4 (parens balanced; `Real.exp` / `Real.log` are valid
//!   `mathlib` references; the theorem body is `sorry`-stubbed so
//!   the whole block parses).
//! - **Round-trip-with-evaluator.** The emitted cached value
//!   matches `PositiveEmlExpr::value()` exactly.
//! - **Determinism.** Same input → same emitted string (no
//!   floating-point formatting drift in the term portion).

use super::branched::PositiveEmlExpr;
use super::grammar::EmlExpr;

/// Lean 4 term for an [`EmlExpr`] subtree.
///
/// Recursive: `One` lowers to `(1 : ℝ)`; `Eml(l, r)` lowers to
/// `(Real.exp <l-term> - Real.log <r-term>)`.
pub fn lean_term(expr: &EmlExpr) -> String {
    match expr {
        EmlExpr::One => "(1 : ℝ)".to_string(),
        EmlExpr::Eml(l, r) => {
            format!(
                "(Real.exp {} - Real.log {})",
                lean_term(l),
                lean_term(r)
            )
        }
    }
}

/// Stable per-tree hash for the certificate name. Uses Rust's
/// default `Hasher` indirectly via `format!`-based serialization
/// of the bare expression (deterministic since `EmlExpr` is a
/// simple ADT with `#[derive(Debug)]`).
fn tree_hash_suffix(expr: &EmlExpr) -> String {
    // Stable structural hash: walk the tree and accumulate an
    // FNV-1a 64-bit hash of the canonical "1" / "E" symbols.
    // FNV-1a chosen for determinism + no_std-friendliness.
    const FNV_OFFSET: u64 = 0xcbf29ce484222325;
    const FNV_PRIME: u64 = 0x100000001b3;
    fn step(expr: &EmlExpr, h: &mut u64) {
        match expr {
            EmlExpr::One => {
                *h ^= b'1' as u64;
                *h = h.wrapping_mul(FNV_PRIME);
            }
            EmlExpr::Eml(l, r) => {
                *h ^= b'E' as u64;
                *h = h.wrapping_mul(FNV_PRIME);
                step(l, h);
                *h ^= b',' as u64;
                *h = h.wrapping_mul(FNV_PRIME);
                step(r, h);
                *h ^= b')' as u64;
                *h = h.wrapping_mul(FNV_PRIME);
            }
        }
    }
    let mut h = FNV_OFFSET;
    step(expr, &mut h);
    format!("{:016x}", h)
}

/// Full Lean 4 certificate for a runtime-validated tree. The
/// theorem statement asserts the tree's value is strictly positive;
/// the proof body is `sorry` (Phase C will discharge).
pub fn lean_certificate(p: &PositiveEmlExpr) -> String {
    let term = lean_term(p.as_expr());
    let suffix = tree_hash_suffix(p.as_expr());
    let value = p.value();
    format!(
        "-- Generated by EML-IR certificate.rs (T5 Phase B1 iter-13)\n\
         -- Source: docs/fusion/PRIMITIVE_IR_STACK_DOCTRINE_2026_05_17.md §3\n\
         -- Runtime-validated value: {value}\n\
         theorem eml_branch_safe_{suffix} :\n\
         \x20   let v := {term}\n\
         \x20   v > 0 := by\n\
         \x20 sorry\n",
        value = value,
        suffix = suffix,
        term = term,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lean_term_one_leaf() {
        assert_eq!(lean_term(&EmlExpr::One), "(1 : ℝ)");
    }

    #[test]
    fn lean_term_eml_one_one() {
        let e = EmlExpr::eml(EmlExpr::One, EmlExpr::One);
        assert_eq!(
            lean_term(&e),
            "(Real.exp (1 : ℝ) - Real.log (1 : ℝ))"
        );
    }

    #[test]
    fn lean_term_nested_eml() {
        // eml(eml(One, One), One)
        let inner = EmlExpr::eml(EmlExpr::One, EmlExpr::One);
        let outer = EmlExpr::eml(inner, EmlExpr::One);
        let lt = lean_term(&outer);
        // Outer wraps inner; check both Real.exp and Real.log present.
        assert!(lt.contains("Real.exp (Real.exp"));
        assert!(lt.contains("Real.log (1 : ℝ)"));
    }

    #[test]
    fn lean_term_is_deterministic() {
        let e = EmlExpr::eml(
            EmlExpr::eml(EmlExpr::One, EmlExpr::One),
            EmlExpr::One,
        );
        let a = lean_term(&e);
        let b = lean_term(&e);
        assert_eq!(a, b);
    }

    #[test]
    fn tree_hash_is_stable_across_calls() {
        let e = EmlExpr::eml(EmlExpr::One, EmlExpr::One);
        assert_eq!(tree_hash_suffix(&e), tree_hash_suffix(&e));
    }

    #[test]
    fn tree_hash_differs_for_different_trees() {
        let a = EmlExpr::eml(EmlExpr::One, EmlExpr::One);
        let b = EmlExpr::eml(
            EmlExpr::eml(EmlExpr::One, EmlExpr::One),
            EmlExpr::One,
        );
        assert_ne!(tree_hash_suffix(&a), tree_hash_suffix(&b));
    }

    #[test]
    fn tree_hash_distinguishes_left_vs_right_nest() {
        // eml(eml(One, One), One)  vs  eml(One, eml(One, One))
        // Two distinct trees that both evaluate to non-trivial values.
        let left_nest = EmlExpr::eml(
            EmlExpr::eml(EmlExpr::One, EmlExpr::One),
            EmlExpr::One,
        );
        let right_nest = EmlExpr::eml(
            EmlExpr::One,
            EmlExpr::eml(EmlExpr::One, EmlExpr::One),
        );
        assert_ne!(
            tree_hash_suffix(&left_nest),
            tree_hash_suffix(&right_nest)
        );
    }

    #[test]
    fn certificate_contains_term() {
        let p = PositiveEmlExpr::one();
        let c = lean_certificate(&p);
        assert!(c.contains("(1 : ℝ)"));
    }

    #[test]
    fn certificate_contains_runtime_value() {
        let p = PositiveEmlExpr::one();
        let c = lean_certificate(&p);
        assert!(c.contains("Runtime-validated value: 1"));
    }

    #[test]
    fn certificate_carries_sorry_proof_body() {
        let p = PositiveEmlExpr::one();
        let c = lean_certificate(&p);
        assert!(c.contains("sorry"));
    }

    #[test]
    fn certificate_carries_positivity_goal() {
        let p = PositiveEmlExpr::one();
        let c = lean_certificate(&p);
        assert!(c.contains("v > 0"));
    }

    #[test]
    fn certificate_header_cites_phase_b1_iter_13() {
        let p = PositiveEmlExpr::one();
        let c = lean_certificate(&p);
        assert!(c.contains("iter-13"));
    }

    #[test]
    fn certificate_for_eml_one_one_emits_e_value() {
        // eml(One, One) evaluates to e ≈ 2.718.
        let b = super::super::branched::BranchedEmlExpr::eml(
            super::super::branched::BranchedEmlExpr::one(),
            PositiveEmlExpr::one(),
        );
        let p = b.try_into_positive().unwrap();
        let c = lean_certificate(&p);
        // The cached value formatted into the comment should be e.
        assert!(c.contains("2.71828"));
    }

    #[test]
    fn certificate_theorem_name_uses_tree_hash() {
        let p = PositiveEmlExpr::one();
        let c = lean_certificate(&p);
        // Format: theorem eml_branch_safe_<16-hex-chars>
        assert!(c.contains("theorem eml_branch_safe_"));
        // Hex suffix is 16 characters of [0-9a-f].
        let needle = "eml_branch_safe_";
        let pos = c.find(needle).unwrap();
        let after = &c[pos + needle.len()..];
        let suffix: String = after.chars().take(16).collect();
        assert_eq!(suffix.len(), 16);
        assert!(suffix.chars().all(|ch| ch.is_ascii_hexdigit()));
    }

    #[test]
    fn certificate_is_deterministic_for_same_input() {
        let p = PositiveEmlExpr::one();
        let c1 = lean_certificate(&p);
        let c2 = lean_certificate(&p);
        assert_eq!(c1, c2);
    }
}
