// SDFLabelAtlas.swift
//
// Load the MTSDF label atlas generated by msdf-atlas-gen into the graph
// engine. Per Tier 1 research ("Epistemos Graph SDF Label System — Deep
// Engineering Report", Part I), and CODEX_PROMPT_CHAIN.md §B-2/B-3.
//
// Pipeline:
//   1. Decode sdf_labels.png → RGBA8 pixel buffer
//   2. Push pixels to Rust via graph_engine_load_label_atlas
//   3. Parse sdf_labels.json → per-glyph UV rects + advance widths
//
// The atlas is generated at build time with:
//     scripts/generate-sdf-atlas.sh
//
// The default v1 graph atlas is JetBrains Mono: monospaced enough to match the
// pixel graph identity, but cleaner than the old blocky retro face at graph
// label sizes.
//
// Critical flags when loading the texture (per Tier 1 §A4):
//   - SRGB: false  (atlas stores distances, NOT colors — sRGB gamma
//                   decoding would corrupt the distance field)
//   - generateMipmaps: false  (SDF sampling is point/bilinear)

import AppKit
import Foundation
import Metal
import os

private let log = Logger(subsystem: "com.epistemos", category: "sdf-labels")

/// Per-glyph atlas metadata parsed from msdf-atlas-gen's JSON output.
/// UV coordinates are already normalized to [0, 1] (divided by atlas size).
/// Plane bounds are in em units relative to the font's line height.
struct SDFGlyph: Sendable {
    /// Atlas UV rect in (x, y, width, height) form, top-left origin.
    /// Matches the Rust `LabelInstance.uv_rect` field layout.
    let uvRect: SIMD4<Float>
    /// Quad half-extents in em units — multiply by font size to get world/screen px.
    let halfWidthEm: Float
    let halfHeightEm: Float
    /// Glyph bearing: offset from baseline in em units. planeBounds.bottom
    /// for the Y bearing, planeBounds.left for X.
    let bearingXEm: Float
    let bearingYEm: Float
    /// Horizontal advance in em units (x-step to the next glyph).
    let advanceEm: Float
}

/// Parsed SDF atlas — texture is uploaded to Rust, metrics stay in Swift
/// for per-frame instance building.
struct SDFLabelAtlas: Sendable {
    let atlasWidth: Int
    let atlasHeight: Int
    /// Distance range in em units — matches -emrange flag at atlas gen time.
    let emRange: Float
    /// Pixel range — matches -pxrange flag at atlas gen time.
    let pxRange: Float
    /// Font line height in em units (usually ~1.2).
    let lineHeightEm: Float
    /// Character → glyph metrics. Keyed by Unicode scalar value.
    let glyphs: [Character: SDFGlyph]
    /// Replacement glyph UV (tofu box) for characters not in the atlas.
    let fallbackGlyph: SDFGlyph?
}

enum SDFLabelAtlasLoader {
    enum LoadError: Error {
        case pngNotFound
        case jsonNotFound
        case pngDecodeFailed
        case jsonParseFailed(String)
        case rustPushFailed
    }

    /// Load the bundled atlas, decode the PNG, push pixels to the graph
    /// engine, and parse the JSON metrics. Call once at graph-engine init.
    ///
    /// `pushPixels` is an injected closure so callers can wire to the
    /// graph engine FFI without this file importing the Rust headers.
    static func load(
        bundle: Bundle = .main,
        resourceName: String = "sdf_labels",
        pushPixels: (Int, Int, UnsafePointer<UInt8>, Int) -> Bool
    ) throws -> SDFLabelAtlas {
        // 1. Locate the bundled PNG + JSON — with graceful fallback to the
        // default "sdf_labels" atlas so adding a font family picker can
        // ship without bundling every variant's atlas upfront.
        func findURLs(_ base: String) -> (URL, URL)? {
            guard let png = bundle.url(forResource: base, withExtension: "png"),
                  let json = bundle.url(forResource: base, withExtension: "json")
            else { return nil }
            return (png, json)
        }
        let urls: (URL, URL)
        if let found = findURLs(resourceName) {
            urls = found
        } else if resourceName != "sdf_labels",
                  let fallback = findURLs("sdf_labels") {
            log.warning(
                "\(resourceName).png/json not bundled — falling back to sdf_labels. Run scripts/generate-sdf-atlas.sh --variant \(resourceName, privacy: .public) to add it."
            )
            urls = fallback
        } else {
            log.error("sdf_labels.png/json not in bundle — run scripts/generate-sdf-atlas.sh")
            throw LoadError.pngNotFound
        }
        let pngURL = urls.0
        let jsonURL = urls.1

        // 2. Decode PNG → RGBA8 bytes.
        let (width, height, pixels) = try decodeRGBA8(at: pngURL)

        // 3. Push pixels to Rust (engine copies internally; buffer can be
        // released after the call returns).
        let ok = pixels.withUnsafeBufferPointer { buf -> Bool in
            guard let base = buf.baseAddress else { return false }
            return pushPixels(width, height, base, buf.count)
        }
        guard ok else {
            log.error("graph_engine_load_label_atlas rejected the buffer")
            throw LoadError.rustPushFailed
        }

        // 4. Parse JSON glyph metrics.
        let data = try Data(contentsOf: jsonURL)
        let metadata = try parseMetadata(data: data, atlasWidth: width, atlasHeight: height)

        log.info("""
            SDF atlas loaded: \(width)x\(height), \
            \(metadata.glyphs.count) glyphs, \
            px_range=\(metadata.pxRange), em_range=\(metadata.emRange)
            """)
        return metadata
    }

    // MARK: - PNG decode

    private static func decodeRGBA8(at url: URL) throws -> (Int, Int, [UInt8]) {
        // Per Tier 1 §A4: the MTSDF atlas encodes DISTANCE values in every
        // channel (RGB = multi-channel SDF, A = true SDF), NOT colors.
        // A `premultipliedLast` CGContext would multiply RGB by A and
        // corrupt the distance field. We read the PNG bytes verbatim via
        // the CGImage's data provider — no color-space conversion, no
        // alpha premultiplication, no sRGB gamma decode.
        guard let source = CGImageSourceCreateWithURL(url as CFURL, nil),
              let cgImage = CGImageSourceCreateImageAtIndex(source, 0, nil),
              let dataProvider = cgImage.dataProvider,
              let rawData = dataProvider.data else {
            throw LoadError.pngDecodeFailed
        }
        let width = cgImage.width
        let height = cgImage.height
        let bpp = cgImage.bitsPerPixel
        let bytesPerRow = cgImage.bytesPerRow
        let alphaInfo = cgImage.alphaInfo

        guard bpp == 32, cgImage.bitsPerComponent == 8 else {
            // msdf-atlas-gen writes 32-bit RGBA PNGs. If the atlas has been
            // re-encoded or the wrong format ended up in the bundle, fail
            // loudly rather than silently mis-decoding.
            log.error("unexpected atlas bit depth: bpp=\(bpp) bpc=\(cgImage.bitsPerComponent)")
            throw LoadError.pngDecodeFailed
        }

        let byteCount = width * height * 4
        guard let bytes = CFDataGetBytePtr(rawData) else {
            throw LoadError.pngDecodeFailed
        }

        // If row stride matches packed bytes we can memcpy in one go;
        // otherwise copy row-by-row to drop any trailing padding.
        var pixels = [UInt8](repeating: 0, count: byteCount)
        pixels.withUnsafeMutableBufferPointer { dst in
            guard let dstBase = dst.baseAddress else { return }
            if bytesPerRow == width * 4 {
                memcpy(dstBase, bytes, byteCount)
            } else {
                for y in 0..<height {
                    let srcRow = bytes.advanced(by: y * bytesPerRow)
                    let dstRow = dstBase.advanced(by: y * width * 4)
                    memcpy(dstRow, srcRow, width * 4)
                }
            }
        }

        // If CoreGraphics reports premultipliedLast, the stored bytes ARE
        // premultiplied — un-multiply so the distance field is restored.
        // msdf-atlas-gen's output is non-premultiplied, so this branch is
        // a safety net rather than the expected path.
        if alphaInfo == .premultipliedLast || alphaInfo == .premultipliedFirst {
            log.warning("PNG reports premultiplied alpha; un-multiplying MTSDF distances")
            pixels.withUnsafeMutableBufferPointer { buf in
                guard let base = buf.baseAddress else { return }
                let stride = 4
                for i in Swift.stride(from: 0, to: byteCount, by: stride) {
                    let a = Int(base[i + 3])
                    if a == 0 || a == 255 { continue }
                    for c in 0..<3 {
                        let v = Int(base[i + c]) * 255 / a
                        base[i + c] = UInt8(Swift.min(255, v))
                    }
                }
            }
        }

        return (width, height, pixels)
    }

    // MARK: - JSON parse

    /// msdf-atlas-gen JSON schema (keys we consume):
    /// ```
    /// {
    ///   "atlas": { "width": 1024, "height": 1024, "distanceRange": 6, ... },
    ///   "metrics": { "emSize": 1, "lineHeight": 1.2, ... },
    ///   "glyphs": [
    ///     { "unicode": 65,
    ///       "advance": 0.527,
    ///       "planeBounds": { "left": 0.04, "bottom": -0.01, "right": 0.62, "top": 0.71 },
    ///       "atlasBounds": { "left": 184.5, "bottom": 435.5, "right": 231.5, "top": 494.5 }
    ///     }, ...
    ///   ]
    /// }
    /// ```
    /// Missing `planeBounds`/`atlasBounds` means a whitespace glyph — we
    /// keep the advance but skip quad drawing for it.
    private static func parseMetadata(
        data: Data,
        atlasWidth: Int,
        atlasHeight: Int
    ) throws -> SDFLabelAtlas {
        guard let root = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw LoadError.jsonParseFailed("root not a dictionary")
        }

        let atlasInfo = root["atlas"] as? [String: Any]
        let pxRange = (atlasInfo?["distanceRange"] as? NSNumber)?.floatValue ?? 6.0
        let emRange = (atlasInfo?["distanceRangeMiddle"] as? NSNumber)?.floatValue ?? 0.4

        let metrics = root["metrics"] as? [String: Any]
        let lineHeightEm = (metrics?["lineHeight"] as? NSNumber)?.floatValue ?? 1.2

        let rawGlyphs = root["glyphs"] as? [[String: Any]] ?? []
        var map: [Character: SDFGlyph] = [:]
        map.reserveCapacity(rawGlyphs.count)
        var fallback: SDFGlyph? = nil

        let atlasWidthF = Float(atlasWidth)
        let atlasHeightF = Float(atlasHeight)

        for entry in rawGlyphs {
            guard let codepoint = (entry["unicode"] as? NSNumber)?.uint32Value,
                  let scalar = Unicode.Scalar(codepoint) else {
                continue
            }
            let advanceEm = (entry["advance"] as? NSNumber)?.floatValue ?? 0

            // Whitespace glyphs have no bounds; carry the advance only.
            guard let planeBounds = entry["planeBounds"] as? [String: Any],
                  let atlasBounds = entry["atlasBounds"] as? [String: Any],
                  let pl = (planeBounds["left"] as? NSNumber)?.floatValue,
                  let pb = (planeBounds["bottom"] as? NSNumber)?.floatValue,
                  let pr = (planeBounds["right"] as? NSNumber)?.floatValue,
                  let pt = (planeBounds["top"] as? NSNumber)?.floatValue,
                  let al = (atlasBounds["left"] as? NSNumber)?.floatValue,
                  let ab = (atlasBounds["bottom"] as? NSNumber)?.floatValue,
                  let ar = (atlasBounds["right"] as? NSNumber)?.floatValue,
                  let at = (atlasBounds["top"] as? NSNumber)?.floatValue else {
                // Whitespace glyph (e.g. space): no visual bounds, just
                // an advance width. We MUST add it to the map so Rust
                // advances the pen instead of falling back to '?'.
                if advanceEm > 0 {
                    let glyph = SDFGlyph(
                        uvRect: .zero,
                        halfWidthEm: 0,
                        halfHeightEm: 0,
                        bearingXEm: 0,
                        bearingYEm: 0,
                        advanceEm: advanceEm
                    )
                    let char = Character(scalar)
                    map[char] = glyph
                }
                continue
            }

            // Atlas UVs — divide by atlas dims. Our generator uses
            // -yorigin top, so `top` is the smaller y value and `bottom`
            // is larger. Width = right-left, height = bottom-top (positive).
            let uvX = al / atlasWidthF
            let uvY = at / atlasHeightF
            let uvW = (ar - al) / atlasWidthF
            let uvH = (ab - at) / atlasHeightF

            let halfWEm = (pr - pl) * 0.5
            let halfHEm = (pt - pb) * 0.5
            let bearingXEm = (pl + pr) * 0.5 // center-x in em units
            let bearingYEm = (pt + pb) * 0.5

            let glyph = SDFGlyph(
                uvRect: SIMD4<Float>(uvX, uvY, uvW, uvH),
                halfWidthEm: halfWEm,
                halfHeightEm: halfHEm,
                bearingXEm: bearingXEm,
                bearingYEm: bearingYEm,
                advanceEm: advanceEm
            )
            let char = Character(scalar)
            map[char] = glyph
            if fallback == nil && codepoint == 63 /* '?' */ {
                fallback = glyph
            }
        }

        return SDFLabelAtlas(
            atlasWidth: atlasWidth,
            atlasHeight: atlasHeight,
            emRange: emRange,
            pxRange: pxRange,
            lineHeightEm: lineHeightEm,
            glyphs: map,
            fallbackGlyph: fallback
        )
    }
}

extension SDFLabelAtlasLoader.LoadError: LocalizedError {
    var errorDescription: String? {
        switch self {
        case .pngNotFound:
            "The bundled SDF atlas image could not be found."
        case .jsonNotFound:
            "The bundled SDF atlas metadata JSON could not be found."
        case .pngDecodeFailed:
            "The bundled SDF atlas image could not be decoded as 32-bit RGBA."
        case .jsonParseFailed(let reason):
            "The bundled SDF atlas metadata could not be parsed: \(reason)"
        case .rustPushFailed:
            "The graph engine rejected the SDF atlas pixel buffer."
        }
    }
}
