import Foundation
import GRDB

// MARK: - ReadableBlocksIndex (universal block-level FTS5 projection)
//
// T+4.4 of `docs/audits/deliberation/T+4_cognitive_artifact_spine_deliberation_20260427.md`
// (cross-ref `docs/architecture/COGNITIVE_ARTIFACT_IMPLEMENTATION_PLAN.md` §5).
//
// New universal projection that absorbs Documents + Raw Thoughts + Code +
// Source into a single block-level FTS5 index. Existing
// `Epistemos/Sync/SearchIndexService.swift` `page_search` + `block_search`
// virtual tables continue to serve Prose-only search until T+13 hardening
// migrates callers — per implementation plan §225 ("Existing page_search
// + block_search tables continue to serve current Prose-only search").
//
// This slice is additive:
//   - own migration namespace ("v3_readable_blocks") so it's idempotent
//     and doesn't collide with SearchIndexService's "v1_page_search" /
//     "v2_block_search" migrations
//   - own helper duplicates (isMissingFTS5Module, tableExists) so this
//     file is self-contained
//   - the caller (AppBootstrap or a search service) hooks `installSchema`
//     into its own DatabaseMigrator chain — wiring lands in T+13
//
// Schema mirrors plan §204-223 verbatim:
//
//     CREATE TABLE readable_blocks (
//       id INTEGER PRIMARY KEY,
//       artifact_id TEXT NOT NULL,
//       artifact_kind TEXT NOT NULL,
//       block_id TEXT NOT NULL,
//       block_kind TEXT NOT NULL,
//       title_path TEXT,
//       body TEXT NOT NULL,
//       updated_at TEXT NOT NULL
//     );
//
//     CREATE VIRTUAL TABLE readable_blocks_fts USING fts5(
//       title_path, body,
//       content='readable_blocks', content_rowid='id'
//     );
//
// Plus INSERT / DELETE / UPDATE triggers keep the FTS index in lock-step
// with the canonical table.

// MARK: ReadableBlockKind

/// Coarse block-kind discriminator stored on every row. Drives UI
/// affordances (icon, indent, prose-vs-code rendering) without the
/// caller having to re-parse the body.
nonisolated public enum ReadableBlockKind: String, Codable, Sendable, Hashable, CaseIterable {
    case paragraph
    case heading
    case code
    case table
    case callout
    case quote
}

// MARK: ReadableBlock (canonical row shape)

/// One row in `readable_blocks`. Generated by an artifact projector
/// (T+4.4 only ships the row + writer; per-artifact projection lands
/// alongside each artifact kind's editor in the call-site rewiring at
/// T+13).
nonisolated public struct ReadableBlock: Hashable, Sendable, Codable {
    public let artifactID: String
    public let artifactKind: ArtifactKind
    public let blockID: String
    public let blockKind: ReadableBlockKind
    /// Breadcrumb-style path: `"Doc Title > Section A > Subsection 2"`.
    /// Optional because top-level blocks have no parent heading.
    public let titlePath: String?
    /// Plain-text body fed into FTS5 — the projector strips marks,
    /// inlines code, etc. so the FTS tokenizer sees clean prose.
    public let body: String
    /// ISO-8601 string for portability with the SQL TEXT column.
    public let updatedAt: String
    /// Owning vault id — RRF Phase-1 future-proofing for multi-vault
    /// scenarios. Optional during the migration window: pre-Phase-1
    /// rows have NULL `vault_id` and remain searchable; post-Phase-1
    /// projectors fill it from the host's active workspace. Phase 4
    /// passes it through `FusionWeights` so per-vault scoping is a
    /// `WHERE vault_id = ?` predicate, not a Swift-side filter.
    public let vaultID: String?

    public init(
        artifactID: String,
        artifactKind: ArtifactKind,
        blockID: String,
        blockKind: ReadableBlockKind,
        titlePath: String? = nil,
        body: String,
        updatedAt: String,
        vaultID: String? = nil
    ) {
        self.artifactID = artifactID
        self.artifactKind = artifactKind
        self.blockID = blockID
        self.blockKind = blockKind
        self.titlePath = titlePath
        self.body = body
        self.updatedAt = updatedAt
        self.vaultID = vaultID
    }

    /// Convenience: convert a `Date` to the canonical `updated_at` form.
    public static func iso8601(_ date: Date) -> String {
        readableBlocksIso8601Formatter.string(from: date)
    }
}

// `ISO8601DateFormatter` is documented thread-safe (Apple guarantees
// concurrent `.string(from:)` calls are safe). Defining the singleton
// at file scope keeps it nonisolated so the `static func iso8601`
// above doesn't trip Swift 6.2's strict-concurrency checker on the
// `.defaultIsolation(MainActor.self)` module-level setting.
private nonisolated(unsafe) let readableBlocksIso8601Formatter: ISO8601DateFormatter = {
    let f = ISO8601DateFormatter()
    f.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
    return f
}()

// MARK: - ReadableBlocksIndex (schema + writer surface)

/// Static schema installer + row writer. Called by the host that owns
/// the GRDB `DatabasePool` (AppBootstrap or a dedicated search service
/// — wiring lands in T+13 hardening, T+4.4 only ships the type).
nonisolated public enum ReadableBlocksIndex {

    /// Migration key. Stable across releases — never rename.
    public static let migrationKey = "v3_readable_blocks"

    /// RRF Phase-1 migration key — adds `vault_id TEXT NULL` column +
    /// indexes on `(updated_at)` and `(vault_id)` for the recency
    /// tie-breaker and per-vault scoping respectively. Stable across
    /// releases. Idempotent via GRDB's migrator (runs once per pool;
    /// existing rows survive with `vault_id IS NULL`).
    public static let migrationKeyVaultID = "v3_1_readable_blocks_vault_id"

    /// Search query result row. Convenience type so callers don't
    /// shape their own.
    public struct SearchHit: Hashable, Sendable {
        public let artifactID: String
        public let artifactKind: ArtifactKind
        public let blockID: String
        public let titlePath: String?
        public let bodySnippet: String
        public let rank: Double
    }

    // MARK: Migration

    /// Register the schema + triggers with a `DatabaseMigrator`. Caller
    /// is expected to invoke `try migrator.migrate(dbPool)` after all
    /// migrations are registered.
    ///
    /// Two migrations run in order:
    ///   1. `v3_readable_blocks` — base schema + FTS5 + triggers
    ///   2. `v3_1_readable_blocks_vault_id` — RRF Phase-1 additive
    ///      `vault_id` column + recency / vault-scoping indexes
    ///
    /// GRDB's migrator runs each registered key exactly once per pool;
    /// re-boot is a no-op so adding a new step here is safe across
    /// existing on-disk databases.
    public static func registerMigration(_ migrator: inout DatabaseMigrator) {
        migrator.registerMigration(migrationKey) { db in
            try installSchema(in: db)
            try installFTSAndTriggersIfAvailable(in: db)
        }
        migrator.registerMigration(migrationKeyVaultID) { db in
            try installVaultIDColumn(in: db)
        }
    }

    /// Install only the canonical table — runs whether or not FTS5 is
    /// available. Split out so older sqlite3 builds can at least keep
    /// the row store + a fallback substring search.
    public static func installSchema(in db: Database) throws {
        try db.execute(sql: """
            CREATE TABLE IF NOT EXISTS readable_blocks (
                id INTEGER PRIMARY KEY,
                artifact_id TEXT NOT NULL,
                artifact_kind TEXT NOT NULL,
                block_id TEXT NOT NULL,
                block_kind TEXT NOT NULL,
                title_path TEXT,
                body TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
        """)

        // Per-artifact lookup index — the projector deletes-then-inserts
        // by artifact_id on every save, so this index is hot.
        try db.execute(sql: """
            CREATE INDEX IF NOT EXISTS readable_blocks_artifact_idx
            ON readable_blocks(artifact_id)
        """)

        // Stable block id within an artifact — supports "jump to block"
        // routing from search hit → ArtifactRoute (per T+4.7) → editor.
        try db.execute(sql: """
            CREATE INDEX IF NOT EXISTS readable_blocks_block_idx
            ON readable_blocks(artifact_id, block_id)
        """)
    }

    /// RRF Phase-1 additive migration step. Adds a nullable `vault_id`
    /// column for multi-vault scoping + indexes that the Phase-2
    /// fusion query relies on:
    ///
    ///   - `readable_blocks_updated_at_idx` — recency tie-breaker
    ///     (Phase 2 ORDER BY uses `updated_at DESC`; without an index
    ///     SQLite would full-scan to sort).
    ///   - `readable_blocks_vault_id_idx` — Phase-4 vault scoping
    ///     (`WHERE vault_id = ?` predicate on multi-vault setups).
    ///
    /// Pre-Phase-1 rows survive with `vault_id IS NULL` — projectors
    /// retrofit on next save (the F8 autosave path's
    /// `replaceAllForArtifact` rewrites every row for the artifact).
    /// Idempotent via GRDB's migrator key, NOT via guards: the
    /// migration only runs once per pool.
    public static func installVaultIDColumn(in db: Database) throws {
        try db.execute(sql: """
            ALTER TABLE readable_blocks ADD COLUMN vault_id TEXT
        """)
        try db.execute(sql: """
            CREATE INDEX IF NOT EXISTS readable_blocks_updated_at_idx
            ON readable_blocks(updated_at)
        """)
        try db.execute(sql: """
            CREATE INDEX IF NOT EXISTS readable_blocks_vault_id_idx
            ON readable_blocks(vault_id)
        """)
    }

    /// Install the FTS5 virtual table + sync triggers. If sqlite3 was
    /// built without FTS5 the call is a no-op (caller can fall back to
    /// substring search via the canonical table).
    public static func installFTSAndTriggersIfAvailable(in db: Database) throws {
        do {
            try db.execute(sql: """
                CREATE VIRTUAL TABLE IF NOT EXISTS readable_blocks_fts USING fts5(
                    title_path,
                    body,
                    content='readable_blocks',
                    content_rowid='id',
                    tokenize='unicode61'
                )
            """)
        } catch {
            guard isMissingFTS5Module(error) else { throw error }
            return
        }

        // INSERT trigger.
        try db.execute(sql: """
            CREATE TRIGGER IF NOT EXISTS readable_blocks_ai AFTER INSERT ON readable_blocks BEGIN
                INSERT INTO readable_blocks_fts(rowid, title_path, body)
                VALUES (new.id, new.title_path, new.body);
            END
        """)

        // DELETE trigger — uses the FTS5 'delete' command form to prune
        // the inverted index entries for the old row.
        try db.execute(sql: """
            CREATE TRIGGER IF NOT EXISTS readable_blocks_ad AFTER DELETE ON readable_blocks BEGIN
                INSERT INTO readable_blocks_fts(readable_blocks_fts, rowid, title_path, body)
                VALUES ('delete', old.id, old.title_path, old.body);
            END
        """)

        // UPDATE trigger — emits delete-then-insert in one transaction
        // so the FTS index stays consistent (the BEFORE form is not
        // needed because we're explicitly issuing both rows of the
        // delete/insert pair).
        try db.execute(sql: """
            CREATE TRIGGER IF NOT EXISTS readable_blocks_au AFTER UPDATE ON readable_blocks BEGIN
                INSERT INTO readable_blocks_fts(readable_blocks_fts, rowid, title_path, body)
                VALUES ('delete', old.id, old.title_path, old.body);
                INSERT INTO readable_blocks_fts(rowid, title_path, body)
                VALUES (new.id, new.title_path, new.body);
            END
        """)
    }

    // MARK: Writer surface

    /// Insert one row. Caller is expected to have called
    /// `replaceAllForArtifact(...)` first when refreshing an artifact's
    /// projection (otherwise duplicate rows accumulate).
    ///
    /// `vault_id` is included in the INSERT (RRF Phase-1) but stays
    /// optional — pre-migration callers using the no-`vaultID`
    /// initializer get NULL, which is a safe default that doesn't
    /// affect single-vault search behavior. Multi-vault hosts pass
    /// the active workspace id through `ReadableBlock.vaultID` so
    /// Phase-4 `WHERE vault_id = ?` predicates scope correctly.
    public static func insert(_ block: ReadableBlock, in db: Database) throws {
        try db.execute(sql: """
            INSERT INTO readable_blocks
                (artifact_id, artifact_kind, block_id, block_kind, title_path, body, updated_at, vault_id)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """, arguments: [
            block.artifactID,
            block.artifactKind.snakeCaseString,
            block.blockID,
            block.blockKind.rawValue,
            block.titlePath,
            block.body,
            block.updatedAt,
            block.vaultID,
        ])
    }

    /// Atomic "replace this artifact's projection" — deletes every
    /// existing row for `artifactID`, then inserts the new set inside
    /// a single GRDB transaction. The triggers keep the FTS index in
    /// lock-step automatically.
    public static func replaceAllForArtifact(
        _ artifactID: String,
        with blocks: [ReadableBlock],
        in db: Database
    ) throws {
        try db.execute(
            sql: "DELETE FROM readable_blocks WHERE artifact_id = ?",
            arguments: [artifactID]
        )
        for block in blocks {
            // Defensive: caller MUST keep all blocks scoped to a single
            // artifactID. Surface the mismatch loudly so the next slice's
            // projector wiring catches it before the DELETE-then-INSERT
            // races with anyone else.
            precondition(
                block.artifactID == artifactID,
                "ReadableBlocksIndex.replaceAllForArtifact: every block must share the same artifact_id (\(artifactID)), got \(block.artifactID)"
            )
            try insert(block, in: db)
        }
    }

    /// Delete every row for `artifactID`. Useful when an artifact is
    /// removed entirely.
    public static func deleteAllForArtifact(_ artifactID: String, in db: Database) throws {
        try db.execute(
            sql: "DELETE FROM readable_blocks WHERE artifact_id = ?",
            arguments: [artifactID]
        )
    }

    // MARK: Reader surface

    /// Count rows for an artifact — useful for tests and diagnostics.
    public static func count(forArtifact artifactID: String, in db: Database) throws -> Int {
        try Int.fetchOne(
            db,
            sql: "SELECT COUNT(*) FROM readable_blocks WHERE artifact_id = ?",
            arguments: [artifactID]
        ) ?? 0
    }

    /// Run an FTS5 MATCH query. Returns ranked hits (lower rank = better
    /// match per FTS5's ranking convention; we negate so callers can sort
    /// descending by `rank` and still get the best match first).
    /// Returns an empty array on a query that produces no hits, or if
    /// FTS5 isn't compiled into sqlite3.
    public static func search(
        _ query: String,
        limit: Int = 50,
        in db: Database
    ) throws -> [SearchHit] {
        guard try tableExists("readable_blocks_fts", in: db) else {
            return try fallbackSubstringSearch(query, limit: limit, in: db)
        }
        do {
            let rows = try Row.fetchAll(
                db,
                sql: """
                    SELECT
                        rb.artifact_id    AS artifact_id,
                        rb.artifact_kind  AS artifact_kind,
                        rb.block_id       AS block_id,
                        rb.title_path     AS title_path,
                        snippet(readable_blocks_fts, 1, '<mark>', '</mark>', '...', 32) AS body_snippet,
                        -bm25(readable_blocks_fts) AS rank
                    FROM readable_blocks_fts
                    JOIN readable_blocks rb ON rb.id = readable_blocks_fts.rowid
                    WHERE readable_blocks_fts MATCH ?
                    ORDER BY rank DESC
                    LIMIT ?
                """,
                arguments: [query, limit]
            )
            let hits = rows.compactMap(searchHit(from:))
            if !hits.isEmpty {
                return hits
            }
        } catch {
            // FTS MATCH has its own query grammar. A literal user query that
            // trips the parser should degrade to the canonical row store
            // rather than making search look broken.
        }

        return try fallbackSubstringSearch(query, limit: limit, in: db)
    }

    // MARK: Helpers (duplicated from SearchIndexService for self-containment)

    private static func fallbackSubstringSearch(
        _ query: String,
        limit: Int,
        in db: Database
    ) throws -> [SearchHit] {
        let terms = query
            .split(whereSeparator: \.isWhitespace)
            .map { escapeLikePattern(String($0).lowercased()) }
            .filter { !$0.isEmpty }
        guard !terms.isEmpty else { return [] }

        let predicate = terms
            .map { _ in
                "(LOWER(COALESCE(title_path, '')) LIKE ? ESCAPE '\\' OR LOWER(body) LIKE ? ESCAPE '\\')"
            }
            .joined(separator: " AND ")
        var arguments: [DatabaseValueConvertible] = []
        for term in terms {
            let pattern = "%\(term)%"
            arguments.append(pattern)
            arguments.append(pattern)
        }
        arguments.append(limit)

        let rows = try Row.fetchAll(
            db,
            sql: """
                SELECT
                    artifact_id,
                    artifact_kind,
                    block_id,
                    title_path,
                    body AS body_snippet,
                    0.0 AS rank
                FROM readable_blocks
                WHERE \(predicate)
                ORDER BY updated_at DESC, id DESC
                LIMIT ?
            """,
            arguments: StatementArguments(arguments)
        )
        return rows.compactMap(searchHit(from:))
    }

    private static func searchHit(from row: Row) -> SearchHit? {
        let kindString: String = row["artifact_kind"]
        guard
            let artifactKind = ArtifactKind.allCases.first(where: { $0.snakeCaseString == kindString })
        else {
            return nil
        }
        return SearchHit(
            artifactID: row["artifact_id"],
            artifactKind: artifactKind,
            blockID: row["block_id"],
            titlePath: row["title_path"],
            bodySnippet: row["body_snippet"],
            rank: row["rank"]
        )
    }

    private static func escapeLikePattern(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "%", with: "\\%")
            .replacingOccurrences(of: "_", with: "\\_")
    }

    private static func isMissingFTS5Module(_ error: Error) -> Bool {
        String(describing: error).localizedCaseInsensitiveContains("no such module: fts5")
    }

    private static func tableExists(_ name: String, in db: Database) throws -> Bool {
        try Bool.fetchOne(
            db,
            sql: "SELECT EXISTS(SELECT 1 FROM sqlite_master WHERE type IN ('table','view') AND name = ?)",
            arguments: [name]
        ) ?? false
    }
}
