//! `.epbox` package parser + validator (Simulation Mode S11;
//! DOCTRINE §7.2 + §7.3).
//!
//! Layout per §7.2:
//!
//!     my_skill.epbox/
//!     ├── manifest.json     (type + signature + applies_to + …)
//!     ├── content/          (type-specific payload)
//!     ├── preview/          (icon + optional unwrap.gif)
//!     └── provenance.json   (origin, license, signature chain)
//!
//! This module owns the structural parsing — the appliers in
//! `super::applier` consume validated `EpBoxContent` payloads to
//! mutate a companion's record.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// All V1 content types per DOCTRINE §7.1. V2+ types
/// (head_shape_unlock, lora_adapter, skill_pack) are listed in
/// the doctrine but NOT yet enumerable here — they land in their
/// own slices.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EpBoxType {
    /// V1 — swap or augment the companion's system prompt.
    SystemPromptPreset,
    /// V1 — enable / disable specific tools for this companion.
    ToolAffinityBundle,
    /// V1 — unlock new prop sprite (cosmetic + tool-affinity bind).
    PropUnlock,
    /// V1 — unlock cosmetic accessory slot.
    AccessoryUnlock,
    /// V1 — unlock a new palette option (does NOT auto-apply).
    PaletteUnlock,
}

impl EpBoxType {
    pub fn as_str(self) -> &'static str {
        match self {
            EpBoxType::SystemPromptPreset => "system_prompt_preset",
            EpBoxType::ToolAffinityBundle => "tool_affinity_bundle",
            EpBoxType::PropUnlock => "prop_unlock",
            EpBoxType::AccessoryUnlock => "accessory_unlock",
            EpBoxType::PaletteUnlock => "palette_unlock",
        }
    }
}

/// Origin / trust class per DOCTRINE §7.3. The applier consults
/// the origin to decide whether a confirmation prompt is needed
/// (Community origin requires per-source approval before first
/// install; Official + UserLocal are auto-trusted).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EpBoxOrigin {
    /// `origin: "official:..."` — bundled with Epistemos or
    /// downloaded from the official registry; signed by the
    /// Epistemos team key. Auto-trusted.
    Official { source: String },
    /// `origin: "community:..."` — public registry (HuggingFace
    /// hub, Epistemos Community Registry); signed by registry.
    /// User must approve first install per source.
    Community { source: String },
    /// `origin: "user:local:..."` — locally generated by the
    /// user (e.g. local fine-tune product). Auto-trusted.
    UserLocal { source: String },
}

impl EpBoxOrigin {
    pub fn parse(s: &str) -> Option<Self> {
        if let Some(rest) = s.strip_prefix("official:") {
            return Some(Self::Official {
                source: rest.to_string(),
            });
        }
        if let Some(rest) = s.strip_prefix("community:") {
            return Some(Self::Community {
                source: rest.to_string(),
            });
        }
        if let Some(rest) = s.strip_prefix("user:local:") {
            return Some(Self::UserLocal {
                source: rest.to_string(),
            });
        }
        None
    }

    pub fn is_auto_trusted(&self) -> bool {
        matches!(self, Self::Official { .. } | Self::UserLocal { .. })
    }

    pub fn raw(&self) -> String {
        match self {
            Self::Official { source } => format!("official:{source}"),
            Self::Community { source } => format!("community:{source}"),
            Self::UserLocal { source } => format!("user:local:{source}"),
        }
    }
}

/// `applies_to` constraints — limits which companions can
/// receive this gift-box. Empty `roles` / `models` means
/// "applicable to all".
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct AppliesTo {
    #[serde(default)]
    pub role: Vec<String>,
    #[serde(default)]
    pub models: Vec<String>,
}

impl AppliesTo {
    pub fn matches(&self, role: &str, base_model: &str) -> bool {
        let role_ok = self.role.is_empty()
            || self.role.iter().any(|r| r == role);
        let model_ok = self.models.is_empty()
            || self.models.iter().any(|m| Self::glob_match(m, base_model));
        role_ok && model_ok
    }

    /// Trailing-`*` glob match: `claude-sonnet-*` matches
    /// `claude-sonnet-4-6` and `claude-sonnet-3-5`. No other
    /// patterns are supported (keeps the matching cheap and
    /// auditable).
    fn glob_match(pattern: &str, value: &str) -> bool {
        if let Some(prefix) = pattern.strip_suffix('*') {
            value.starts_with(prefix)
        } else {
            pattern == value
        }
    }
}

/// Type-specific content. Each variant carries the payload
/// fields the matching applier needs.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum EpBoxContent {
    SystemPromptPreset {
        /// New system prompt preset slug — replaces the
        /// companion's `system_prompt_preset` column.
        preset_id: String,
        /// Optional inline prompt body when not registry-fetched.
        prompt_body: Option<String>,
    },
    ToolAffinityBundle {
        /// Tool slugs to enable (`code_edit`, `web_search`, …).
        enable: Vec<String>,
        /// Tool slugs to disable. Disable wins if a tool is in
        /// both lists.
        disable: Vec<String>,
    },
    PropUnlock {
        /// New prop slug per DOCTRINE §5.5 (`Wrench`, `Scroll`,
        /// `Magnifier`, `Folder`, `Baton`, `Lantern`).
        prop: String,
        /// `true` = also auto-apply (set as held prop) on
        /// unwrap; `false` = only unlock for selection.
        auto_apply: bool,
    },
    AccessoryUnlock {
        /// New accessory slug (cosmetic-only per §7.1 V1).
        accessory: String,
    },
    PaletteUnlock {
        /// New palette ref (matches `palette_ref` column +
        /// `Resources/CompanionAssets/palettes/<id>.json`).
        palette_ref: String,
    },
}

impl EpBoxContent {
    pub fn type_tag(&self) -> EpBoxType {
        match self {
            EpBoxContent::SystemPromptPreset { .. } => EpBoxType::SystemPromptPreset,
            EpBoxContent::ToolAffinityBundle { .. } => EpBoxType::ToolAffinityBundle,
            EpBoxContent::PropUnlock { .. } => EpBoxType::PropUnlock,
            EpBoxContent::AccessoryUnlock { .. } => EpBoxType::AccessoryUnlock,
            EpBoxContent::PaletteUnlock { .. } => EpBoxType::PaletteUnlock,
        }
    }
}

/// The strongly-typed manifest. Top-level shape mirrors §7.2
/// schema verbatim.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EpBoxManifest {
    pub epbox_version: String,
    pub id: String,
    pub r#type: EpBoxType,
    pub title: String,
    #[serde(default)]
    pub applies_to: AppliesTo,
    pub apply_duration_estimate_ms: u64,
    pub reversible: bool,
    pub license: String,
    /// Raw origin string (`"official:epistemos:starter-pack-v1"`,
    /// `"community:hf:user/skill"`, `"user:local:my-finetune"`).
    /// Parsed into `EpBoxOrigin` via `parsed_origin()`.
    pub origin: String,
    /// Hex-encoded signature over the canonical-JSON form of
    /// the rest of the manifest. V1 doesn't yet verify against
    /// a key registry — `signature` is stored verbatim and
    /// surfaced to the user.
    #[serde(default)]
    pub signature: String,
    /// Optional content payload. When present, content/ is
    /// already inlined inside the manifest (compact gift boxes
    /// for tests + small registry payloads). When absent, the
    /// applier reads `content/<type>.json` from disk.
    #[serde(default)]
    pub content: Option<EpBoxContent>,
}

impl EpBoxManifest {
    pub fn parsed_origin(&self) -> Option<EpBoxOrigin> {
        EpBoxOrigin::parse(&self.origin)
    }
}

/// Resolved `.epbox` package on disk — the manifest plus the
/// content payload (loaded from inline manifest or `content/`).
/// The applier consumes this; the bridge constructs it from a
/// vault-relative path.
#[derive(Debug, Clone, PartialEq)]
pub struct EpBoxPath {
    pub root: PathBuf,
    pub manifest: EpBoxManifest,
    pub content: EpBoxContent,
}

#[derive(Debug, thiserror::Error)]
pub enum EpBoxParseError {
    #[error("epbox path is not a directory: {0:?}")]
    NotADirectory(PathBuf),
    #[error("missing manifest.json at {0:?}")]
    MissingManifest(PathBuf),
    #[error("manifest parse: {0}")]
    ManifestParse(#[source] serde_json::Error),
    #[error("manifest validation: {0}")]
    Validation(String),
    #[error("missing content/{0}.json")]
    MissingContent(String),
    #[error("content parse: {0}")]
    ContentParse(#[source] serde_json::Error),
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("vault sandbox: {0:?} escapes vault_root {1:?}")]
    OutsideVaultRoot(PathBuf, PathBuf),
}

/// Open + validate a `.epbox` directory. The `root` MUST be
/// inside `vault_root` per the §7.3 MAS-profile sandbox rule —
/// caller is responsible for that gate. This function fails
/// loudly when `root` escapes via `..`.
pub fn open_epbox(root: &Path, vault_root: &Path) -> Result<EpBoxPath, EpBoxParseError> {
    if !root.is_dir() {
        return Err(EpBoxParseError::NotADirectory(root.to_path_buf()));
    }
    let canonical_root = root.canonicalize().unwrap_or_else(|_| root.to_path_buf());
    let canonical_vault = vault_root
        .canonicalize()
        .unwrap_or_else(|_| vault_root.to_path_buf());
    if !canonical_root.starts_with(&canonical_vault) {
        return Err(EpBoxParseError::OutsideVaultRoot(
            canonical_root,
            canonical_vault,
        ));
    }

    let manifest_path = root.join("manifest.json");
    if !manifest_path.is_file() {
        return Err(EpBoxParseError::MissingManifest(manifest_path));
    }
    let manifest_bytes = std::fs::read(&manifest_path)?;
    let manifest: EpBoxManifest = serde_json::from_slice(&manifest_bytes)
        .map_err(EpBoxParseError::ManifestParse)?;

    validate_manifest(&manifest)?;

    let content = if let Some(inline) = manifest.content.clone() {
        // Inline — but assert it matches the manifest's type.
        if inline.type_tag() != manifest.r#type {
            return Err(EpBoxParseError::Validation(format!(
                "inline content type {:?} ≠ manifest type {:?}",
                inline.type_tag(),
                manifest.r#type,
            )));
        }
        inline
    } else {
        load_content_from_disk(root, manifest.r#type)?
    };

    Ok(EpBoxPath {
        root: root.to_path_buf(),
        manifest,
        content,
    })
}

/// §7.2 validation — non-empty id / title / origin, parseable
/// origin, version starts with `1.`, sane apply_duration
/// estimate.
fn validate_manifest(m: &EpBoxManifest) -> Result<(), EpBoxParseError> {
    if !m.epbox_version.starts_with("1.") {
        return Err(EpBoxParseError::Validation(format!(
            "epbox_version {:?} not 1.x",
            m.epbox_version
        )));
    }
    if m.id.trim().is_empty() {
        return Err(EpBoxParseError::Validation("id is empty".to_string()));
    }
    if m.title.trim().is_empty() {
        return Err(EpBoxParseError::Validation("title is empty".to_string()));
    }
    if m.parsed_origin().is_none() {
        return Err(EpBoxParseError::Validation(format!(
            "origin {:?} not in 'official:'/'community:'/'user:local:' namespace",
            m.origin
        )));
    }
    // Sanity bound on the apply-duration estimate: the unwrap
    // animation caps at 8 wait loops × 500 ms = 4 s before the
    // progress chip surfaces (§7.4). Estimates above 60 s are
    // almost certainly malformed — surface as validation error.
    if m.apply_duration_estimate_ms == 0 {
        return Err(EpBoxParseError::Validation(
            "apply_duration_estimate_ms must be > 0".to_string(),
        ));
    }
    if m.apply_duration_estimate_ms > 60_000 {
        return Err(EpBoxParseError::Validation(format!(
            "apply_duration_estimate_ms {} exceeds 60 s ceiling",
            m.apply_duration_estimate_ms
        )));
    }
    if m.license.trim().is_empty() {
        return Err(EpBoxParseError::Validation("license is empty".to_string()));
    }
    Ok(())
}

fn load_content_from_disk(
    root: &Path,
    ty: EpBoxType,
) -> Result<EpBoxContent, EpBoxParseError> {
    let filename = format!("{}.json", ty.as_str());
    let path = root.join("content").join(&filename);
    if !path.is_file() {
        return Err(EpBoxParseError::MissingContent(ty.as_str().to_string()));
    }
    let bytes = std::fs::read(path)?;
    let content: EpBoxContent = serde_json::from_slice(&bytes)
        .map_err(EpBoxParseError::ContentParse)?;
    if content.type_tag() != ty {
        return Err(EpBoxParseError::Validation(format!(
            "content/{} declares type {:?} but manifest says {:?}",
            filename,
            content.type_tag(),
            ty,
        )));
    }
    Ok(content)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_manifest(ty: EpBoxType, content: EpBoxContent) -> EpBoxManifest {
        EpBoxManifest {
            epbox_version: "1.0".to_string(),
            id: "01J0123456789ABCDEFGHJKMNPQ".to_string(),
            r#type: ty,
            title: "Test Box".to_string(),
            applies_to: AppliesTo::default(),
            apply_duration_estimate_ms: 50,
            reversible: true,
            license: "CC0-1.0".to_string(),
            origin: "official:epistemos:starter-pack-v1".to_string(),
            signature: "deadbeef".to_string(),
            content: Some(content),
        }
    }

    fn write_manifest(dir: &Path, manifest: &EpBoxManifest) {
        std::fs::create_dir_all(dir).unwrap();
        std::fs::write(
            dir.join("manifest.json"),
            serde_json::to_vec_pretty(manifest).unwrap(),
        )
        .unwrap();
    }

    #[test]
    fn parses_valid_inline_box() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("vault").join("test.epbox");
        std::fs::create_dir_all(tmp.path().join("vault")).unwrap();
        let manifest = fixture_manifest(
            EpBoxType::SystemPromptPreset,
            EpBoxContent::SystemPromptPreset {
                preset_id: "careful_reviewer_v2".to_string(),
                prompt_body: None,
            },
        );
        write_manifest(&dir, &manifest);
        let opened = open_epbox(&dir, &tmp.path().join("vault")).unwrap();
        assert_eq!(opened.manifest.id, manifest.id);
        match opened.content {
            EpBoxContent::SystemPromptPreset { preset_id, .. } => {
                assert_eq!(preset_id, "careful_reviewer_v2");
            }
            _ => panic!("expected SystemPromptPreset"),
        }
    }

    #[test]
    fn rejects_path_outside_vault_root() {
        let tmp = tempfile::tempdir().unwrap();
        let outside = tmp.path().join("outside.epbox");
        let inside = tmp.path().join("vault");
        std::fs::create_dir_all(&inside).unwrap();
        let manifest = fixture_manifest(
            EpBoxType::AccessoryUnlock,
            EpBoxContent::AccessoryUnlock {
                accessory: "scarf".to_string(),
            },
        );
        write_manifest(&outside, &manifest);
        let err = open_epbox(&outside, &inside).unwrap_err();
        assert!(matches!(err, EpBoxParseError::OutsideVaultRoot(..)), "{err:?}");
    }

    #[test]
    fn rejects_unknown_origin_namespace() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("vault").join("bad.epbox");
        std::fs::create_dir_all(tmp.path().join("vault")).unwrap();
        let mut manifest = fixture_manifest(
            EpBoxType::PaletteUnlock,
            EpBoxContent::PaletteUnlock {
                palette_ref: "claude_warm_v1".to_string(),
            },
        );
        manifest.origin = "rando:unknown:source".to_string();
        write_manifest(&dir, &manifest);
        let err = open_epbox(&dir, &tmp.path().join("vault")).unwrap_err();
        assert!(matches!(err, EpBoxParseError::Validation(_)), "{err:?}");
    }

    #[test]
    fn rejects_zero_apply_duration() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("vault").join("zero.epbox");
        std::fs::create_dir_all(tmp.path().join("vault")).unwrap();
        let mut manifest = fixture_manifest(
            EpBoxType::PropUnlock,
            EpBoxContent::PropUnlock {
                prop: "Wrench".to_string(),
                auto_apply: false,
            },
        );
        manifest.apply_duration_estimate_ms = 0;
        write_manifest(&dir, &manifest);
        let err = open_epbox(&dir, &tmp.path().join("vault")).unwrap_err();
        assert!(matches!(err, EpBoxParseError::Validation(_)), "{err:?}");
    }

    #[test]
    fn rejects_apply_duration_above_60s_ceiling() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("vault").join("huge.epbox");
        std::fs::create_dir_all(tmp.path().join("vault")).unwrap();
        let mut manifest = fixture_manifest(
            EpBoxType::PropUnlock,
            EpBoxContent::PropUnlock {
                prop: "Wrench".to_string(),
                auto_apply: false,
            },
        );
        manifest.apply_duration_estimate_ms = 60_001;
        write_manifest(&dir, &manifest);
        let err = open_epbox(&dir, &tmp.path().join("vault")).unwrap_err();
        assert!(matches!(err, EpBoxParseError::Validation(_)), "{err:?}");
    }

    #[test]
    fn applies_to_glob_matches_trailing_star() {
        let a = AppliesTo {
            role: vec!["CodeWorker".to_string()],
            models: vec!["claude-sonnet-*".to_string()],
        };
        assert!(a.matches("CodeWorker", "claude-sonnet-4-6"));
        assert!(a.matches("CodeWorker", "claude-sonnet-3-5"));
        assert!(!a.matches("CodeWorker", "kimi-k2"));
        assert!(!a.matches("Helper", "claude-sonnet-4-6"));
    }

    #[test]
    fn applies_to_empty_lists_match_all() {
        let a = AppliesTo::default();
        assert!(a.matches("Helper", "qwen3-4b-mlx"));
        assert!(a.matches("CodeWorker", "claude-sonnet-4-6"));
    }

    #[test]
    fn epbox_origin_parses_and_round_trips() {
        for raw in [
            "official:epistemos:starter-pack-v1",
            "community:hf:user/cool-skill",
            "user:local:my-finetune-2026",
        ] {
            let parsed = EpBoxOrigin::parse(raw).expect(raw);
            assert_eq!(parsed.raw(), raw);
        }
        assert!(EpBoxOrigin::parse("rando:bad").is_none());
    }

    #[test]
    fn auto_trust_classification() {
        let off = EpBoxOrigin::parse("official:x:y").unwrap();
        let comm = EpBoxOrigin::parse("community:x:y").unwrap();
        let user = EpBoxOrigin::parse("user:local:y").unwrap();
        assert!(off.is_auto_trusted());
        assert!(!comm.is_auto_trusted());
        assert!(user.is_auto_trusted());
    }

    #[test]
    fn rejects_inline_content_type_mismatch() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("vault").join("mismatch.epbox");
        std::fs::create_dir_all(tmp.path().join("vault")).unwrap();
        // Manifest declares PropUnlock but inline content is
        // PaletteUnlock — must reject.
        let mut manifest = fixture_manifest(
            EpBoxType::PropUnlock,
            EpBoxContent::PropUnlock {
                prop: "Wrench".to_string(),
                auto_apply: false,
            },
        );
        manifest.content = Some(EpBoxContent::PaletteUnlock {
            palette_ref: "claude_warm_v1".to_string(),
        });
        write_manifest(&dir, &manifest);
        let err = open_epbox(&dir, &tmp.path().join("vault")).unwrap_err();
        assert!(matches!(err, EpBoxParseError::Validation(_)), "{err:?}");
    }
}
